{"variants":[{"paths":["\/documentation\/hmssdk\/hmssamplebufferdisplayview\/rtcvideorenderer-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssamplebufferdisplayview\/rtcvideorenderer-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/RTCVideoRenderer-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/renderFrame(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/setSize(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"HMSSDK"}],"role":"collectionGroup","title":"RTCVideoRenderer Implementations"},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/setSize(_:)":{"role":"symbol","title":"setSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/setSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSize:"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/setsize(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView":{"role":"symbol","title":"HMSSampleBufferDisplayView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/renderFrame(_:)":{"role":"symbol","title":"renderFrame(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCVideoFrame","preciseIdentifier":"c:objc(cs)RTCVideoFrame"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/renderFrame(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderFrame:"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/renderframe(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/renderFrame(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/setSize(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1setSize(_:)\/title","value":"setSize:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1setSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView\/title","value":"HMSSampleBufferDisplayView"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView\/fragments","value":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1renderFrame(_:)\/title","value":"renderFrame:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1renderFrame(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}