{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssamplebufferdisplayview\/setsize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssamplebufferdisplayview\/setsize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/setSize(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RTCVideoRenderer.setSize(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"title":"setSize(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@HMSSDK@objc(cs)HMSSampleBufferDisplayView(im)setSize:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setSize:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/RTCVideoRenderer-Implementations"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/setSize(_:)":{"role":"symbol","title":"setSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/setSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSize:"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/setsize(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView":{"role":"symbol","title":"HMSSampleBufferDisplayView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/RTCVideoRenderer-Implementations":{"role":"collectionGroup","title":"RTCVideoRenderer Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/RTCVideoRenderer-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/rtcvideorenderer-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSize:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1setSize(_:)\/title","value":"setSize:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1setSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView\/title","value":"HMSSampleBufferDisplayView"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView\/fragments","value":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}