{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollUserTrackingMode","text":"HMSPollUserTrackingMode"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspoll\/mode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/mode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The tracking mode for user participation in the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollUserTrackingMode","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollUserTrackingMode"},{"kind":"text","text":"?"}],"title":"mode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6HMSSDK7HMSPollC4modeAA0B16UserTrackingModeOSgvp","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll":{"role":"symbol","title":"HMSPoll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"abstract":[{"type":"text","text":"Represents a poll object."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}],"url":"\/documentation\/hmssdk\/hmspoll"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode":{"role":"symbol","title":"HMSPollUserTrackingMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"abstract":[{"type":"text","text":"Represents the user tracking mode for poll participation."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/mode":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollUserTrackingMode","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollUserTrackingMode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The tracking mode for user participation in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/mode","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspoll\/mode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/title","value":"HMSPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode\/title","value":"HMSPollUserTrackingMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}