{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"startedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspoll\/startedby"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspoll\/startedby"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedBy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The peer who started the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"startedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"title":"startedBy","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPoll(py)startedBy","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"startedBy"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll":{"role":"symbol","title":"HMSPoll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"abstract":[{"type":"text","text":"Represents a poll object."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}],"url":"\/documentation\/hmssdk\/hmspoll"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/startedBy":{"role":"symbol","title":"startedBy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"startedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The peer who started the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startedBy"}],"url":"\/documentation\/hmssdk\/hmspoll\/startedby"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"startedBy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"startedBy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"startedBy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/title","value":"HMSPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1startedBy\/title","value":"startedBy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1startedBy\/fragments","value":[{"kind":"identifier","text":"startedBy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}