{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory","text":"HMSPollCategory"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspoll\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspoll\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPoll(py)type","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll":{"role":"symbol","title":"HMSPoll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"abstract":[{"type":"text","text":"Represents a poll object."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}],"url":"\/documentation\/hmssdk\/hmspoll"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollCategory":{"role":"symbol","title":"HMSPollCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollCategory"}],"abstract":[{"type":"text","text":"Represents the category of a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollCategory"}],"url":"\/documentation\/hmssdk\/hmspollcategory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory"}],"abstract":[{"type":"text","text":"The type of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/hmssdk\/hmspoll\/type"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory","text":"HMSPollCategory"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/title","value":"HMSPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/title","value":"HMSPollCategory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/fragments","value":[{"kind":"identifier","text":"HMSPollCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}