{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevices"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSDevice","text":"HMSDevice"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsutilities\/getdevices()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsutilities\/getdevices()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getDevices()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevices"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"HMSDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSDevice"},{"kind":"text","text":"]"}],"title":"getDevices()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSUtilities(cm)getDevices","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getDevices"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSDevice":{"role":"symbol","title":"HMSDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDevice"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDevice"}],"url":"\/documentation\/hmssdk\/hmsdevice"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getDevices()":{"role":"symbol","title":"getDevices()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevices"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"HMSDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSDevice"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getDevices()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDevices"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getdevices()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities":{"role":"symbol","title":"HMSUtilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtilities"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUtilities"}],"url":"\/documentation\/hmssdk\/hmsutilities"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getDevices"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDevices"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<HMSDevice *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getDevices"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDevice\/title","value":"HMSDevice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDevice\/fragments","value":[{"kind":"identifier","text":"HMSDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getDevices()\/title","value":"getDevices"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getDevices()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDevices"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities\/title","value":"HMSUtilities"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities\/fragments","value":[{"kind":"identifier","text":"HMSUtilities"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}