{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsutilities\/gettrack(for:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsutilities\/gettrack(for:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getTrack(for:in:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"?"}],"title":"getTrack(for:in:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSUtilities(cm)getTrackFor:in:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getTrackFor:in:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack":{"role":"symbol","title":"HMSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrack"}],"abstract":[{"type":"text","text":"A track represents either the audio or video that makes up a stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrack"}],"url":"\/documentation\/hmssdk\/hmstrack"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getTrack(for:in:)":{"role":"symbol","title":"getTrack(for:in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getTrack(for:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTrackFor:in:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/gettrack(for:in:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities":{"role":"symbol","title":"HMSUtilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtilities"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUtilities"}],"url":"\/documentation\/hmssdk\/hmsutilities"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom":{"role":"symbol","title":"HMSRoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}],"url":"\/documentation\/hmssdk\/hmsroom"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getTrackFor:in:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getTrackFor:in:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getTrackFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"id"},{"kind":"text","text":" "},{"kind":"identifier","text":"in:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"room"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/title","value":"HMSTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/fragments","value":[{"kind":"identifier","text":"HMSTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getTrack(for:in:)\/title","value":"getTrackFor:in:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getTrack(for:in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getTrackFor:in:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities\/title","value":"HMSUtilities"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities\/fragments","value":[{"kind":"identifier","text":"HMSUtilities"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/title","value":"HMSRoom"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}