{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY","doc:\/\/live.100ms.HMS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_BridgedStoredNSError.Code"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"HMSError.Code","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@HMSError","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/alreadyJoined","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/audiovideoSubsystemFailure","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/cantAccessCaptureDevice","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/codecChangeNotPermitted","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createAnswerFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createOfferFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/endpointUnreachable","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/genericTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/iceDisconnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/iceFailure","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/invalidEndpointUrl","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/invalidTokenFormat","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/jsonParsingFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/micCaptureFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/notConnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/nothingToReturn","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/peerMetadataMissing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/rtcTrackMissing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/setLocalDescriptionFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/setRemoteDescriptionFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/trackMetadataMissing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/unknown","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/websocketConnectionLost"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/genericTrack":{"role":"symbol","title":"HMSError.Code.genericTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericTrack"}],"abstract":[{"type":"text","text":"Unknown error during track creation. Check error message for more info."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/genericTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorGenericTrack"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/generictrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/invalidTokenFormat":{"role":"symbol","title":"HMSError.Code.invalidTokenFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTokenFormat"}],"abstract":[{"type":"text","text":"Token is not in proper JWT format"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/invalidTokenFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorInvalidTokenFormat"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/invalidtokenformat"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/alreadyJoined":{"role":"symbol","title":"HMSError.Code.alreadyJoined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyJoined"}],"abstract":[{"type":"text","text":"Already joined"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/alreadyJoined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorAlreadyJoined"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/alreadyjoined"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/createAnswerFailed":{"role":"symbol","title":"HMSError.Code.createAnswerFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnswerFailed"}],"abstract":[{"type":"text","text":"Failed to establish audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createAnswerFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/createanswerfailed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/codecChangeNotPermitted":{"role":"symbol","title":"HMSError.Code.codecChangeNotPermitted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecChangeNotPermitted"}],"abstract":[{"type":"text","text":"Codec change is not permitted during a call"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/codecChangeNotPermitted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorCodecChangeNotPermitted"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/codecchangenotpermitted"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/unknown":{"role":"symbol","title":"HMSError.Code.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Generic SDK error. Some unforseen exception happened."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorUnknown"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/unknown"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/websocketConnectionLost":{"role":"symbol","title":"HMSError.Code.websocketConnectionLost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketConnectionLost"}],"abstract":[{"type":"text","text":"Lost signalling connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/websocketConnectionLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorWebsocketConnectionLost"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/websocketconnectionlost"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/rtcTrackMissing":{"role":"symbol","title":"HMSError.Code.rtcTrackMissing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcTrackMissing"}],"abstract":[{"type":"text","text":"RTC Track is missing"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/rtcTrackMissing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorRtcTrackMissing"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/rtctrackmissing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/setRemoteDescriptionFailed":{"role":"symbol","title":"HMSError.Code.setRemoteDescriptionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteDescriptionFailed"}],"abstract":[{"type":"text","text":"Failed to establish audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/setRemoteDescriptionFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorSetRemoteDescriptionFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/setremotedescriptionfailed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/cantAccessCaptureDevice":{"role":"symbol","title":"HMSError.Code.cantAccessCaptureDevice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cantAccessCaptureDevice"}],"abstract":[{"type":"text","text":"User denied permission to access capture device"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/cantAccessCaptureDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorCantAccessCaptureDevice"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/cantaccesscapturedevice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/micCaptureFailed":{"role":"symbol","title":"HMSError.Code.micCaptureFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"micCaptureFailed"}],"abstract":[{"type":"text","text":"Unable to capture audio from mic"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/micCaptureFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorMicCaptureFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/miccapturefailed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/endpointUnreachable":{"role":"symbol","title":"HMSError.Code.endpointUnreachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointUnreachable"}],"abstract":[{"type":"text","text":"Endpoint is not responding"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/endpointUnreachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/endpointunreachable"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/jsonParsingFailed":{"role":"symbol","title":"HMSError.Code.jsonParsingFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonParsingFailed"}],"abstract":[{"type":"text","text":"Failed to parse JSON message"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/jsonParsingFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorJsonParsingFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/jsonparsingfailed"},"doc://live.100ms.HMS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/live.100ms.HMS\/s8SendableP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/notConnected":{"role":"symbol","title":"HMSError.Code.notConnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notConnected"}],"abstract":[{"type":"text","text":"Not connected"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/notConnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorNotConnected"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/notconnected"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct":{"role":"symbol","title":"HMSError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSError"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/trackMetadataMissing":{"role":"symbol","title":"HMSError.Code.trackMetadataMissing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackMetadataMissing"}],"abstract":[{"type":"text","text":"Track metadata missing"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/trackMetadataMissing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorTrackMetadataMissing"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/trackmetadatamissing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/peerMetadataMissing":{"role":"symbol","title":"HMSError.Code.peerMetadataMissing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerMetadataMissing"}],"abstract":[{"type":"text","text":"Peer metadata missing"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/peerMetadataMissing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorPeerMetadataMissing"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/peermetadatamissing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/nothingToReturn":{"role":"symbol","title":"HMSError.Code.nothingToReturn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nothingToReturn"}],"abstract":[{"type":"text","text":"Audio and video publishing is disabled. Check the room template settings in the dashboard."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/nothingToReturn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorNothingToReturn"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/nothingtoreturn"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/createOfferFailed":{"role":"symbol","title":"HMSError.Code.createOfferFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOfferFailed"}],"abstract":[{"type":"text","text":"Failed to establish audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createOfferFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorCreateOfferFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/createofferfailed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/invalidEndpointUrl":{"role":"symbol","title":"HMSError.Code.invalidEndpointUrl","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidEndpointUrl"}],"abstract":[{"type":"text","text":"Custom endpoint url is malformed"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/invalidEndpointUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorInvalidEndpointUrl"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/invalidendpointurl"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/iceDisconnected":{"role":"symbol","title":"HMSError.Code.iceDisconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iceDisconnected"}],"abstract":[{"type":"text","text":"Lost audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/iceDisconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorIceDisconnected"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/icedisconnected"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code":{"role":"symbol","title":"HMSError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/iceFailure":{"role":"symbol","title":"HMSError.Code.iceFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iceFailure"}],"abstract":[{"type":"text","text":"Lost audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/iceFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorIceFailure"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/icefailure"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/setLocalDescriptionFailed":{"role":"symbol","title":"HMSError.Code.setLocalDescriptionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalDescriptionFailed"}],"abstract":[{"type":"text","text":"Failed to establish audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/setLocalDescriptionFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorSetLocalDescriptionFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/setlocaldescriptionfailed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/audiovideoSubsystemFailure":{"role":"symbol","title":"HMSError.Code.audiovideoSubsystemFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audiovideoSubsystemFailure"}],"abstract":[{"type":"text","text":"Audio\/Video subsystem Failure"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/audiovideoSubsystemFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorAudiovideoSubsystemFailure"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/audiovideosubsystemfailure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/alreadyJoined","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/audiovideoSubsystemFailure","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/cantAccessCaptureDevice","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/codecChangeNotPermitted","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createAnswerFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createOfferFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/endpointUnreachable","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/genericTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/iceDisconnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/iceFailure","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/invalidEndpointUrl","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/invalidTokenFormat","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/jsonParsingFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/micCaptureFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/notConnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/nothingToReturn","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/peerMetadataMissing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/rtcTrackMissing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/setLocalDescriptionFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/setRemoteDescriptionFailed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/trackMetadataMissing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/unknown","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/websocketConnectionLost"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1genericTrack\/title","value":"HMSErrorGenericTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1genericTrack\/fragments","value":[{"kind":"identifier","text":"HMSErrorGenericTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1invalidTokenFormat\/title","value":"HMSErrorInvalidTokenFormat"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1invalidTokenFormat\/fragments","value":[{"kind":"identifier","text":"HMSErrorInvalidTokenFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1alreadyJoined\/title","value":"HMSErrorAlreadyJoined"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1alreadyJoined\/fragments","value":[{"kind":"identifier","text":"HMSErrorAlreadyJoined"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1createAnswerFailed\/title","value":"HMSErrorCreateAnswerFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1createAnswerFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1codecChangeNotPermitted\/title","value":"HMSErrorCodecChangeNotPermitted"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1codecChangeNotPermitted\/fragments","value":[{"kind":"identifier","text":"HMSErrorCodecChangeNotPermitted"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1unknown\/title","value":"HMSErrorUnknown"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1unknown\/fragments","value":[{"kind":"identifier","text":"HMSErrorUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1websocketConnectionLost\/title","value":"HMSErrorWebsocketConnectionLost"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1websocketConnectionLost\/fragments","value":[{"kind":"identifier","text":"HMSErrorWebsocketConnectionLost"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1rtcTrackMissing\/title","value":"HMSErrorRtcTrackMissing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1rtcTrackMissing\/fragments","value":[{"kind":"identifier","text":"HMSErrorRtcTrackMissing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1setRemoteDescriptionFailed\/title","value":"HMSErrorSetRemoteDescriptionFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1setRemoteDescriptionFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorSetRemoteDescriptionFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1cantAccessCaptureDevice\/title","value":"HMSErrorCantAccessCaptureDevice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1cantAccessCaptureDevice\/fragments","value":[{"kind":"identifier","text":"HMSErrorCantAccessCaptureDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1micCaptureFailed\/title","value":"HMSErrorMicCaptureFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1micCaptureFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorMicCaptureFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1endpointUnreachable\/title","value":"HMSErrorEndpointUnreachable"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1endpointUnreachable\/fragments","value":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1jsonParsingFailed\/title","value":"HMSErrorJsonParsingFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1jsonParsingFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorJsonParsingFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1notConnected\/title","value":"HMSErrorNotConnected"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1notConnected\/fragments","value":[{"kind":"identifier","text":"HMSErrorNotConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1trackMetadataMissing\/title","value":"HMSErrorTrackMetadataMissing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1trackMetadataMissing\/fragments","value":[{"kind":"identifier","text":"HMSErrorTrackMetadataMissing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1peerMetadataMissing\/title","value":"HMSErrorPeerMetadataMissing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1peerMetadataMissing\/fragments","value":[{"kind":"identifier","text":"HMSErrorPeerMetadataMissing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1nothingToReturn\/title","value":"HMSErrorNothingToReturn"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1nothingToReturn\/fragments","value":[{"kind":"identifier","text":"HMSErrorNothingToReturn"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1createOfferFailed\/title","value":"HMSErrorCreateOfferFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1createOfferFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorCreateOfferFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1invalidEndpointUrl\/title","value":"HMSErrorInvalidEndpointUrl"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1invalidEndpointUrl\/fragments","value":[{"kind":"identifier","text":"HMSErrorInvalidEndpointUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1iceDisconnected\/title","value":"HMSErrorIceDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1iceDisconnected\/fragments","value":[{"kind":"identifier","text":"HMSErrorIceDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/title","value":"HMSError"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"HMSError"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1iceFailure\/title","value":"HMSErrorIceFailure"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1iceFailure\/fragments","value":[{"kind":"identifier","text":"HMSErrorIceFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1setLocalDescriptionFailed\/title","value":"HMSErrorSetLocalDescriptionFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1setLocalDescriptionFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorSetLocalDescriptionFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1audiovideoSubsystemFailure\/title","value":"HMSErrorAudiovideoSubsystemFailure"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1audiovideoSubsystemFailure\/fragments","value":[{"kind":"identifier","text":"HMSErrorAudiovideoSubsystemFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}