{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig","text":"HMSHLSRecordingConfig"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsconfig\/recording"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsconfig\/recording"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig\/recording","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Recording parameters in case recording is required"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig"},{"kind":"text","text":"?"}],"title":"recording","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSHLSConfig(py)recording","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"recording"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSRecordingConfig":{"role":"symbol","title":"HMSHLSRecordingConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSRecordingConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSRecordingConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSRecordingConfig"}],"url":"\/documentation\/hmssdk\/hmshlsrecordingconfig"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSConfig":{"role":"symbol","title":"HMSHLSConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSConfig"}],"url":"\/documentation\/hmssdk\/hmshlsconfig"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSConfig/recording":{"role":"symbol","title":"recording","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Recording parameters in case recording is required"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig\/recording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recording"}],"url":"\/documentation\/hmssdk\/hmshlsconfig\/recording"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recording"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recording"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig","text":"HMSHLSRecordingConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recording"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSRecordingConfig\/title","value":"HMSHLSRecordingConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSRecordingConfig\/fragments","value":[{"kind":"identifier","text":"HMSHLSRecordingConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig\/title","value":"HMSHLSConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig\/fragments","value":[{"kind":"identifier","text":"HMSHLSConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig~1recording\/title","value":"recording"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig~1recording\/fragments","value":[{"kind":"identifier","text":"recording"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}