{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An observer that was returned from the observeChanges API."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssessionstore\/removeobserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssessionstore\/removeobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/removeObserver(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes the previously registerd change observer. It will no longer receive updates post this call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")"}],"title":"removeObserver(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSSessionStore(im)removeObserver:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore":{"role":"symbol","title":"HMSSessionStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSessionStore"}],"abstract":[{"type":"text","text":"The HMSSessionStore class provides a centralized storage solution for session-related data."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSessionStore"}],"url":"\/documentation\/hmssdk\/hmssessionstore"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore/removeObserver(_:)":{"role":"symbol","title":"removeObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the previously registerd change observer. It will no longer receive updates post this call."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/removeObserver(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"url":"\/documentation\/hmssdk\/hmssessionstore\/removeobserver(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeObserver:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeObserver:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeObserver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<NSObject>","preciseIdentifier":"c:Qoobjc(pl)NSObject"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore\/title","value":"HMSSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore\/fragments","value":[{"kind":"identifier","text":"HMSSessionStore"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1removeObserver(_:)\/title","value":"removeObserver:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1removeObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeObserver:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}