{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logger"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogger","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSLogger","text":"HMSLogger"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticsservice\/logger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticsservice\/logger"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService\/logger","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"logger"}],"role":"symbol","title":"logger","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logger"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"HMSLogger","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSLogger"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")?"}],"symbolKind":"property","externalID":"c:objc(pl)HMSAnalyticsService(py)logger","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsService/logger":{"navigatorTitle":[{"kind":"identifier","text":"logger"}],"role":"symbol","title":"logger","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logger"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"HMSLogger","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSLogger"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService\/logger","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsservice\/logger"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsService":{"role":"symbol","title":"HMSAnalyticsService","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsService"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsService"}],"url":"\/documentation\/hmssdk\/hmsanalyticsservice"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogger":{"role":"symbol","title":"HMSLogger","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLogger"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLogger"}],"url":"\/documentation\/hmssdk\/hmslogger"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"logger"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"logger"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSObject<HMSLogger>","preciseIdentifier":"c:Q$objc(cs)NSObject@M@HMSSDK@objc(pl)HMSLogger"},{"kind":"text","text":" * "},{"kind":"identifier","text":"logger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService~1logger\/title","value":"logger"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService~1logger\/fragments","value":[{"kind":"identifier","text":"logger"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService\/title","value":"HMSAnalyticsService"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsService"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogger\/title","value":"HMSLogger"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogger\/fragments","value":[{"kind":"identifier","text":"HMSLogger"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}