{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent","text":"HMSAnalyticsEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticsservice\/queue(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticsservice\/queue(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService\/queue(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"queueEvent:"}],"role":"symbol","title":"queue(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)HMSAnalyticsService(im)queueEvent:","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsService/queue(_:)":{"navigatorTitle":[{"kind":"identifier","text":"queueEvent:"}],"role":"symbol","title":"queue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService\/queue(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsservice\/queue(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent":{"role":"symbol","title":"HMSAnalyticsEvent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEvent"}],"url":"\/documentation\/hmssdk\/hmsanalyticsevent"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsService":{"role":"symbol","title":"HMSAnalyticsService","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsService"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsService"}],"url":"\/documentation\/hmssdk\/hmsanalyticsservice"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"queueEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queueEvent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"queueEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<HMSAnalyticsEvent>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)HMSAnalyticsEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService~1queue(_:)\/title","value":"queueEvent:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService~1queue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queueEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/title","value":"HMSAnalyticsEvent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService\/title","value":"HMSAnalyticsService"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}