{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate","text":"HMSPeerUpdate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"peer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the peer who joined\/left or was updated"}]}]},{"name":"update","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the triggered update type. Should be used to perform different UI Actions"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsdatasource\/on(peer:update:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/on(peer:update:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This will be called whenever there is an update on an existing peer"},{"type":"text","text":" "},{"type":"text","text":"or a new peer got added\/existing peer is removed."},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to keep a track of all the peers in the room"}],"kind":"symbol","metadata":{"role":"symbol","title":"on(peer:update:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:6HMSSDK13HMSDataSourceC2on4peer6updateyAA7HMSPeerC_AA0G6UpdateOtF","extendedModule":"HMSSDK","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/HMSUpdateListener-Implementations"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource/HMSUpdateListener-Implementations":{"role":"collectionGroup","title":"HMSUpdateListener Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/HMSUpdateListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsdatasource\/hmsupdatelistener-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate":{"role":"symbol","title":"HMSPeerUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdate"}],"url":"\/documentation\/hmssdk\/hmspeerupdate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource":{"role":"symbol","title":"HMSDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDataSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDataSource"}],"url":"\/documentation\/hmssdk\/hmsdatasource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource/on(peer:update:)":{"role":"symbol","title":"on(peer:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called whenever there is an update on an existing peer"},{"type":"text","text":" "},{"type":"text","text":"or a new peer got added\/existing peer is removed."},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to keep a track of all the peers in the room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/on(peer:update:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsdatasource\/on(peer:update:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/title","value":"HMSPeerUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}