{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSRoomUpdate","text":"HMSRoomUpdate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"room","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the room which was joined"}]}]},{"name":"update","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the triggered update type. Should be used to perform different UI Actions"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsdatasource\/on(room:update:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/on(room:update:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when there is a change in any property of the Room"}],"kind":"symbol","metadata":{"role":"symbol","title":"on(room:update:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoomUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSRoomUpdate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:6HMSSDK13HMSDataSourceC2on4room6updateyAA7HMSRoomC_AA0G6UpdateOtF","extendedModule":"HMSSDK","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/HMSUpdateListener-Implementations"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate":{"role":"symbol","title":"HMSRoomUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdate"}],"url":"\/documentation\/hmssdk\/hmsroomupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource/HMSUpdateListener-Implementations":{"role":"collectionGroup","title":"HMSUpdateListener Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/HMSUpdateListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsdatasource\/hmsupdatelistener-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource":{"role":"symbol","title":"HMSDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDataSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDataSource"}],"url":"\/documentation\/hmssdk\/hmsdatasource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom":{"role":"symbol","title":"HMSRoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}],"url":"\/documentation\/hmssdk\/hmsroom"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource/on(room:update:)":{"role":"symbol","title":"on(room:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoomUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSRoomUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when there is a change in any property of the Room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/on(room:update:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsdatasource\/on(room:update:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/title","value":"HMSRoomUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/title","value":"HMSRoom"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}