{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSTrackUpdate","text":"HMSTrackUpdate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"track","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the track which was added, removed or updated"}]}]},{"name":"update","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the triggered update type"}]}]},{"name":"peer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the peer for which track was added, removed or updated"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsdatasource\/on(track:update:for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/on(track:update:for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when there are updates on an existing track"},{"type":"text","text":" "},{"type":"text","text":"or a new track got added\/existing track is removed"},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to render the video on screen whenever a track gets added"}],"kind":"symbol","metadata":{"role":"symbol","title":"on(track:update:for:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSTrackUpdate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:6HMSSDK13HMSDataSourceC2on5track6update3forySo8HMSTrackC_AA0H6UpdateOAA7HMSPeerCtF","extendedModule":"HMSSDK","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/HMSUpdateListener-Implementations"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate":{"role":"symbol","title":"HMSTrackUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdate"}],"url":"\/documentation\/hmssdk\/hmstrackupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack":{"role":"symbol","title":"HMSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrack"}],"abstract":[{"type":"text","text":"A track represents either the audio or video that makes up a stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrack"}],"url":"\/documentation\/hmssdk\/hmstrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource":{"role":"symbol","title":"HMSDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDataSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDataSource"}],"url":"\/documentation\/hmssdk\/hmsdatasource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource/HMSUpdateListener-Implementations":{"role":"collectionGroup","title":"HMSUpdateListener Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/HMSUpdateListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsdatasource\/hmsupdatelistener-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource/on(track:update:for:)":{"role":"symbol","title":"on(track:update:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSTrackUpdate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when there are updates on an existing track"},{"type":"text","text":" "},{"type":"text","text":"or a new track got added\/existing track is removed"},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to render the video on screen whenever a track gets added"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource\/on(track:update:for:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsdatasource\/on(track:update:for:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate\/title","value":"HMSTrackUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/title","value":"HMSTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/fragments","value":[{"kind":"identifier","text":"HMSTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}