{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkHealthConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig","preciseIdentifier":"c:objc(cs)HMSNetworkHealthConfig","text":"HMSNetworkHealthConfig"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstransport\/networkhealthconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstransport\/networkhealthconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/networkHealthConfig","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkHealthConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSNetworkHealthConfig","preciseIdentifier":"c:objc(cs)HMSNetworkHealthConfig"},{"kind":"text","text":"?"}],"title":"networkHealthConfig","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSTransport(py)networkHealthConfig","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"networkHealthConfig"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/networkHealthConfig":{"role":"symbol","title":"networkHealthConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkHealthConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSNetworkHealthConfig","preciseIdentifier":"c:objc(cs)HMSNetworkHealthConfig"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/networkHealthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"networkHealthConfig"}],"url":"\/documentation\/hmssdk\/hmstransport\/networkhealthconfig"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig":{"role":"symbol","title":"HMSNetworkHealthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport":{"role":"symbol","title":"HMSTransport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTransport"}],"url":"\/documentation\/hmssdk\/hmstransport"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"networkHealthConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"networkHealthConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig","preciseIdentifier":"c:objc(cs)HMSNetworkHealthConfig","text":"HMSNetworkHealthConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"networkHealthConfig"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1networkHealthConfig\/title","value":"networkHealthConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1networkHealthConfig\/fragments","value":[{"kind":"identifier","text":"networkHealthConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig\/title","value":"HMSNetworkHealthConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig\/fragments","value":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/title","value":"HMSTransport"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/fragments","value":[{"kind":"identifier","text":"HMSTransport"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}