{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionFactory"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"RTCPeerConnectionFactory","preciseIdentifier":"c:objc(cs)RTCPeerConnectionFactory"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstransport\/peerconnectionfactory()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstransport\/peerconnectionfactory()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/peerConnectionFactory()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionFactory"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"RTCPeerConnectionFactory","preciseIdentifier":"c:objc(cs)RTCPeerConnectionFactory"}],"title":"peerConnectionFactory()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSTransport(im)peerConnectionFactory","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"peerConnectionFactory"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/peerConnectionFactory()":{"role":"symbol","title":"peerConnectionFactory()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionFactory"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"RTCPeerConnectionFactory","preciseIdentifier":"c:objc(cs)RTCPeerConnectionFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/peerConnectionFactory()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnectionFactory"}],"url":"\/documentation\/hmssdk\/hmstransport\/peerconnectionfactory()"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport":{"role":"symbol","title":"HMSTransport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTransport"}],"url":"\/documentation\/hmssdk\/hmstransport"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"peerConnectionFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnectionFactory"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"RTCPeerConnectionFactory","preciseIdentifier":"c:objc(cs)RTCPeerConnectionFactory"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"peerConnectionFactory"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1peerConnectionFactory()\/title","value":"peerConnectionFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1peerConnectionFactory()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnectionFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/title","value":"HMSTransport"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/fragments","value":[{"kind":"identifier","text":"HMSTransport"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}