{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRegister"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstransport\/track(for:streamid:shouldregister:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstransport\/track(for:streamid:shouldregister:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/track(for:streamId:shouldRegister:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRegister"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"?"}],"title":"track(for:streamId:shouldRegister:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSTransport(im)trackFor:streamId:shouldRegister:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"trackFor:streamId:shouldRegister:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport":{"role":"symbol","title":"HMSTransport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTransport"}],"url":"\/documentation\/hmssdk\/hmstransport"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/track(for:streamId:shouldRegister:)":{"role":"symbol","title":"track(for:streamId:shouldRegister:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRegister"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/track(for:streamId:shouldRegister:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackFor:streamId:shouldRegister:"}],"url":"\/documentation\/hmssdk\/hmstransport\/track(for:streamid:shouldregister:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack":{"role":"symbol","title":"HMSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrack"}],"abstract":[{"type":"text","text":"A track represents either the audio or video that makes up a stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrack"}],"url":"\/documentation\/hmssdk\/hmstrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"trackFor:streamId:shouldRegister:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackFor:streamId:shouldRegister:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"trackFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"track"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRegister:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"shouldRegister"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/title","value":"HMSTransport"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/fragments","value":[{"kind":"identifier","text":"HMSTransport"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1track(for:streamId:shouldRegister:)\/title","value":"trackFor:streamId:shouldRegister:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1track(for:streamId:shouldRegister:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackFor:streamId:shouldRegister:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/title","value":"HMSTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/fragments","value":[{"kind":"identifier","text":"HMSTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}