{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings","text":"HMSAudioTrackSettings"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstracksettings\/audio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstracksettings\/audio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings\/audio","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings"},{"kind":"text","text":"?"}],"title":"audio","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSTrackSettings(py)audio","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"audio"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackSettings/audio":{"role":"symbol","title":"audio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings\/audio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audio"}],"url":"\/documentation\/hmssdk\/hmstracksettings\/audio"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackSettings":{"role":"symbol","title":"HMSTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackSettings"}],"url":"\/documentation\/hmssdk\/hmstracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings":{"role":"symbol","title":"HMSAudioTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audio"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings","text":"HMSAudioTrackSettings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"audio"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings~1audio\/title","value":"audio"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings~1audio\/fragments","value":[{"kind":"identifier","text":"audio"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings\/title","value":"HMSTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}