{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettings","text":"HMSVideoTrackSettings"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"audioSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings","text":"HMSAudioTrackSettings"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstracksettings\/init(videosettings:audiosettings:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstracksettings\/init(videosettings:audiosettings:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings\/init(videoSettings:audioSettings:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrackSettings","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettings"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"audioSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings"},{"kind":"text","text":"?)"}],"title":"init(videoSettings:audioSettings:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)HMSTrackSettings(im)initWithVideoSettings:audioSettings:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVideoSettings:audioSettings:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackSettings":{"role":"symbol","title":"HMSTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackSettings"}],"url":"\/documentation\/hmssdk\/hmstracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings":{"role":"symbol","title":"HMSVideoTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackSettings/init(videoSettings:audioSettings:)":{"role":"symbol","title":"init(videoSettings:audioSettings:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrackSettings","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettings"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"audioSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings\/init(videoSettings:audioSettings:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVideoSettings:audioSettings:"}],"url":"\/documentation\/hmssdk\/hmstracksettings\/init(videosettings:audiosettings:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings":{"role":"symbol","title":"HMSAudioTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVideoSettings:audioSettings:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVideoSettings:audioSettings:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVideoSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettings","text":"HMSVideoTrackSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoSettings"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings","text":"HMSAudioTrackSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"audioSettings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings\/title","value":"HMSTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings~1init(videoSettings:audioSettings:)\/title","value":"initWithVideoSettings:audioSettings:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings~1init(videoSettings:audioSettings:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVideoSettings:audioSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}