{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult","text":"HMSPluginSupportResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginsupportresult\/devicenotsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginsupportresult\/devicenotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/deviceNotSupported","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"title":"deviceNotSupported","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult(cpy)deviceNotSupported","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"deviceNotSupported"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult/deviceNotSupported":{"role":"symbol","title":"deviceNotSupported","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/deviceNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceNotSupported"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult\/devicenotsupported"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult":{"role":"symbol","title":"HMSPluginSupportResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResult"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"deviceNotSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deviceNotSupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult","text":"HMSPluginSupportResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"deviceNotSupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1deviceNotSupported\/title","value":"deviceNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1deviceNotSupported\/fragments","value":[{"kind":"identifier","text":"deviceNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/title","value":"HMSPluginSupportResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}