{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginSupportResultType","text":"HMSPluginSupportResultType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes","text":"HMSPluginUnsupportedErrorTypes"},{"kind":"text","text":" = .none, "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginsupportresult\/init(type:errortype:errormessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginsupportresult\/init(type:errortype:errormessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/init(type:errorType:errorMessage:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResultType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginSupportResultType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginUnsupportedErrorTypes","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(type:errorType:errorMessage:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult(im)initWithType:errorType:errorMessage:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithType:errorType:errorMessage:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult":{"role":"symbol","title":"HMSPluginSupportResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResult"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult/init(type:errorType:errorMessage:)":{"role":"symbol","title":"init(type:errorType:errorMessage:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResultType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginSupportResultType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginUnsupportedErrorTypes","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/init(type:errorType:errorMessage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithType:errorType:errorMessage:"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult\/init(type:errortype:errormessage:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType":{"role":"symbol","title":"HMSPluginSupportResultType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResultType"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResultType"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresulttype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithType:errorType:errorMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:errorType:errorMessage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginSupportResultType","text":"HMSPluginSupportResultType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes","text":"HMSPluginUnsupportedErrorTypes"},{"kind":"text","text":")"},{"kind":"internalParam","text":"errorType"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/title","value":"HMSPluginSupportResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResult"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/title","value":"HMSPluginUnsupportedErrorTypes"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1init(type:errorType:errorMessage:)\/title","value":"initWithType:errorType:errorMessage:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1init(type:errorType:errorMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:errorType:errorMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType\/title","value":"HMSPluginSupportResultType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResultType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}