{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnswerFailed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code\/createanswerfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code\/createanswerfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createAnswerFailed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Failed to establish audio\/video stream connection to 100ms server"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnswerFailed"}],"title":"HMSError.Code.createAnswerFailed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSError@HMSErrorCreateAnswerFailed","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code":{"role":"symbol","title":"HMSError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/createAnswerFailed":{"role":"symbol","title":"HMSError.Code.createAnswerFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnswerFailed"}],"abstract":[{"type":"text","text":"Failed to establish audio\/video stream connection to 100ms server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/createAnswerFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/createanswerfailed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct":{"role":"symbol","title":"HMSError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSError"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSErrorCreateAnswerFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/title","value":"HMSError"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"HMSError"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1createAnswerFailed\/title","value":"HMSErrorCreateAnswerFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1createAnswerFailed\/fragments","value":[{"kind":"identifier","text":"HMSErrorCreateAnswerFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}