{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performanceEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"stats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats","preciseIdentifier":"c:@S@HMSPerformanceStats","text":"HMSPerformanceStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent","text":"HMSAnalyticsEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticseventfactory\/performanceevent(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticseventfactory\/performanceevent(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/performanceEvent(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"performanceEvent:"}],"role":"symbol","title":"performanceEvent(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performanceEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPerformanceStats","preciseIdentifier":"c:@S@HMSPerformanceStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"symbolKind":"method","externalID":"c:objc(pl)HMSAnalyticsEventFactory(im)performanceEvent:","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent":{"role":"symbol","title":"HMSAnalyticsEvent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEvent"}],"url":"\/documentation\/hmssdk\/hmsanalyticsevent"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/performanceEvent(_:)":{"navigatorTitle":[{"kind":"identifier","text":"performanceEvent:"}],"role":"symbol","title":"performanceEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performanceEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPerformanceStats","preciseIdentifier":"c:@S@HMSPerformanceStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/performanceEvent(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/performanceevent(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory":{"role":"symbol","title":"HMSAnalyticsEventFactory","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventfactory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats":{"role":"symbol","title":"HMSPerformanceStats","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPerformanceStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPerformanceStats"}],"url":"\/documentation\/hmssdk\/hmsperformancestats"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"performanceEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performanceEvent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSObject<HMSAnalyticsEvent>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)HMSAnalyticsEvent"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"performanceEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats","preciseIdentifier":"c:@S@HMSPerformanceStats","text":"HMSPerformanceStats"},{"kind":"text","text":")"},{"kind":"internalParam","text":"stats"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/title","value":"HMSAnalyticsEvent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1performanceEvent(_:)\/title","value":"performanceEvent:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1performanceEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performanceEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory\/title","value":"HMSAnalyticsEventFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats\/title","value":"HMSPerformanceStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats\/fragments","value":[{"kind":"identifier","text":"HMSPerformanceStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}