{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticseventlevel\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticseventlevel\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel\/error","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"title":"HMSAnalyticsEventLevel.error","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSAnalyticsEventLevel@kHMSAnalyticsEventLevelError","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelError"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventLevel/error":{"role":"symbol","title":"HMSAnalyticsEventLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelError"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventlevel\/error"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventLevel":{"role":"symbol","title":"HMSAnalyticsEventLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventlevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSAnalyticsEventLevelError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel~1error\/title","value":"kHMSAnalyticsEventLevelError"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel~1error\/fragments","value":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/title","value":"HMSAnalyticsEventLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}