{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticseventlevel\/verbose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticseventlevel\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel\/verbose","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"title":"HMSAnalyticsEventLevel.verbose","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSAnalyticsEventLevel@kHMSAnalyticsEventLevelVerbose","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelVerbose"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventLevel/verbose":{"role":"symbol","title":"HMSAnalyticsEventLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelVerbose"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventlevel\/verbose"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventLevel":{"role":"symbol","title":"HMSAnalyticsEventLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventlevel"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSAnalyticsEventLevelVerbose"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelVerbose"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelVerbose"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel~1verbose\/title","value":"kHMSAnalyticsEventLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"kHMSAnalyticsEventLevelVerbose"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/title","value":"HMSAnalyticsEventLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}