{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsspeaker\/init(peer:track:level:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsspeaker\/init(peer:track:level:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSpeaker\/init(peer:track:level:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(peer:track:level:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@HMSSDK@objc(cs)HMSSpeaker(im)initWithPeer:track:level:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPeer:track:level:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSpeaker"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSpeaker/init(peer:track:level:)":{"role":"symbol","title":"init(peer:track:level:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSpeaker\/init(peer:track:level:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPeer:track:level:"}],"url":"\/documentation\/hmssdk\/hmsspeaker\/init(peer:track:level:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack":{"role":"symbol","title":"HMSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrack"}],"abstract":[{"type":"text","text":"A track represents either the audio or video that makes up a stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrack"}],"url":"\/documentation\/hmssdk\/hmstrack"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSpeaker":{"role":"symbol","title":"HMSSpeaker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSpeaker"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSpeaker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSpeaker"}],"url":"\/documentation\/hmssdk\/hmsspeaker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPeer:track:level:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPeer:track:level:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPeer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peer"},{"kind":"text","text":" "},{"kind":"identifier","text":"track:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack","text":"HMSTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"track"},{"kind":"text","text":" "},{"kind":"identifier","text":"level:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"level"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSpeaker~1init(peer:track:level:)\/title","value":"initWithPeer:track:level:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSpeaker~1init(peer:track:level:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPeer:track:level:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/title","value":"HMSTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/fragments","value":[{"kind":"identifier","text":"HMSTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSpeaker\/title","value":"HMSSpeaker"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSpeaker\/fragments","value":[{"kind":"identifier","text":"HMSSpeaker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}