{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin","text":"HMSVideoPlugin"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/videoplugins"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/videoplugins"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/videoPlugins","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?"}],"title":"videoPlugins","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSVideoTrackSettingsBuilder(py)videoPlugins","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"videoPlugins"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/videoPlugins":{"role":"symbol","title":"videoPlugins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/videoPlugins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoPlugins"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/videoplugins"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder":{"role":"symbol","title":"HMSVideoTrackSettingsBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoPlugin":{"role":"symbol","title":"HMSVideoPlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoPlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoPlugin"}],"url":"\/documentation\/hmssdk\/hmsvideoplugin"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoPlugins"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoPlugins"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSVideoPlugin *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"videoPlugins"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1videoPlugins\/title","value":"videoPlugins"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1videoPlugins\/fragments","value":[{"kind":"identifier","text":"videoPlugins"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder\/title","value":"HMSVideoTrackSettingsBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/title","value":"HMSVideoPlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/fragments","value":[{"kind":"identifier","text":"HMSVideoPlugin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}