{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioNode","text":"HMSAudioNode"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiomixersource\/init(nodes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiomixersource\/init(nodes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource\/init(nodes:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithNodes:error:"}],"role":"symbol","title":"init(nodes:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioNode"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"symbolKind":"init","externalID":"c:@M@HMSSDK@objc(cs)HMSAudioMixerSource(im)initWithNodes:error:","modules":[{"name":"HMSSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioMixerSource":{"role":"symbol","title":"HMSAudioMixerSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioMixerSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioMixerSource"}],"url":"\/documentation\/hmssdk\/hmsaudiomixersource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioMixerSource/init(nodes:)":{"role":"symbol","title":"init(nodes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioNode"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource\/init(nodes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNodes:error:"}],"url":"\/documentation\/hmssdk\/hmsaudiomixersource\/init(nodes:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioNode":{"role":"symbol","title":"HMSAudioNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioNode"}],"url":"\/documentation\/hmssdk\/hmsaudionode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithNodes:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNodes:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNodes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<HMSAudioNode *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nodes"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioMixerSource\/title","value":"HMSAudioMixerSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioMixerSource\/fragments","value":[{"kind":"identifier","text":"HMSAudioMixerSource"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioMixerSource~1init(nodes:)\/title","value":"initWithNodes:error:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioMixerSource~1init(nodes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNodes:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioNode\/title","value":"HMSAudioNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioNode\/fragments","value":[{"kind":"identifier","text":"HMSAudioNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}