{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builderBlock"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettingsBuilder","text":"HMSVideoTrackSettingsBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettings","text":"HMSVideoTrackSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/build(builderblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/build(builderblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/build(builderBlock:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builderBlock"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"HMSVideoTrackSettingsBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettingsBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSVideoTrackSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettings"}],"title":"build(builderBlock:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettings(cm)buildWithBuilderBlock:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"buildWithBuilderBlock:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings":{"role":"symbol","title":"HMSVideoTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/build(builderBlock:)":{"role":"symbol","title":"build(builderBlock:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builderBlock"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"HMSVideoTrackSettingsBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettingsBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSVideoTrackSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/build(builderBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildWithBuilderBlock:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/build(builderblock:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder":{"role":"symbol","title":"HMSVideoTrackSettingsBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"buildWithBuilderBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildWithBuilderBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrackSettings","text":"HMSVideoTrackSettings"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildWithBuilderBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(HMSVideoTrackSettingsBuilder *)","preciseIdentifier":"c:BFv(#*$@M@HMSSDK@objc(cs)HMSVideoTrackSettingsBuilder)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"builderBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1build(builderBlock:)\/title","value":"buildWithBuilderBlock:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1build(builderBlock:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildWithBuilderBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder\/title","value":"HMSVideoTrackSettingsBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}