{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCodec","preciseIdentifier":"c:@E@HMSCodec","text":"HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution","text":"HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin","text":"HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:trackdescription:videoplugins:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:trackdescription:videoplugins:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)HMSVideoTrackSettings(im)initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoResolution":{"role":"symbol","title":"HMSVideoResolution","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoResolution"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoResolution"}],"url":"\/documentation\/hmssdk\/hmsvideoresolution"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings":{"role":"symbol","title":"HMSVideoTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFacing":{"role":"symbol","title":"HMSCameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCameraFacing"}],"url":"\/documentation\/hmssdk\/hmscamerafacing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)":{"role":"symbol","title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:trackdescription:videoplugins:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoPlugin":{"role":"symbol","title":"HMSVideoPlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoPlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoPlugin"}],"url":"\/documentation\/hmssdk\/hmsvideoplugin"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCodec":{"role":"symbol","title":"HMSCodec","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCodec"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCodec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCodec"}],"url":"\/documentation\/hmssdk\/hmscodec"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCodec:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCodec","preciseIdentifier":"c:@E@HMSCodec","text":"HMSCodec"},{"kind":"text","text":") "},{"kind":"internalParam","text":"codec"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"resolution"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBitrate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxBitrate"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFrameRate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxFrameRate"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescription:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackDescription"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlugins:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<HMSVideoPlugin *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoPlugins"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/title","value":"HMSVideoPlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/fragments","value":[{"kind":"identifier","text":"HMSVideoPlugin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}