{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings","text":"HMSSimulcastLayerSettings"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/simulcastsettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/simulcastsettings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/simulcastSettings","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?"}],"title":"simulcastSettings","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSVideoTrackSettings(py)simulcastSettings","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"simulcastSettings"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings":{"role":"symbol","title":"HMSVideoTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings":{"role":"symbol","title":"HMSSimulcastLayerSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/simulcastSettings":{"role":"symbol","title":"simulcastSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/simulcastSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"simulcastSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/simulcastsettings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"simulcastSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"simulcastSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSSimulcastLayerSettings *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"simulcastSettings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings\/title","value":"HMSSimulcastLayerSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1simulcastSettings\/title","value":"simulcastSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1simulcastSettings\/fragments","value":[{"kind":"identifier","text":"simulcastSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}