{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings","text":"HMSAudioTrackSettings"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalaudiotrack\/settings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalaudiotrack\/settings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack\/settings","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings"}],"title":"settings","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSLocalAudioTrack(py)settings","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"settings"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalAudioTrack/settings":{"role":"symbol","title":"settings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack\/settings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"settings"}],"url":"\/documentation\/hmssdk\/hmslocalaudiotrack\/settings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings":{"role":"symbol","title":"HMSAudioTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalAudioTrack":{"role":"symbol","title":"HMSLocalAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalAudioTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalAudioTrack"}],"url":"\/documentation\/hmssdk\/hmslocalaudiotrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"settings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"settings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettings","text":"HMSAudioTrackSettings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"settings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioTrack~1settings\/title","value":"settings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioTrack~1settings\/fragments","value":[{"kind":"identifier","text":"settings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioTrack\/title","value":"HMSLocalAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalAudioTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}