{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastlayer\/mid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastlayer\/mid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/mid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"}],"title":"HMSSimulcastLayer.mid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSSimulcastLayer@kHMSSimulcastLayerMid","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer":{"role":"symbol","title":"HMSSimulcastLayer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayer"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/mid":{"role":"symbol","title":"HMSSimulcastLayer.mid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/mid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer\/mid"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSSimulcastLayerMid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer\/title","value":"HMSSimulcastLayer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1mid\/title","value":"kHMSSimulcastLayerMid"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1mid\/fragments","value":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}