{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel","text":"HMSAnalyticsEventLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticsevent\/level()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticsevent\/level()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/level()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"level"}],"role":"symbol","title":"level()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"symbolKind":"method","externalID":"c:objc(pl)HMSAnalyticsEvent(im)level","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventLevel":{"role":"symbol","title":"HMSAnalyticsEventLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventlevel"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/level()":{"navigatorTitle":[{"kind":"identifier","text":"level"}],"role":"symbol","title":"level()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/level()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/level()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent":{"role":"symbol","title":"HMSAnalyticsEvent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEvent"}],"url":"\/documentation\/hmssdk\/hmsanalyticsevent"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"level"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"level"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel","text":"HMSAnalyticsEventLevel"},{"kind":"text","text":") "},{"kind":"identifier","text":"level"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/title","value":"HMSAnalyticsEventLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1level()\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1level()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/title","value":"HMSAnalyticsEvent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}