{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCI420Buffer","preciseIdentifier":"c:objc(cs)RTCI420Buffer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmswebrtcutilities\/image(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmswebrtcutilities\/image(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSWebRTCUtilities\/image(from:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCI420Buffer","preciseIdentifier":"c:objc(cs)RTCI420Buffer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"image(from:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSWebRTCUtilities(cm)imageFromRTCI420Buffer:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"imageFromRTCI420Buffer:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSWebRTCUtilities"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSWebRTCUtilities/image(from:)":{"role":"symbol","title":"image(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCI420Buffer","preciseIdentifier":"c:objc(cs)RTCI420Buffer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSWebRTCUtilities\/image(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageFromRTCI420Buffer:"}],"url":"\/documentation\/hmssdk\/hmswebrtcutilities\/image(from:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSWebRTCUtilities":{"role":"symbol","title":"HMSWebRTCUtilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSWebRTCUtilities"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSWebRTCUtilities","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSWebRTCUtilities"}],"url":"\/documentation\/hmssdk\/hmswebrtcutilities"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"imageFromRTCI420Buffer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageFromRTCI420Buffer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageFromRTCI420Buffer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCI420Buffer","preciseIdentifier":"c:objc(cs)RTCI420Buffer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSWebRTCUtilities~1image(from:)\/title","value":"imageFromRTCI420Buffer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSWebRTCUtilities~1image(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageFromRTCI420Buffer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSWebRTCUtilities\/title","value":"HMSWebRTCUtilities"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSWebRTCUtilities\/fragments","value":[{"kind":"identifier","text":"HMSWebRTCUtilities"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}