{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browserRecordingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSBrowserRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSBrowserRecordingState","text":"HMSBrowserRecordingState"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsroom\/browserrecordingstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsroom\/browserrecordingstate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/browserRecordingState","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browserRecordingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSBrowserRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSBrowserRecordingState"}],"title":"browserRecordingState","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSRoom(py)browserRecordingState","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"browserRecordingState"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSBrowserRecordingState":{"role":"symbol","title":"HMSBrowserRecordingState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSBrowserRecordingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSBrowserRecordingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSBrowserRecordingState"}],"url":"\/documentation\/hmssdk\/hmsbrowserrecordingstate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom":{"role":"symbol","title":"HMSRoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}],"url":"\/documentation\/hmssdk\/hmsroom"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/browserRecordingState":{"role":"symbol","title":"browserRecordingState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browserRecordingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSBrowserRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSBrowserRecordingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/browserRecordingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"browserRecordingState"}],"url":"\/documentation\/hmssdk\/hmsroom\/browserrecordingstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"browserRecordingState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"browserRecordingState"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSBrowserRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSBrowserRecordingState","text":"HMSBrowserRecordingState"},{"kind":"text","text":" * "},{"kind":"identifier","text":"browserRecordingState"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSBrowserRecordingState\/title","value":"HMSBrowserRecordingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSBrowserRecordingState\/fragments","value":[{"kind":"identifier","text":"HMSBrowserRecordingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/title","value":"HMSRoom"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1browserRecordingState\/title","value":"browserRecordingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1browserRecordingState\/fragments","value":[{"kind":"identifier","text":"browserRecordingState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}