{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"capture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsframecaptureplugin\/capture()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsframecaptureplugin\/capture()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/capture()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"capture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"capture()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSFrameCapturePlugin(im)capture","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"capture"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSFrameCapturePlugin":{"role":"symbol","title":"HMSFrameCapturePlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSFrameCapturePlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}],"url":"\/documentation\/hmssdk\/hmsframecaptureplugin"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSFrameCapturePlugin/capture()":{"role":"symbol","title":"capture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"capture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/capture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"capture"}],"url":"\/documentation\/hmssdk\/hmsframecaptureplugin\/capture()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"capture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"capture"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"capture"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin\/title","value":"HMSFrameCapturePlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin\/fragments","value":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin~1capture()\/title","value":"capture"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin~1capture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"capture"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}