{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withWeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","text":"HMSPollQuestionBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"weight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The weight of the question."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated question builder instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestionbuilder\/withweight(weight:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestionbuilder\/withweight(weight:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withWeight(weight:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the weight of the question for score calculation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withWeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"title":"withWeight(weight:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder(im)withWeightWithWeight:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"withWeightWithWeight:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder":{"role":"symbol","title":"HMSPollQuestionBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withWeight(weight:)":{"role":"symbol","title":"withWeight(weight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withWeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the weight of the question for score calculation."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withWeight(weight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withWeightWithWeight:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withweight(weight:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"withWeightWithWeight:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withWeightWithWeight:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","text":"HMSPollQuestionBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"withWeightWithWeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"weight"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/title","value":"HMSPollQuestionBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withWeight(weight:)\/title","value":"withWeightWithWeight:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withWeight(weight:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withWeightWithWeight:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}