{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack","text":"HMSVideoTrack"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideoview\/setvideotrack(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideoview\/setvideotrack(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/setVideoTrack(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":"?)"}],"title":"setVideoTrack(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSVideoView(im)setVideoTrack:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setVideoTrack:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/setVideoTrack(_:)":{"role":"symbol","title":"setVideoTrack(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/setVideoTrack(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoTrack:"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/setvideotrack(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack":{"role":"symbol","title":"HMSVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsvideotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView":{"role":"symbol","title":"HMSVideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoView"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoView"}],"url":"\/documentation\/hmssdk\/hmsvideoview"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVideoTrack:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoTrack:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVideoTrack:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack","text":"HMSVideoTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"track"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1setVideoTrack(_:)\/title","value":"setVideoTrack:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1setVideoTrack(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoTrack:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/title","value":"HMSVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView\/title","value":"HMSVideoView"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView\/fragments","value":[{"kind":"identifier","text":"HMSVideoView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}