{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoSettings","text":"HMSVideoSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspublishsettings\/video"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspublishsettings\/video"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPublishSettings\/video","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoSettings"}],"title":"video","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPublishSettings(py)video","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"video"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPublishSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPublishSettings":{"role":"symbol","title":"HMSPublishSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPublishSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPublishSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPublishSettings"}],"url":"\/documentation\/hmssdk\/hmspublishsettings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoSettings":{"role":"symbol","title":"HMSVideoSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoSettings"}],"url":"\/documentation\/hmssdk\/hmsvideosettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPublishSettings/video":{"role":"symbol","title":"video","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPublishSettings\/video","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"video"}],"url":"\/documentation\/hmssdk\/hmspublishsettings\/video"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"video"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"video"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoSettings","text":"HMSVideoSettings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"video"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPublishSettings\/title","value":"HMSPublishSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPublishSettings\/fragments","value":[{"kind":"identifier","text":"HMSPublishSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoSettings\/title","value":"HMSVideoSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPublishSettings~1video\/title","value":"video"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPublishSettings~1video\/fragments","value":[{"kind":"identifier","text":"video"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}