{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant","text":"HMSHLSMeetingURLVariant"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"recording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig","text":"HMSHLSRecordingConfig"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsconfig\/init(variants:recording:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsconfig\/init(variants:recording:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig\/init(variants:recording:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSHLSMeetingURLVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig"},{"kind":"text","text":"?)"}],"title":"init(variants:recording:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@HMSSDK@objc(cs)HMSHLSConfig(im)initWithVariants:recording:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVariants:recording:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSMeetingURLVariant":{"role":"symbol","title":"HMSHLSMeetingURLVariant","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}],"url":"\/documentation\/hmssdk\/hmshlsmeetingurlvariant"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSConfig":{"role":"symbol","title":"HMSHLSConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSConfig"}],"url":"\/documentation\/hmssdk\/hmshlsconfig"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSConfig/init(variants:recording:)":{"role":"symbol","title":"init(variants:recording:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSHLSMeetingURLVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"recording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig\/init(variants:recording:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVariants:recording:"}],"url":"\/documentation\/hmssdk\/hmshlsconfig\/init(variants:recording:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSRecordingConfig":{"role":"symbol","title":"HMSHLSRecordingConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSRecordingConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSRecordingConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSRecordingConfig"}],"url":"\/documentation\/hmssdk\/hmshlsrecordingconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVariants:recording:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVariants:recording:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVariants:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<HMSHLSMeetingURLVariant *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"variants"},{"kind":"text","text":" "},{"kind":"identifier","text":"recording:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSRecordingConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingConfig","text":"HMSHLSRecordingConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recording"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant\/title","value":"HMSHLSMeetingURLVariant"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant\/fragments","value":[{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig\/title","value":"HMSHLSConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig\/fragments","value":[{"kind":"identifier","text":"HMSHLSConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig~1init(variants:recording:)\/title","value":"initWithVariants:recording:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig~1init(variants:recording:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVariants:recording:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSRecordingConfig\/title","value":"HMSHLSRecordingConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSRecordingConfig\/fragments","value":[{"kind":"identifier","text":"HMSHLSRecordingConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}