{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant","text":"HMSHLSMeetingURLVariant"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsconfig\/variants"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsconfig\/variants"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig\/variants","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Meeting url variants that would be used as sources of HLS streams"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSHLSMeetingURLVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant"},{"kind":"text","text":"]?"}],"title":"variants","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSHLSConfig(py)variants","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"variants"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSConfig/variants":{"role":"symbol","title":"variants","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSHLSMeetingURLVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Meeting url variants that would be used as sources of HLS streams"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig\/variants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"variants"}],"url":"\/documentation\/hmssdk\/hmshlsconfig\/variants"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSMeetingURLVariant":{"role":"symbol","title":"HMSHLSMeetingURLVariant","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}],"url":"\/documentation\/hmssdk\/hmshlsmeetingurlvariant"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSConfig":{"role":"symbol","title":"HMSHLSConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSConfig"}],"url":"\/documentation\/hmssdk\/hmshlsconfig"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"variants"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"variants"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSHLSMeetingURLVariant *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"variants"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig~1variants\/title","value":"variants"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig~1variants\/fragments","value":[{"kind":"identifier","text":"variants"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant\/title","value":"HMSHLSMeetingURLVariant"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant\/fragments","value":[{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig\/title","value":"HMSHLSConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSConfig\/fragments","value":[{"kind":"identifier","text":"HMSHLSConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}