{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"layers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastLayerSettingsPolicy","text":"HMSSimulcastLayerSettingsPolicy"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastsettingspolicy\/layers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastsettingspolicy\/layers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy\/layers","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"layers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastLayerSettingsPolicy"},{"kind":"text","text":"]?"}],"title":"layers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSSimulcastSettingsPolicy(py)layers","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"layers"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastSettingsPolicy":{"role":"symbol","title":"HMSSimulcastSettingsPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastSettingsPolicy"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastSettingsPolicy"}],"url":"\/documentation\/hmssdk\/hmssimulcastsettingspolicy"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettingsPolicy":{"role":"symbol","title":"HMSSimulcastLayerSettingsPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerSettingsPolicy"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettingsPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerSettingsPolicy"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettingspolicy"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastSettingsPolicy/layers":{"role":"symbol","title":"layers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"layers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastLayerSettingsPolicy"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy\/layers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layers"}],"url":"\/documentation\/hmssdk\/hmssimulcastsettingspolicy\/layers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"layers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"layers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSSimulcastLayerSettingsPolicy *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"layers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettingsPolicy\/title","value":"HMSSimulcastSettingsPolicy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettingsPolicy\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastSettingsPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettingsPolicy\/title","value":"HMSSimulcastLayerSettingsPolicy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettingsPolicy\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerSettingsPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettingsPolicy~1layers\/title","value":"layers"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettingsPolicy~1layers\/fragments","value":[{"kind":"identifier","text":"layers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}