{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsRecordingStateUpdated"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsroomupdate\/hlsrecordingstateupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsroomupdate\/hlsrecordingstateupdated"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsRecordingStateUpdated","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsRecordingStateUpdated"}],"title":"HMSRoomUpdate.hlsRecordingStateUpdated","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSRoomUpdate@HMSRoomUpdateHlsRecordingStateUpdated","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate":{"role":"symbol","title":"HMSRoomUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdate"}],"url":"\/documentation\/hmssdk\/hmsroomupdate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/hlsRecordingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.hlsRecordingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsRecordingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsRecordingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/hlsrecordingstateupdated"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSRoomUpdateHlsRecordingStateUpdated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/title","value":"HMSRoomUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1hlsRecordingStateUpdated\/title","value":"HMSRoomUpdateHlsRecordingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1hlsRecordingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}