{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomTypeChanged"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsroomupdate\/roomtypechanged"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsroomupdate\/roomtypechanged"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/roomTypeChanged","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomTypeChanged"}],"title":"HMSRoomUpdate.roomTypeChanged","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSRoomUpdate@HMSRoomUpdateRoomTypeChanged","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/roomTypeChanged":{"role":"symbol","title":"HMSRoomUpdate.roomTypeChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomTypeChanged"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/roomTypeChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/roomtypechanged"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate":{"role":"symbol","title":"HMSRoomUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdate"}],"url":"\/documentation\/hmssdk\/hmsroomupdate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSRoomUpdateRoomTypeChanged"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1roomTypeChanged\/title","value":"HMSRoomUpdateRoomTypeChanged"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1roomTypeChanged\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/title","value":"HMSRoomUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}