{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmpStreamingStateUpdated"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsroomupdate\/rtmpstreamingstateupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsroomupdate\/rtmpstreamingstateupdated"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/rtmpStreamingStateUpdated","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmpStreamingStateUpdated"}],"title":"HMSRoomUpdate.rtmpStreamingStateUpdated","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSRoomUpdate@HMSRoomUpdateRtmpStreamingStateUpdated","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate":{"role":"symbol","title":"HMSRoomUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdate"}],"url":"\/documentation\/hmssdk\/hmsroomupdate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/rtmpStreamingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.rtmpStreamingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmpStreamingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/rtmpStreamingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/rtmpstreamingstateupdated"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSRoomUpdateRtmpStreamingStateUpdated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/title","value":"HMSRoomUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1rtmpStreamingStateUpdated\/title","value":"HMSRoomUpdateRtmpStreamingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1rtmpStreamingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}