{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataUpdated"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspeerupdate\/metadataupdated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspeerupdate\/metadataupdated"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/metadataUpdated","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataUpdated"}],"title":"HMSPeerUpdate.metadataUpdated","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPeerUpdate@HMSPeerUpdateMetadataUpdated","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate":{"role":"symbol","title":"HMSPeerUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdate"}],"url":"\/documentation\/hmssdk\/hmspeerupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/metadataUpdated":{"role":"symbol","title":"HMSPeerUpdate.metadataUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/metadataUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/metadataupdated"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPeerUpdateMetadataUpdated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/title","value":"HMSPeerUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1metadataUpdated\/title","value":"HMSPeerUpdateMetadataUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1metadataUpdated\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}