{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmscommandpriority\/low"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmscommandpriority\/low"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority\/low","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"title":"HMSCommandPriority.low","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSCommandPriority@HMSCommandPriorityLow","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSCommandPriorityLow"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCommandPriority/low":{"role":"symbol","title":"HMSCommandPriority.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCommandPriorityLow"}],"url":"\/documentation\/hmssdk\/hmscommandpriority\/low"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCommandPriority":{"role":"symbol","title":"HMSCommandPriority","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCommandPriority"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCommandPriority"}],"url":"\/documentation\/hmssdk\/hmscommandpriority"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSCommandPriorityLow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSCommandPriorityLow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSCommandPriorityLow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCommandPriority~1low\/title","value":"HMSCommandPriorityLow"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCommandPriority~1low\/fragments","value":[{"kind":"identifier","text":"HMSCommandPriorityLow"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCommandPriority\/title","value":"HMSCommandPriority"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCommandPriority\/fragments","value":[{"kind":"identifier","text":"HMSCommandPriority"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}