{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rolesThatCanViewResponses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole","text":"HMSRole"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspoll\/rolesthatcanviewresponses"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspoll\/rolesthatcanviewresponses"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanViewResponses","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The roles that can view the poll responses."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rolesThatCanViewResponses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]"}],"title":"rolesThatCanViewResponses","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPoll(py)rolesThatCanViewResponses","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"rolesThatCanViewResponses"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/rolesThatCanViewResponses":{"role":"symbol","title":"rolesThatCanViewResponses","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rolesThatCanViewResponses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The roles that can view the poll responses."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanViewResponses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rolesThatCanViewResponses"}],"url":"\/documentation\/hmssdk\/hmspoll\/rolesthatcanviewresponses"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll":{"role":"symbol","title":"HMSPoll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"abstract":[{"type":"text","text":"Represents a poll object."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}],"url":"\/documentation\/hmssdk\/hmspoll"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRole":{"role":"symbol","title":"HMSRole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRole"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRole"}],"url":"\/documentation\/hmssdk\/hmsrole"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rolesThatCanViewResponses"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rolesThatCanViewResponses"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSRole *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rolesThatCanViewResponses"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1rolesThatCanViewResponses\/title","value":"rolesThatCanViewResponses"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1rolesThatCanViewResponses\/fragments","value":[{"kind":"identifier","text":"rolesThatCanViewResponses"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/title","value":"HMSPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRole\/title","value":"HMSRole"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRole\/fragments","value":[{"kind":"identifier","text":"HMSRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}