{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideoconnectionstate\/connecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideoconnectionstate\/connecting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connecting","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"title":"HMSVideoConnectionState.connecting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSVideoConnectionState@kHMSVideoConnectionStateConnecting","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState":{"role":"symbol","title":"HMSVideoConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoConnectionState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoConnectionState"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/connecting":{"role":"symbol","title":"HMSVideoConnectionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/connecting"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSVideoConnectionStateConnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState\/title","value":"HMSVideoConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState\/fragments","value":[{"kind":"identifier","text":"HMSVideoConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1connecting\/title","value":"kHMSVideoConnectionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1connecting\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}