{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointUnreachable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code\/endpointunreachable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code\/endpointunreachable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/endpointUnreachable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Endpoint is not responding"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointUnreachable"}],"title":"HMSError.Code.endpointUnreachable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSError@HMSErrorEndpointUnreachable","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct":{"role":"symbol","title":"HMSError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSError"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code":{"role":"symbol","title":"HMSError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/endpointUnreachable":{"role":"symbol","title":"HMSError.Code.endpointUnreachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointUnreachable"}],"abstract":[{"type":"text","text":"Endpoint is not responding"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/endpointUnreachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/endpointunreachable"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSErrorEndpointUnreachable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/title","value":"HMSError"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"HMSError"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1endpointUnreachable\/title","value":"HMSErrorEndpointUnreachable"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1endpointUnreachable\/fragments","value":[{"kind":"identifier","text":"HMSErrorEndpointUnreachable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}