{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code\/generictrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmserror-swift.struct\/code\/generictrack"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/genericTrack","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unknown error during track creation. Check error message for more info."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericTrack"}],"title":"HMSError.Code.genericTrack","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSError@HMSErrorGenericTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSErrorGenericTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code/genericTrack":{"role":"symbol","title":"HMSError.Code.genericTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericTrack"}],"abstract":[{"type":"text","text":"Unknown error during track creation. Check error message for more info."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code\/genericTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorGenericTrack"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code\/generictrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct/Code":{"role":"symbol","title":"HMSError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct\/code"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSError-swift.struct":{"role":"symbol","title":"HMSError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSError"}],"url":"\/documentation\/hmssdk\/hmserror-swift.struct"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSErrorGenericTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSErrorGenericTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSErrorGenericTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1genericTrack\/title","value":"HMSErrorGenericTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code~1genericTrack\/fragments","value":[{"kind":"identifier","text":"HMSErrorGenericTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/title","value":"HMSError"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"HMSError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}