{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"question"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC","text":"HMSPollQuestion"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionOption","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionOption","text":"HMSPollQuestionOption"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"question","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The question to add the result for."}]}]},{"name":"choice","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The choice that the user voted for."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollresponsebuilder\/addresponse(for:options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder\/addResponse(for:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a result for a single or multi-choice question."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestionOption","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionOption"},{"kind":"text","text":"])"}],"title":"addResponse(for:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6HMSSDK22HMSPollResponseBuilderC03addC03for7optionsyAA0B8QuestionC_SayAA0bH6OptionCGtF","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionOption":{"role":"symbol","title":"HMSPollQuestionOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionOption"}],"abstract":[{"type":"text","text":"Represents an option for a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionOption"}],"url":"\/documentation\/hmssdk\/hmspollquestionoption"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestion":{"role":"symbol","title":"HMSPollQuestion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestion"}],"abstract":[{"type":"text","text":"Represents a question in a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestion"}],"url":"\/documentation\/hmssdk\/hmspollquestion"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollResponseBuilder":{"role":"symbol","title":"HMSPollResponseBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollResponseBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollResponseBuilder"}],"url":"\/documentation\/hmssdk\/hmspollresponsebuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollResponseBuilder/addResponse(for:options:)":{"role":"symbol","title":"addResponse(for:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestionOption","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionOption"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Adds a result for a single or multi-choice question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder\/addResponse(for:options:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollresponsebuilder\/addresponse(for:options:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionOption\/title","value":"HMSPollQuestionOption"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionOption\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionOption"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResponseBuilder\/title","value":"HMSPollResponseBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResponseBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollResponseBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}