{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pub"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsconnectionrole\/pub"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsconnectionrole\/pub"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole\/pub","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pub"}],"title":"HMSConnectionRole.pub","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSConnectionRole@kHMSConnectionRolePub","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSConnectionRolePub"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSConnectionRole":{"role":"symbol","title":"HMSConnectionRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSConnectionRole"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSConnectionRole"}],"url":"\/documentation\/hmssdk\/hmsconnectionrole"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConnectionRole/pub":{"role":"symbol","title":"HMSConnectionRole.pub","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pub"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole\/pub","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSConnectionRolePub"}],"url":"\/documentation\/hmssdk\/hmsconnectionrole\/pub"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSConnectionRolePub"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSConnectionRolePub"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSConnectionRolePub"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole\/title","value":"HMSConnectionRole"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole\/fragments","value":[{"kind":"identifier","text":"HMSConnectionRole"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole~1pub\/title","value":"kHMSConnectionRolePub"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole~1pub\/fragments","value":[{"kind":"identifier","text":"kHMSConnectionRolePub"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}