{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sub"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsconnectionrole\/sub"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsconnectionrole\/sub"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole\/sub","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sub"}],"title":"HMSConnectionRole.sub","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSConnectionRole@kHMSConnectionRoleSub","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSConnectionRoleSub"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConnectionRole/sub":{"role":"symbol","title":"HMSConnectionRole.sub","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sub"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole\/sub","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSConnectionRoleSub"}],"url":"\/documentation\/hmssdk\/hmsconnectionrole\/sub"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConnectionRole":{"role":"symbol","title":"HMSConnectionRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSConnectionRole"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConnectionRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSConnectionRole"}],"url":"\/documentation\/hmssdk\/hmsconnectionrole"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSConnectionRoleSub"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSConnectionRoleSub"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSConnectionRoleSub"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole~1sub\/title","value":"kHMSConnectionRoleSub"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole~1sub\/fragments","value":[{"kind":"identifier","text":"kHMSConnectionRoleSub"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole\/title","value":"HMSConnectionRole"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConnectionRole\/fragments","value":[{"kind":"identifier","text":"HMSConnectionRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}