{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/trackDescription"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}],"title":"HMSAudioTrackSettingsBuilder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSAudioTrackSettingsBuilder","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder/audioMode":{"role":"symbol","title":"audioMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioMode"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/audiomode"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/init()"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder/initialMuteState":{"role":"symbol","title":"initialMuteState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/initialMuteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialMuteState"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/initialmutestate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder/trackDescription":{"role":"symbol","title":"trackDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/trackDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackDescription"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/trackdescription"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder":{"role":"symbol","title":"HMSAudioTrackSettingsBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder/audioSource":{"role":"symbol","title":"audioSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSource"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/audiosource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSAudioTrackSettingsBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/trackDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1audioMode\/title","value":"audioMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1audioMode\/fragments","value":[{"kind":"identifier","text":"audioMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1initialMuteState\/title","value":"initialMuteState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1initialMuteState\/fragments","value":[{"kind":"identifier","text":"initialMuteState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1trackDescription\/title","value":"trackDescription"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1trackDescription\/fragments","value":[{"kind":"identifier","text":"trackDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder\/title","value":"HMSAudioTrackSettingsBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1audioSource\/title","value":"audioSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1audioSource\/fragments","value":[{"kind":"identifier","text":"audioSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}