{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalvideostats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalvideostats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/frameRate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/qualityLimitations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/resolution","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/simulcastLayerId"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoStats"}],"title":"HMSLocalVideoStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSLocalVideoStats","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoStats"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoStats/qualityLimitations":{"role":"symbol","title":"qualityLimitations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityLimitations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSQualityLimitationReasons","preciseIdentifier":"c:objc(cs)HMSQualityLimitationReasons"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/qualityLimitations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityLimitations"}],"url":"\/documentation\/hmssdk\/hmslocalvideostats\/qualitylimitations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats":{"role":"symbol","title":"HMSSenderStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSenderStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSenderStats"}],"url":"\/documentation\/hmssdk\/hmssenderstats"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoStats/frameRate":{"role":"symbol","title":"frameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/frameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameRate"}],"url":"\/documentation\/hmssdk\/hmslocalvideostats\/framerate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoStats":{"role":"symbol","title":"HMSLocalVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoStats"}],"url":"\/documentation\/hmssdk\/hmslocalvideostats"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoStats/resolution":{"role":"symbol","title":"resolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/resolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resolution"}],"url":"\/documentation\/hmssdk\/hmslocalvideostats\/resolution"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoStats/simulcastLayerId":{"role":"symbol","title":"simulcastLayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulcastLayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/simulcastLayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"simulcastLayerId"}],"url":"\/documentation\/hmssdk\/hmslocalvideostats\/simulcastlayerid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSLocalVideoStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSLocalVideoStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/frameRate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/qualityLimitations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/resolution","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats\/simulcastLayerId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":[],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats","preciseIdentifier":"c:objc(cs)HMSSenderStats","text":"HMSSenderStats"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1qualityLimitations\/title","value":"qualityLimitations"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1qualityLimitations\/fragments","value":[{"kind":"identifier","text":"qualityLimitations"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1frameRate\/title","value":"frameRate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1frameRate\/fragments","value":[{"kind":"identifier","text":"frameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats\/title","value":"HMSLocalVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1resolution\/title","value":"resolution"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1resolution\/fragments","value":[{"kind":"identifier","text":"resolution"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1simulcastLayerId\/title","value":"simulcastLayerId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats~1simulcastLayerId\/fragments","value":[{"kind":"identifier","text":"simulcastLayerId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}