{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:peerRecipient:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:rolesRecipient:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/message","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/messageID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/recipient","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/sender","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/time","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/type"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessage"}],"title":"HMSMessage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSMessage","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSMessage"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/time":{"role":"symbol","title":"time","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/time","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"time"}],"url":"\/documentation\/hmssdk\/hmsmessage\/time"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage":{"role":"symbol","title":"HMSMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessage"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessage"}],"url":"\/documentation\/hmssdk\/hmsmessage"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/hmssdk\/hmsmessage\/sender"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/recipient":{"role":"symbol","title":"recipient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSMessageRecipient","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessageRecipient"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/recipient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recipient"}],"url":"\/documentation\/hmssdk\/hmsmessage\/recipient"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/hmssdk\/hmsmessage\/message"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/hmssdk\/hmsmessage\/type"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/messageID":{"role":"symbol","title":"messageID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/messageID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageID"}],"url":"\/documentation\/hmssdk\/hmsmessage\/messageid"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/init(message:type:peerRecipient:)":{"role":"symbol","title":"init(message:type:peerRecipient:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peerRecipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:peerRecipient:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:type:peerRecipient:"}],"url":"\/documentation\/hmssdk\/hmsmessage\/init(message:type:peerrecipient:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/init(message:type:)":{"role":"symbol","title":"init(message:type:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:type:"}],"url":"\/documentation\/hmssdk\/hmsmessage\/init(message:type:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/init(message:type:rolesRecipient:)":{"role":"symbol","title":"init(message:type:rolesRecipient:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rolesRecipient"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:rolesRecipient:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:type:rolesRecipient:"}],"url":"\/documentation\/hmssdk\/hmsmessage\/init(message:type:rolesrecipient:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSMessage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/message","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/messageID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/recipient","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/sender","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/time","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:peerRecipient:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/init(message:type:rolesRecipient:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1time\/title","value":"time"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1time\/fragments","value":[{"kind":"identifier","text":"time"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage\/title","value":"HMSMessage"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage\/fragments","value":[{"kind":"identifier","text":"HMSMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1recipient\/title","value":"recipient"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1recipient\/fragments","value":[{"kind":"identifier","text":"recipient"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1messageID\/title","value":"messageID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1messageID\/fragments","value":[{"kind":"identifier","text":"messageID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1init(message:type:peerRecipient:)\/title","value":"initWithMessage:type:peerRecipient:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1init(message:type:peerRecipient:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:type:peerRecipient:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1init(message:type:)\/title","value":"initWithMessage:type:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1init(message:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1init(message:type:rolesRecipient:)\/title","value":"initWithMessage:type:rolesRecipient:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1init(message:type:rolesRecipient:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMessage:type:rolesRecipient:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}