{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestionbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestionbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Builder class for creating a poll question."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"title":"HMSPollQuestionBuilder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/addOption(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/addQuizOption(with:isCorrect:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/build()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withAnswerHidden(answerHidden:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanBeSkipped(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanChangeResponse(canChangeResponse:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withDuration(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withIndex(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withMaxLength(maxLength:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withMinLength(minLength:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withTitle(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withType(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withWeight(weight:)"]}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/init"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withWeight(weight:)":{"role":"symbol","title":"withWeight(weight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withWeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"weight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the weight of the question for score calculation."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withWeight(weight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withWeightWithWeight:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withweight(weight:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder":{"role":"symbol","title":"HMSPollQuestionBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withCanChangeResponse(canChangeResponse:)":{"role":"symbol","title":"withCanChangeResponse(canChangeResponse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCanChangeResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"canChangeResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets wether users are allowed to change their response to the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanChangeResponse(canChangeResponse:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withCanChangeResponseWithCanChangeResponse:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withcanchangeresponse(canchangeresponse:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withIndex(_:)":{"role":"symbol","title":"withIndex(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withIndex"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the index of the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withIndex(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withIndex:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withindex(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withDuration(_:)":{"role":"symbol","title":"withDuration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDuration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the duration of the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withDuration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withDuration:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withduration(_:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/addQuizOption(with:isCorrect:)":{"role":"symbol","title":"addQuizOption(with:isCorrect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addQuizOption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCorrect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Adds an option to the question if poll type is set to quiz."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/addQuizOption(with:isCorrect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addQuizOptionWith:isCorrect:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/addquizoption(with:iscorrect:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withTitle(_:)":{"role":"symbol","title":"withTitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the title of the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withTitle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withTitle:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withtitle(_:)"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withCanBeSkipped(_:)":{"role":"symbol","title":"withCanBeSkipped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCanBeSkipped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets whether the question can be skipped."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanBeSkipped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withCanBeSkipped:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withcanbeskipped(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/addOption(with:)":{"role":"symbol","title":"addOption(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addOption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Adds an option to the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/addOption(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addOptionWith:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/addoption(with:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withMinLength(minLength:)":{"role":"symbol","title":"withMinLength(minLength:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withMinLength"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the minimum answer length of the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withMinLength(minLength:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withMinLengthWithMinLength:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withminlength(minlength:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withType(_:)":{"role":"symbol","title":"withType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollQuestionType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollQuestionType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the type of the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withType(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withType:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withtype(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withAnswerHidden(answerHidden:)":{"role":"symbol","title":"withAnswerHidden(answerHidden:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAnswerHidden"},{"kind":"text","text":"("},{"kind":"externalParam","text":"answerHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets wether the correct answer will be returned as a part of the fetchPollQuestions API response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withAnswerHidden(answerHidden:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withAnswerHiddenWithAnswerHidden:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withanswerhidden(answerhidden:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withMaxLength(maxLength:)":{"role":"symbol","title":"withMaxLength(maxLength:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withMaxLength"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets the maximum answer length of the question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withMaxLength(maxLength:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withMaxLengthWithMaxLength:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withmaxlength(maxlength:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"}],"abstract":[{"type":"text","text":"Builds the question object with the configured properties."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/build()","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/build()"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollQuestionBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/addOption(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/addQuizOption(with:isCorrect:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/init","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withAnswerHidden(answerHidden:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanBeSkipped(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanChangeResponse(canChangeResponse:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withDuration(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withIndex(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withMaxLength(maxLength:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withMinLength(minLength:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withTitle(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withType(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withWeight(weight:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withWeight(weight:)\/title","value":"withWeightWithWeight:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withWeight(weight:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withWeightWithWeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/title","value":"HMSPollQuestionBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withCanChangeResponse(canChangeResponse:)\/title","value":"withCanChangeResponseWithCanChangeResponse:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withCanChangeResponse(canChangeResponse:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCanChangeResponseWithCanChangeResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withIndex(_:)\/title","value":"withIndex:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withIndex(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withDuration(_:)\/title","value":"withDuration:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withDuration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1addQuizOption(with:isCorrect:)\/title","value":"addQuizOptionWith:isCorrect:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1addQuizOption(with:isCorrect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addQuizOptionWith:isCorrect:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withTitle(_:)\/title","value":"withTitle:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withTitle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withTitle:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withCanBeSkipped(_:)\/title","value":"withCanBeSkipped:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withCanBeSkipped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCanBeSkipped:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1addOption(with:)\/title","value":"addOptionWith:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1addOption(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addOptionWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withMinLength(minLength:)\/title","value":"withMinLengthWithMinLength:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withMinLength(minLength:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withMinLengthWithMinLength:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withType(_:)\/title","value":"withType:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withType(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withType:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withAnswerHidden(answerHidden:)\/title","value":"withAnswerHiddenWithAnswerHidden:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withAnswerHidden(answerHidden:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withAnswerHiddenWithAnswerHidden:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withMaxLength(maxLength:)\/title","value":"withMaxLengthWithMaxLength:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withMaxLength(maxLength:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withMaxLengthWithMaxLength:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}