{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUpdateType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollupdatetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollupdatetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/resultsUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/started","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/stopped"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUpdateType"}],"title":"HMSPollUpdateType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSPollUpdateType","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollUpdateType"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspollupdatetype\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType/stopped":{"role":"symbol","title":"HMSPollUpdateType.stopped","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/stopped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUpdateTypeStopped"}],"url":"\/documentation\/hmssdk\/hmspollupdatetype\/stopped"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspollupdatetype\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType/resultsUpdated":{"role":"symbol","title":"HMSPollUpdateType.resultsUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultsUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/resultsUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUpdateTypeResultsUpdated"}],"url":"\/documentation\/hmssdk\/hmspollupdatetype\/resultsupdated"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollupdatetype\/init(rawvalue:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType/started":{"role":"symbol","title":"HMSPollUpdateType.started","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/started","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUpdateTypeStarted"}],"url":"\/documentation\/hmssdk\/hmspollupdatetype\/started"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUpdateType":{"role":"symbol","title":"HMSPollUpdateType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUpdateType"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUpdateType"}],"url":"\/documentation\/hmssdk\/hmspollupdatetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollUpdateType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollUpdateType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPollUpdateType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/resultsUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/started","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUpdateType\/stopped"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUpdateType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType~1stopped\/title","value":"HMSPollUpdateTypeStopped"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType~1stopped\/fragments","value":[{"kind":"identifier","text":"HMSPollUpdateTypeStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType~1resultsUpdated\/title","value":"HMSPollUpdateTypeResultsUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType~1resultsUpdated\/fragments","value":[{"kind":"identifier","text":"HMSPollUpdateTypeResultsUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType~1started\/title","value":"HMSPollUpdateTypeStarted"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType~1started\/fragments","value":[{"kind":"identifier","text":"HMSPollUpdateTypeStarted"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType\/title","value":"HMSPollUpdateType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUpdateType\/fragments","value":[{"kind":"identifier","text":"HMSPollUpdateType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}