{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/s12CaseIterableP","doc:\/\/live.100ms.HMS\/Se","doc:\/\/live.100ms.HMS\/SE","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the type of a poll question."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionType"}],"title":"HMSPollQuestionType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSPollQuestionType","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionType"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/longAnswer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/multipleChoice","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/shortAnswer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/singleChoice"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/shortAnswer":{"role":"symbol","title":"HMSPollQuestionType.shortAnswer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortAnswer"}],"abstract":[{"type":"text","text":"The question expects a short text answer."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/shortAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionTypeShortAnswer"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype\/shortanswer"},"doc://live.100ms.HMS/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/live.100ms.HMS\/SE"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestiontype\/rawrepresentable-implementations"},"doc://live.100ms.HMS/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/live.100ms.HMS\/s12CaseIterableP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/singleChoice":{"role":"symbol","title":"HMSPollQuestionType.singleChoice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleChoice"}],"abstract":[{"type":"text","text":"The question allows for a single choice answer."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/singleChoice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionTypeSingleChoice"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype\/singlechoice"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/live.100ms.HMS\/Se"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/multipleChoice":{"role":"symbol","title":"HMSPollQuestionType.multipleChoice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleChoice"}],"abstract":[{"type":"text","text":"The question allows for multiple choice answers."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/multipleChoice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype\/multiplechoice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType":{"role":"symbol","title":"HMSPollQuestionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionType"}],"abstract":[{"type":"text","text":"Represents the type of a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionType"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestiontype\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestiontype\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/longAnswer":{"role":"symbol","title":"HMSPollQuestionType.longAnswer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"longAnswer"}],"abstract":[{"type":"text","text":"The question expects a long text answer."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/longAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionTypeLongAnswer"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype\/longanswer"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollQuestionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPollQuestionType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/longAnswer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/multipleChoice","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/shortAnswer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/singleChoice"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1shortAnswer\/title","value":"HMSPollQuestionTypeShortAnswer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1shortAnswer\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionTypeShortAnswer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1singleChoice\/title","value":"HMSPollQuestionTypeSingleChoice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1singleChoice\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionTypeSingleChoice"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1multipleChoice\/title","value":"HMSPollQuestionTypeMultipleChoice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1multipleChoice\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType\/title","value":"HMSPollQuestionType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionType"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1longAnswer\/title","value":"HMSPollQuestionTypeLongAnswer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1longAnswer\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionTypeLongAnswer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}