{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Builder class for creating a poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"title":"HMSPollBuilder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollBuilder"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addLongAnswerQuestion(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addMultiChoiceQuestion(with:options:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addQuestion(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addShortAnswerQuestion(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addSingleChoiceQuestion(with:options:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/build()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withAnonymous(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withCategory(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withDuration(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withPollID(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanViewResponses(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanVote(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withTitle(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withUserTrackingMode(_:)"]}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/addSingleChoiceQuestion(with:options:)":{"role":"symbol","title":"addSingleChoiceQuestion(with:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addSingleChoiceQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Adds a single-choice question to the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addSingleChoiceQuestion(with:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addSingleChoiceQuestionWith:options:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/addsinglechoicequestion(with:options:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withPollID(_:)":{"role":"symbol","title":"withPollID(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withPollID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the ID of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withPollID(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withPollID:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withpollid(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/addMultiChoiceQuestion(with:options:)":{"role":"symbol","title":"addMultiChoiceQuestion(with:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addMultiChoiceQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Adds a multiple-choice question to the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addMultiChoiceQuestion(with:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addMultiChoiceQuestionWith:options:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/addmultichoicequestion(with:options:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"}],"abstract":[{"type":"text","text":"Builds the poll object with the configured properties."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/build()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withRolesThatCanVote(_:)":{"role":"symbol","title":"withRolesThatCanVote(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRolesThatCanVote"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the roles that can vote in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanVote(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withRolesThatCanVote:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withrolesthatcanvote(_:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/addLongAnswerQuestion(with:)":{"role":"symbol","title":"addLongAnswerQuestion(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addLongAnswerQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Adds a long answer question to the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addLongAnswerQuestion(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addLongAnswerQuestionWith:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/addlonganswerquestion(with:)"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withRolesThatCanViewResponses(_:)":{"role":"symbol","title":"withRolesThatCanViewResponses(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRolesThatCanViewResponses"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the roles that can view responses in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanViewResponses(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withRolesThatCanViewResponses:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withrolesthatcanviewresponses(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withCategory(_:)":{"role":"symbol","title":"withCategory(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the category of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withCategory(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withCategory:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withcategory(_:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withTitle(_:)":{"role":"symbol","title":"withTitle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTitle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the title of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withTitle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withTitle:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withtitle(_:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withDuration(_:)":{"role":"symbol","title":"withDuration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDuration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the duration of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withDuration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withDuration:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withduration(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/addQuestion(with:)":{"role":"symbol","title":"addQuestion(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Adds a question to the poll using a question builder."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addQuestion(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addQuestionWith:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/addquestion(with:)"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withUserTrackingMode(_:)":{"role":"symbol","title":"withUserTrackingMode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withUserTrackingMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollUserTrackingMode","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollUserTrackingMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the user tracking mode of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withUserTrackingMode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withUserTrackingMode:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withusertrackingmode(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder":{"role":"symbol","title":"HMSPollBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollBuilder"}],"url":"\/documentation\/hmssdk\/hmspollbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/addShortAnswerQuestion(with:)":{"role":"symbol","title":"addShortAnswerQuestion(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addShortAnswerQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Adds a short answer question to the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addShortAnswerQuestion(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addShortAnswerQuestionWith:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/addshortanswerquestion(with:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/init"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withAnonymous(_:)":{"role":"symbol","title":"withAnonymous(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAnonymous"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets whether the poll is anonymous."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withAnonymous(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withAnonymous:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withanonymous(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPollBuilder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addLongAnswerQuestion(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addMultiChoiceQuestion(with:options:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addQuestion(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addShortAnswerQuestion(with:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addSingleChoiceQuestion(with:options:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/build()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/init","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withAnonymous(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withCategory(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withDuration(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withPollID(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanViewResponses(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanVote(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withTitle(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withUserTrackingMode(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addSingleChoiceQuestion(with:options:)\/title","value":"addSingleChoiceQuestionWith:options:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addSingleChoiceQuestion(with:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addSingleChoiceQuestionWith:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withPollID(_:)\/title","value":"withPollID:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withPollID(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withPollID:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addMultiChoiceQuestion(with:options:)\/title","value":"addMultiChoiceQuestionWith:options:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addMultiChoiceQuestion(with:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addMultiChoiceQuestionWith:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withRolesThatCanVote(_:)\/title","value":"withRolesThatCanVote:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withRolesThatCanVote(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withRolesThatCanVote:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addLongAnswerQuestion(with:)\/title","value":"addLongAnswerQuestionWith:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addLongAnswerQuestion(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addLongAnswerQuestionWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withRolesThatCanViewResponses(_:)\/title","value":"withRolesThatCanViewResponses:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withRolesThatCanViewResponses(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withRolesThatCanViewResponses:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withCategory(_:)\/title","value":"withCategory:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withCategory(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCategory:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withTitle(_:)\/title","value":"withTitle:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withTitle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withTitle:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withDuration(_:)\/title","value":"withDuration:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withDuration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addQuestion(with:)\/title","value":"addQuestionWith:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addQuestion(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addQuestionWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withUserTrackingMode(_:)\/title","value":"withUserTrackingMode:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withUserTrackingMode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withUserTrackingMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/title","value":"HMSPollBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addShortAnswerQuestion(with:)\/title","value":"addShortAnswerQuestionWith:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addShortAnswerQuestion(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addShortAnswerQuestionWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withAnonymous(_:)\/title","value":"withAnonymous:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withAnonymous(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withAnonymous:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}