{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestionresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestionresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/Se","doc:\/\/live.100ms.HMS\/SE","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a response for a poll question."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponse"}],"title":"HMSPollQuestionResponse","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponse","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionResponse"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/duration","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/option","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/options","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/peer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/questionID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/responseFinal","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/skipped","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/text","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/type","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/update"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/encode(to:)"]}],"references":{"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestionresponse\/encode(to:)"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/text":{"role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The text answer provided (in case of short\/long answer question)."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/text","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"text"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/text"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The list of indexes of selected options (in case of multiple choice question)."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/options","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"options"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/options"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/update":{"role":"symbol","title":"update","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A flag indicating whether the response was updated from previous response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/update","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"update"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/update"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestionresponse\/init(from:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/responseFinal":{"role":"symbol","title":"responseFinal","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseFinal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A flag indicating whether the response is final in case multiple responses were sent for this question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/responseFinal","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollquestionresponse\/responsefinal"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/live.100ms.HMS\/SE"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Time taken to respond."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/duration"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/skipped":{"role":"symbol","title":"skipped","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A flag indicating whether the question was skipped or not."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/skipped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"skipped"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/skipped"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/option":{"role":"symbol","title":"option","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The index of the selected option (in case of single choice question)."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/option","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"option"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/option"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/questionID":{"role":"symbol","title":"questionID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"questionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The ID of the question associated with the response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/questionID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"questionID"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/questionid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollQuestionType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollQuestionType"}],"abstract":[{"type":"text","text":"The type of the question associated with the response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/type"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse":{"role":"symbol","title":"HMSPollQuestionResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponse"}],"abstract":[{"type":"text","text":"Represents a response for a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionResponse"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/peer":{"role":"symbol","title":"peer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResponsePeerInfo","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponsePeerInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The peer information associated with the response. Depends on the tracking type selected for poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/peer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peer"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/peer"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/live.100ms.HMS\/Se"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollQuestionResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionResponse"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPollQuestionResponse"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/duration","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/option","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/options","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/peer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/questionID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/skipped","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/text","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/type","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/update"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponse"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1text\/title","value":"text"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1text\/fragments","value":[{"kind":"identifier","text":"text"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1options\/title","value":"options"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1options\/fragments","value":[{"kind":"identifier","text":"options"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1update\/title","value":"update"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1update\/fragments","value":[{"kind":"identifier","text":"update"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1skipped\/title","value":"skipped"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1skipped\/fragments","value":[{"kind":"identifier","text":"skipped"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1option\/title","value":"option"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1option\/fragments","value":[{"kind":"identifier","text":"option"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1questionID\/title","value":"questionID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1questionID\/fragments","value":[{"kind":"identifier","text":"questionID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse\/title","value":"HMSPollQuestionResponse"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1peer\/title","value":"peer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1peer\/fragments","value":[{"kind":"identifier","text":"peer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}