{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteVideoTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsremotevideotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsremotevideotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/layer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/layerDefinitions"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/isPlaybackAllowed()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/setPlaybackAllowed(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteVideoTrack"}],"title":"HMSRemoteVideoTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSRemoteVideoTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoTrack/isPlaybackAllowed()":{"role":"symbol","title":"isPlaybackAllowed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackAllowed"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/isPlaybackAllowed()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPlaybackAllowed"}],"url":"\/documentation\/hmssdk\/hmsremotevideotrack\/isplaybackallowed()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoTrack/setPlaybackAllowed(_:)":{"role":"symbol","title":"setPlaybackAllowed(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPlaybackAllowed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/setPlaybackAllowed(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPlaybackAllowed:"}],"url":"\/documentation\/hmssdk\/hmsremotevideotrack\/setplaybackallowed(_:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoTrack/layerDefinitions":{"role":"symbol","title":"layerDefinitions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerDefinitions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerDefinition","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerDefinition"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/layerDefinitions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerDefinitions"}],"url":"\/documentation\/hmssdk\/hmsremotevideotrack\/layerdefinitions"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoTrack/layer":{"role":"symbol","title":"layer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/layer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layer"}],"url":"\/documentation\/hmssdk\/hmsremotevideotrack\/layer"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoTrack":{"role":"symbol","title":"HMSRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsremotevideotrack"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack":{"role":"symbol","title":"HMSVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsvideotrack"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSRemoteVideoTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/layer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/layerDefinitions"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/isPlaybackAllowed()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack\/setPlaybackAllowed(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteVideoTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack","text":"HMSVideoTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1isPlaybackAllowed()\/title","value":"isPlaybackAllowed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1isPlaybackAllowed()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPlaybackAllowed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1setPlaybackAllowed(_:)\/title","value":"setPlaybackAllowed:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1setPlaybackAllowed(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPlaybackAllowed:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1layerDefinitions\/title","value":"layerDefinitions"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1layerDefinitions\/fragments","value":[{"kind":"identifier","text":"layerDefinitions"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1layer\/title","value":"layer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack~1layer\/fragments","value":[{"kind":"identifier","text":"layer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack\/title","value":"HMSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/title","value":"HMSVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}