{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsrtcstats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsrtcstats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bitrateReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bitrateSent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bytesReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bytesSent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/packetsReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/roundTripTime"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStats"}],"title":"HMSRTCStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSRTCStats","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRTCStats"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/bitrateSent":{"role":"symbol","title":"bitrateSent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bitrateSent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrateSent"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/bitratesent"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/roundTripTime":{"role":"symbol","title":"roundTripTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundTripTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/roundTripTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roundTripTime"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/roundtriptime"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/bytesSent":{"role":"symbol","title":"bytesSent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bytesSent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytesSent"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/bytessent"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/packetsReceived":{"role":"symbol","title":"packetsReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/packetsReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetsReceived"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/packetsreceived"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/bitrateReceived":{"role":"symbol","title":"bitrateReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bitrateReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrateReceived"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/bitratereceived"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats":{"role":"symbol","title":"HMSRTCStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRTCStats"}],"url":"\/documentation\/hmssdk\/hmsrtcstats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/packetsLost":{"role":"symbol","title":"packetsLost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/packetsLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetsLost"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/packetslost"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStats/bytesReceived":{"role":"symbol","title":"bytesReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bytesReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytesReceived"}],"url":"\/documentation\/hmssdk\/hmsrtcstats\/bytesreceived"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSRTCStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRTCStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSRTCStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bitrateReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bitrateSent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bytesReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/bytesSent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/packetsReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStats\/roundTripTime"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bitrateSent\/title","value":"bitrateSent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bitrateSent\/fragments","value":[{"kind":"identifier","text":"bitrateSent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1roundTripTime\/title","value":"roundTripTime"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1roundTripTime\/fragments","value":[{"kind":"identifier","text":"roundTripTime"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bytesSent\/title","value":"bytesSent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bytesSent\/fragments","value":[{"kind":"identifier","text":"bytesSent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1packetsReceived\/title","value":"packetsReceived"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1packetsReceived\/fragments","value":[{"kind":"identifier","text":"packetsReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bitrateReceived\/title","value":"bitrateReceived"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bitrateReceived\/fragments","value":[{"kind":"identifier","text":"bitrateReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats\/title","value":"HMSRTCStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats\/fragments","value":[{"kind":"identifier","text":"HMSRTCStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1packetsLost\/title","value":"packetsLost"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1packetsLost\/fragments","value":[{"kind":"identifier","text":"packetsLost"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bytesReceived\/title","value":"bytesReceived"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStats~1bytesReceived\/fragments","value":[{"kind":"identifier","text":"bytesReceived"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}