{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssamplebufferdisplayview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssamplebufferdisplayview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCoding","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/objc(pl)CALayerDelegate","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/objc(pl)UIAccessibilityIdentification","doc:\/\/live.100ms.HMS\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/live.100ms.HMS\/objc(pl)UIAppearance","doc:\/\/live.100ms.HMS\/objc(pl)UIAppearanceContainer","doc:\/\/live.100ms.HMS\/objc(pl)UICoordinateSpace","doc:\/\/live.100ms.HMS\/objc(pl)UIDynamicItem","doc:\/\/live.100ms.HMS\/objc(pl)UIFocusEnvironment","doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItem","doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItemContainer","doc:\/\/live.100ms.HMS\/objc(pl)UILargeContentViewerItem","doc:\/\/live.100ms.HMS\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/live.100ms.HMS\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/live.100ms.HMS\/objc(pl)UIResponderStandardEditActions","doc:\/\/live.100ms.HMS\/objc(pl)UITraitEnvironment","doc:\/\/live.100ms.HMS\/objc(pl)UIUserActivityRestoring","doc:\/\/live.100ms.HMS\/objc(pl)RTCVideoRenderer"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/isEnabled","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/preferredSize","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/track","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/videoContentMode"]},{"title":"Type Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/layerClass"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/RTCVideoRenderer-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"title":"HMSSampleBufferDisplayView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSSampleBufferDisplayView","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)CALayerDelegate"},"doc://live.100ms.HMS/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UILargeContentViewerItem"},"doc://live.100ms.HMS/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIAccessibilityIdentification"},"doc://live.100ms.HMS/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIAppearanceContainer"},"doc://live.100ms.HMS/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItem"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/preferredSize":{"role":"symbol","title":"preferredSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/preferredSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredSize"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/preferredsize"},"doc://live.100ms.HMS/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://live.100ms.HMS/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UITraitEnvironment"},"doc://live.100ms.HMS/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView":{"role":"symbol","title":"HMSSampleBufferDisplayView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview"},"doc://live.100ms.HMS/objc(pl)RTCVideoRenderer":{"type":"unresolvable","title":"RTCVideoRenderer","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)RTCVideoRenderer"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIPasteConfigurationSupporting"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/isEnabled":{"role":"symbol","title":"isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/isEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/isenabled"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/layerClass":{"role":"symbol","title":"layerClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/layerClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerClass"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/layerclass"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/videoContentMode":{"role":"symbol","title":"videoContentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoContentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/videoContentMode","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/videocontentmode"},"doc://live.100ms.HMS/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)UIView"},"doc://live.100ms.HMS/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIResponderStandardEditActions"},"doc://live.100ms.HMS/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIAppearance"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/track":{"role":"symbol","title":"track","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/track","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"track"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/track"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/init(frame:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSampleBufferDisplayView/RTCVideoRenderer-Implementations":{"role":"collectionGroup","title":"RTCVideoRenderer Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/RTCVideoRenderer-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmssamplebufferdisplayview\/rtcvideorenderer-implementations"},"doc://live.100ms.HMS/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIFocusEnvironment"},"doc://live.100ms.HMS/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItemContainer"},"doc://live.100ms.HMS/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIDynamicItem"},"doc://live.100ms.HMS/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIUserActivityRestoring"},"doc://live.100ms.HMS/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UICoordinateSpace"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSCoding"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSSampleBufferDisplayView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/isEnabled","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/preferredSize","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/track"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/init(frame:)"]},{"title":"Type Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/layerClass"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSampleBufferDisplayView\/RTCVideoRenderer-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)RTCVideoRenderer"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSampleBufferDisplayView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1preferredSize\/title","value":"preferredSize"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1preferredSize\/fragments","value":[{"kind":"identifier","text":"preferredSize"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView\/title","value":"HMSSampleBufferDisplayView"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView\/fragments","value":[{"kind":"identifier","text":"HMSSampleBufferDisplayView"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1isEnabled\/title","value":"isEnabled"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1isEnabled\/fragments","value":[{"kind":"identifier","text":"isEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1layerClass\/title","value":"layerClass"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1layerClass\/fragments","value":[{"kind":"identifier","text":"layerClass"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1track\/title","value":"track"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1track\/fragments","value":[{"kind":"identifier","text":"track"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSampleBufferDisplayView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}