{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"title":"HMSUpdateListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(changeTrackStateRequest:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(join:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(localAudioStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(localVideoStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(message:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(peer:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(remoteAudioStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(remoteVideoStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(removedFromRoom:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(roleChangeRequest:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(room:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(rtcStats:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(sessionStoreAvailable:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(track:update:for:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(updated:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/onReconnected()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/onReconnecting()"]}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(localVideoStats:track:peer:)":{"role":"symbol","title":"on(localVideoStats:track:peer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"localVideoStats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSLocalVideoStats","preciseIdentifier":"c:objc(cs)HMSLocalVideoStats"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when stats have been collected for a local video track."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(localVideoStats:track:peer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onLocalVideoStats:track:peer:"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(localvideostats:track:peer:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(join:)":{"navigatorTitle":[{"kind":"identifier","text":"onJoin:"}],"role":"symbol","title":"on(join:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"join"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called on a successful JOIN of the room by the user"},{"type":"text","text":" "},{"type":"text","text":"This is the point where applications can stop showing its loading state"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(join:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(join:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(remoteVideoStats:track:peer:)":{"navigatorTitle":[{"kind":"identifier","text":"onRemoteVideoStats:track:peer:"}],"role":"symbol","title":"on(remoteVideoStats:track:peer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteVideoStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRemoteVideoStats","preciseIdentifier":"c:objc(cs)HMSRemoteVideoStats"},{"kind":"text","text":", "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when stats have been collected for a remote video track."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(remoteVideoStats:track:peer:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(remotevideostats:track:peer:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(localAudioStats:track:peer:)":{"navigatorTitle":[{"kind":"identifier","text":"onLocalAudioStats:track:peer:"}],"role":"symbol","title":"on(localAudioStats:track:peer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"localAudioStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSLocalAudioStats","preciseIdentifier":"c:objc(cs)HMSLocalAudioStats"},{"kind":"text","text":", "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrack","preciseIdentifier":"c:objc(cs)HMSAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when stats have been collected for a local audio track."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(localAudioStats:track:peer:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(localaudiostats:track:peer:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/onReconnecting()":{"navigatorTitle":[{"kind":"identifier","text":"onReconnecting"}],"role":"symbol","title":"onReconnecting()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReconnecting"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This is called when SDK detects a network issue and is trying to recover"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/onReconnecting()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/onreconnecting()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(updated:)":{"navigatorTitle":[{"kind":"identifier","text":"onUpdatedSpeakers:"}],"role":"symbol","title":"on(updated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"updated"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSpeaker","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSpeaker"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"This is called every 1 second with list of active speakers"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(updated:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(updated:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDataSource":{"role":"symbol","title":"HMSDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDataSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDataSource"}],"url":"\/documentation\/hmssdk\/hmsdatasource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(removedFromRoom:)":{"navigatorTitle":[{"kind":"identifier","text":"removedFromRoom:"}],"role":"symbol","title":"on(removedFromRoom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"removedFromRoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRemovedFromRoomNotification","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRemovedFromRoomNotification"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when someone removes the local peer for the current room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(removedFromRoom:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(removedfromroom:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(changeTrackStateRequest:)":{"navigatorTitle":[{"kind":"identifier","text":"changeTrackStateRequest:"}],"role":"symbol","title":"on(changeTrackStateRequest:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changeTrackStateRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSChangeTrackStateRequest","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSChangeTrackStateRequest"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when a change track state request arrives"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(changeTrackStateRequest:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(changetrackstaterequest:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(rtcStats:)":{"role":"symbol","title":"on(rtcStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtcStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRTCStatsReport","preciseIdentifier":"c:objc(cs)HMSRTCStatsReport"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when stats have been collected for the current session"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(rtcStats:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRTCStats:"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(rtcstats:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(remoteAudioStats:track:peer:)":{"navigatorTitle":[{"kind":"identifier","text":"onRemoteAudioStats:track:peer:"}],"role":"symbol","title":"on(remoteAudioStats:track:peer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteAudioStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRemoteAudioStats","preciseIdentifier":"c:objc(cs)HMSRemoteAudioStats"},{"kind":"text","text":", "},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrack","preciseIdentifier":"c:objc(cs)HMSAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when stats have been collected for a remote audio track."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(remoteAudioStats:track:peer:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(remoteaudiostats:track:peer:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(error:)":{"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","title":"on(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called when there is an error in the system"},{"type":"text","text":" "},{"type":"text","text":"and SDK has already retried to fix the error"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(error:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(track:update:for:)":{"navigatorTitle":[{"kind":"identifier","text":"onTrack:update:peer:"}],"role":"symbol","title":"on(track:update:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSTrackUpdate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when there are updates on an existing track"},{"type":"text","text":" "},{"type":"text","text":"or a new track got added\/existing track is removed"},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to render the video on screen whenever a track gets added"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(track:update:for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(track:update:for:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(room:update:)":{"navigatorTitle":[{"kind":"identifier","text":"onRoom:update:"}],"role":"symbol","title":"on(room:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoomUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSRoomUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when there is a change in any property of the Room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(room:update:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(room:update:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/onReconnected()":{"navigatorTitle":[{"kind":"identifier","text":"onReconnected"}],"role":"symbol","title":"onReconnected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReconnected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This is called when SDK successfully recovered from a network issue"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/onReconnected()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/onreconnected()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(peer:update:)":{"navigatorTitle":[{"kind":"identifier","text":"onPeer:update:"}],"role":"symbol","title":"on(peer:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called whenever there is an update on an existing peer"},{"type":"text","text":" "},{"type":"text","text":"or a new peer got added\/existing peer is removed."},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to keep a track of all the peers in the room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(peer:update:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(peer:update:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(sessionStoreAvailable:)":{"role":"symbol","title":"on(sessionStoreAvailable:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionStoreAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSessionStore","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSessionStore"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when HMSSessionStore is ready for use"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(sessionStoreAvailable:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSessionStoreAvailable:"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(sessionstoreavailable:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessage:"}],"role":"symbol","title":"on(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when there is a new broadcast message from any other peer in the room"},{"type":"text","text":" "},{"type":"text","text":"This can be used to implement chat is the room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(message:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(roleChangeRequest:)":{"navigatorTitle":[{"kind":"identifier","text":"roleChangeRequest:"}],"role":"symbol","title":"on(roleChangeRequest:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roleChangeRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoleChangeRequest","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoleChangeRequest"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when a role change request arrives"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(roleChangeRequest:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(rolechangerequest:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(changeTrackStateRequest:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(join:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(localAudioStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(localVideoStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(message:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(peer:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(remoteAudioStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(remoteVideoStats:track:peer:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(removedFromRoom:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(roleChangeRequest:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(room:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(rtcStats:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(sessionStoreAvailable:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(track:update:for:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(updated:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/onReconnected()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/onReconnecting()"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(localVideoStats:track:peer:)\/title","value":"onLocalVideoStats:track:peer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(localVideoStats:track:peer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocalVideoStats:track:peer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(join:)\/title","value":"onJoin:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(join:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onJoin:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(remoteVideoStats:track:peer:)\/title","value":"onRemoteVideoStats:track:peer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(remoteVideoStats:track:peer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRemoteVideoStats:track:peer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(localAudioStats:track:peer:)\/title","value":"onLocalAudioStats:track:peer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(localAudioStats:track:peer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocalAudioStats:track:peer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1onReconnecting()\/title","value":"onReconnecting"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1onReconnecting()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReconnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(updated:)\/title","value":"onUpdatedSpeakers:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(updated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUpdatedSpeakers:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(removedFromRoom:)\/title","value":"removedFromRoom:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(removedFromRoom:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removedFromRoom:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(changeTrackStateRequest:)\/title","value":"changeTrackStateRequest:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(changeTrackStateRequest:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeTrackStateRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(rtcStats:)\/title","value":"onRTCStats:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(rtcStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRTCStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(remoteAudioStats:track:peer:)\/title","value":"onRemoteAudioStats:track:peer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(remoteAudioStats:track:peer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRemoteAudioStats:track:peer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(error:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(track:update:for:)\/title","value":"onTrack:update:peer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(track:update:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTrack:update:peer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(room:update:)\/title","value":"onRoom:update:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(room:update:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRoom:update:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1onReconnected()\/title","value":"onReconnected"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1onReconnected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(peer:update:)\/title","value":"onPeer:update:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(peer:update:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPeer:update:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(sessionStoreAvailable:)\/title","value":"onSessionStoreAvailable:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(sessionStoreAvailable:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSessionStoreAvailable:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(message:)\/title","value":"onMessage:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(roleChangeRequest:)\/title","value":"roleChangeRequest:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(roleChangeRequest:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"roleChangeRequest:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}