{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVersionString"},{"kind":"text","text":": <<error type>>"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsversionstring"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVersionString","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Project version string for HMSSDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVersionString"},{"kind":"text","text":": <<error type>>"}],"title":"HMSVersionString","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@HMSVersionString","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVersionString"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVersionString":{"role":"symbol","title":"HMSVersionString","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVersionString"},{"kind":"text","text":": <<error type>>"}],"abstract":[{"type":"text","text":"Project version string for HMSSDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVersionString","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVersionString"}],"url":"\/documentation\/hmssdk\/hmsversionstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"HMSVersionString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVersionString"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVersionString"},{"kind":"text","text":"[]"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVersionString\/title","value":"HMSVersionString"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVersionString\/fragments","value":[{"kind":"identifier","text":"HMSVersionString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}