{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource","text":"HMSAudioSource"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettings\/audiosource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettings\/audiosource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioSource","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?"}],"title":"audioSource","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSAudioTrackSettings(py)audioSource","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"audioSource"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings":{"role":"symbol","title":"HMSAudioTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/audioSource":{"role":"symbol","title":"audioSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSource"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/audiosource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioSource":{"role":"symbol","title":"HMSAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioSource"}],"url":"\/documentation\/hmssdk\/hmsaudiosource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioSource"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource","text":"HMSAudioSource"},{"kind":"text","text":" * "},{"kind":"identifier","text":"audioSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1audioSource\/title","value":"audioSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1audioSource\/fragments","value":[{"kind":"identifier","text":"audioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioSource\/title","value":"HMSAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioSource\/fragments","value":[{"kind":"identifier","text":"HMSAudioSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}