{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerUserID"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollusertrackingmode\/customeruserid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollusertrackingmode\/customeruserid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/customerUserID","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User tracking is based on the customer ID."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerUserID"}],"title":"HMSPollUserTrackingMode.customerUserID","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPollUserTrackingMode@HMSPollUserTrackingModeCustomerUserID","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/customerUserID":{"role":"symbol","title":"HMSPollUserTrackingMode.customerUserID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerUserID"}],"abstract":[{"type":"text","text":"User tracking is based on the customer ID."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/customerUserID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/customeruserid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode":{"role":"symbol","title":"HMSPollUserTrackingMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"abstract":[{"type":"text","text":"Represents the user tracking mode for poll participation."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollUserTrackingModeCustomerUserID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1customerUserID\/title","value":"HMSPollUserTrackingModeCustomerUserID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1customerUserID\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode\/title","value":"HMSPollUserTrackingMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}