{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideocapturer\/camerafacing()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideocapturer\/camerafacing()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFacing()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"role":"symbol","title":"cameraFacing()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"symbolKind":"method","externalID":"c:objc(cs)HMSVideoCapturer(im)cameraFacing","extendedModule":"HMSSDK","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer":{"role":"symbol","title":"HMSVideoCapturer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoCapturer"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/cameraFacing()":{"role":"symbol","title":"cameraFacing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFacing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/camerafacing()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFacing":{"role":"symbol","title":"HMSCameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCameraFacing"}],"url":"\/documentation\/hmssdk\/hmscamerafacing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cameraFacing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraFacing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":") "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/title","value":"HMSVideoCapturer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/fragments","value":[{"kind":"identifier","text":"HMSVideoCapturer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1cameraFacing()\/title","value":"cameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1cameraFacing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFacing\/title","value":"HMSCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFacing\/fragments","value":[{"kind":"identifier","text":"HMSCameraFacing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}