{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"capturer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCVideoCapturer","preciseIdentifier":"c:objc(cs)RTCVideoCapturer"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution","text":"HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shim"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoCapturerShim"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideocapturer\/init(capturer:resolution:framerate:shim:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideocapturer\/init(capturer:resolution:framerate:shim:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/init(capturer:resolution:frameRate:shim:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCapturer:resolution:frameRate:shim:"}],"role":"symbol","title":"init(capturer:resolution:frameRate:shim:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"capturer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCVideoCapturer","preciseIdentifier":"c:objc(cs)RTCVideoCapturer"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shim"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoCapturerShim"},{"kind":"text","text":"!)"}],"symbolKind":"init","externalID":"c:objc(cs)HMSVideoCapturer(im)initWithCapturer:resolution:frameRate:shim:","extendedModule":"HMSSDK","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/init(capturer:resolution:frameRate:shim:)":{"role":"symbol","title":"init(capturer:resolution:frameRate:shim:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"capturer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCVideoCapturer","preciseIdentifier":"c:objc(cs)RTCVideoCapturer"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shim"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoCapturerShim"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/init(capturer:resolution:frameRate:shim:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCapturer:resolution:frameRate:shim:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/init(capturer:resolution:framerate:shim:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer":{"role":"symbol","title":"HMSVideoCapturer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoCapturer"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoResolution":{"role":"symbol","title":"HMSVideoResolution","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoResolution"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoResolution"}],"url":"\/documentation\/hmssdk\/hmsvideoresolution"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCapturer:resolution:frameRate:shim:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCapturer:resolution:frameRate:shim:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCapturer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCVideoCapturer","preciseIdentifier":"c:objc(cs)RTCVideoCapturer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"capturer"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"},{"kind":"internalParam","text":"resolution"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"frameRate"},{"kind":"text","text":" "},{"kind":"identifier","text":"shim:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoCapturerShim","preciseIdentifier":"c:objc(cs)HMSVideoCapturerShim"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"shim"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1init(capturer:resolution:frameRate:shim:)\/title","value":"initWithCapturer:resolution:frameRate:shim:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1init(capturer:resolution:frameRate:shim:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCapturer:resolution:frameRate:shim:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/title","value":"HMSVideoCapturer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/fragments","value":[{"kind":"identifier","text":"HMSVideoCapturer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoResolution\/title","value":"HMSVideoResolution"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoResolution\/fragments","value":[{"kind":"identifier","text":"HMSVideoResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}