{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraFacing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideocapturer\/setcamerafacing(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideocapturer\/setcamerafacing(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setCameraFacing(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraFacing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":")"}],"title":"setCameraFacing(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSVideoCapturer(im)setCameraFacing:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setCameraFacing:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/setCameraFacing(_:)":{"role":"symbol","title":"setCameraFacing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraFacing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setCameraFacing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCameraFacing:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/setcamerafacing(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFacing":{"role":"symbol","title":"HMSCameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCameraFacing"}],"url":"\/documentation\/hmssdk\/hmscamerafacing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer":{"role":"symbol","title":"HMSVideoCapturer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoCapturer"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setCameraFacing:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraFacing:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCameraFacing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setCameraFacing(_:)\/title","value":"setCameraFacing:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setCameraFacing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraFacing:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFacing\/title","value":"HMSCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFacing\/fragments","value":[{"kind":"identifier","text":"HMSCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/title","value":"HMSVideoCapturer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/fragments","value":[{"kind":"identifier","text":"HMSVideoCapturer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}