{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode","text":"HMSCameraFocusMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack\/focusmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack\/focusmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/focusMode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"}],"title":"focusMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSLocalVideoTrack(py)focusMode","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"focusMode"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/focusMode":{"role":"symbol","title":"focusMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/focusMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"focusMode"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/focusmode"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack":{"role":"symbol","title":"HMSLocalVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFocusMode":{"role":"symbol","title":"HMSCameraFocusMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCameraFocusMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCameraFocusMode"}],"url":"\/documentation\/hmssdk\/hmscamerafocusmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"focusMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"focusMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode","text":"HMSCameraFocusMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1focusMode\/title","value":"focusMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1focusMode\/fragments","value":[{"kind":"identifier","text":"focusMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFocusMode\/title","value":"HMSCameraFocusMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFocusMode\/fragments","value":[{"kind":"identifier","text":"HMSCameraFocusMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}