{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyCaptureDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"block"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack\/modifycapturedevice(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack\/modifycapturedevice(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/modifyCaptureDevice(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyCaptureDevice"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"modifyCaptureDevice(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSLocalVideoTrack(im)modifyCaptureDeviceUsingBlock:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/modifyCaptureDevice(_:)":{"role":"symbol","title":"modifyCaptureDevice(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyCaptureDevice"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/modifyCaptureDevice(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/modifycapturedevice(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack":{"role":"symbol","title":"HMSLocalVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"modifyCaptureDeviceUsingBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(AVCaptureDevice *)","preciseIdentifier":"c:BFv(#*$objc(cs)AVCaptureDevice)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1modifyCaptureDevice(_:)\/title","value":"modifyCaptureDeviceUsingBlock:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1modifyCaptureDevice(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}