{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPollUpdateListner"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/HMSPollListener","preciseIdentifier":"s:6HMSSDK22HMSInteractivityCenterC15HMSPollListenera","text":"HMSPollListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The closure to be called when a poll update occurs."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter\/addpollupdatelistner(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter\/addpollupdatelistner(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/addPollUpdateListner(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a poll update listener to receive poll updates."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPollUpdateListner"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollListener","preciseIdentifier":"s:6HMSSDK22HMSInteractivityCenterC15HMSPollListenera"},{"kind":"text","text":")"}],"title":"addPollUpdateListner(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter(im)addPollUpdateListner:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addPollUpdateListner:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter":{"role":"symbol","title":"HMSInteractivityCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Provides interactivity features."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSInteractivityCenter"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/HMSPollListener":{"role":"symbol","title":"HMSInteractivityCenter.HMSPollListener","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollListener"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/HMSPollListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollListener"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/hmspolllistener"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/addPollUpdateListner(_:)":{"role":"symbol","title":"addPollUpdateListner(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPollUpdateListner"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollListener","preciseIdentifier":"s:6HMSSDK22HMSInteractivityCenterC15HMSPollListenera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds a poll update listener to receive poll updates."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/addPollUpdateListner(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPollUpdateListner:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/addpollupdatelistner(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addPollUpdateListner:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPollUpdateListner:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addPollUpdateListner:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(HMSPoll *, enum HMSPollUpdateType)","preciseIdentifier":"c:BFv(#*$@M@HMSSDK@objc(cs)HMSPoll#$@M@HMSSDK@E@HMSPollUpdateType)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/title","value":"HMSInteractivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/fragments","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1addPollUpdateListner(_:)\/title","value":"addPollUpdateListner:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1addPollUpdateListner(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPollUpdateListner:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}