{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPollQuestions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll","text":"HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC","text":"HMSPollQuestion"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSAnalyticsEventTransport.h@T@HMSOperationStatusHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"poll","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The poll to set questions for."}]}]},{"name":"questions","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of poll questions."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The closure to be called upon completion, indicating the success or failure of the operation."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter\/setpollquestions(poll:questions:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/setPollQuestions(poll:questions:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the questions for a poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPollQuestions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSAnalyticsEventTransport.h@T@HMSOperationStatusHandler"},{"kind":"text","text":")"}],"title":"setPollQuestions(poll:questions:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6HMSSDK22HMSInteractivityCenterC16setPollQuestions4poll9questions10completionyAA7HMSPollC_SayAA0J8QuestionCGySb_s5Error_pSgtctF","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/setPollQuestions(poll:questions:completion:)":{"role":"symbol","title":"setPollQuestions(poll:questions:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPollQuestions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSAnalyticsEventTransport.h@T@HMSOperationStatusHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the questions for a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/setPollQuestions(poll:questions:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/setpollquestions(poll:questions:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll":{"role":"symbol","title":"HMSPoll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"abstract":[{"type":"text","text":"Represents a poll object."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}],"url":"\/documentation\/hmssdk\/hmspoll"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter":{"role":"symbol","title":"HMSInteractivityCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Provides interactivity features."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSInteractivityCenter"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestion":{"role":"symbol","title":"HMSPollQuestion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestion"}],"abstract":[{"type":"text","text":"Represents a question in a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestion"}],"url":"\/documentation\/hmssdk\/hmspollquestion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/title","value":"HMSPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/title","value":"HMSInteractivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/fragments","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}