{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastSettingsPolicy","text":"HMSSimulcastSettingsPolicy"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastsettings\/video"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastsettings\/video"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettings\/video","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastSettingsPolicy"},{"kind":"text","text":"?"}],"title":"video","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSSimulcastSettings(py)video","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"video"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastSettingsPolicy":{"role":"symbol","title":"HMSSimulcastSettingsPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastSettingsPolicy"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastSettingsPolicy"}],"url":"\/documentation\/hmssdk\/hmssimulcastsettingspolicy"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastSettings/video":{"role":"symbol","title":"video","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastSettingsPolicy"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettings\/video","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"video"}],"url":"\/documentation\/hmssdk\/hmssimulcastsettings\/video"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastSettings":{"role":"symbol","title":"HMSSimulcastSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastSettings"}],"url":"\/documentation\/hmssdk\/hmssimulcastsettings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"video"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"video"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastSettingsPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSimulcastSettingsPolicy","text":"HMSSimulcastSettingsPolicy"},{"kind":"text","text":" * "},{"kind":"identifier","text":"video"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettingsPolicy\/title","value":"HMSSimulcastSettingsPolicy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettingsPolicy\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastSettingsPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettings~1video\/title","value":"video"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettings~1video\/fragments","value":[{"kind":"identifier","text":"video"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettings\/title","value":"HMSSimulcastSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastSettings\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}