{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel","text":"HMSAnalyticsEventLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/level"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/level"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/level","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"title":"level","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSDefaultAnalyticsService(py)level","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"level"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService/level":{"role":"symbol","title":"level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"level"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/level"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService":{"role":"symbol","title":"HMSDefaultAnalyticsService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsService"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventLevel":{"role":"symbol","title":"HMSAnalyticsEventLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventlevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"level"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel","text":"HMSAnalyticsEventLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1level\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1level\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService\/title","value":"HMSDefaultAnalyticsService"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService\/fragments","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/title","value":"HMSAnalyticsEventLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventLevel\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}