{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult","text":"HMSPluginSupportResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsplugin\/activate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsplugin\/activate()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/activate()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"activate"}],"role":"symbol","title":"activate()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSPlugin(im)activate","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPlugin":{"role":"symbol","title":"HMSPlugin","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPlugin"}],"url":"\/documentation\/hmssdk\/hmsplugin"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult":{"role":"symbol","title":"HMSPluginSupportResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResult"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPlugin/activate()":{"navigatorTitle":[{"kind":"identifier","text":"activate"}],"role":"symbol","title":"activate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/activate()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsplugin\/activate()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"activate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult","text":"HMSPluginSupportResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"activate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin\/title","value":"HMSPlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin\/fragments","value":[{"kind":"identifier","text":"HMSPlugin"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/title","value":"HMSPluginSupportResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResult"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1activate()\/title","value":"activate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1activate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}