{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidChangeResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsplaybackdelegate\/playerdidchangeresolution(videosize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsplaybackdelegate\/playerdidchangeresolution(videosize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/playerDidChangeResolution(videoSize:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Player has switched to different resolution layer of HLS stream - due to improved\/degraded network condition or when user manually picks a different resolution"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidChangeResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"title":"playerDidChangeResolution(videoSize:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSHLSPlaybackDelegate(im)playerDidChangeResolutionWithVideoSize:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSPlaybackDelegate/playerDidChangeResolution(videoSize:)":{"role":"symbol","title":"playerDidChangeResolution(videoSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidChangeResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Player has switched to different resolution layer of HLS stream - due to improved\/degraded network condition or when user manually picks a different resolution"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/playerDidChangeResolution(videoSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"}],"url":"\/documentation\/hmssdk\/hmshlsplaybackdelegate\/playerdidchangeresolution(videosize:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSPlaybackDelegate":{"role":"symbol","title":"HMSHLSPlaybackDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"url":"\/documentation\/hmssdk\/hmshlsplaybackdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playerDidChangeResolutionWithVideoSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"},{"kind":"internalParam","text":"videoSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate~1playerDidChangeResolution(videoSize:)\/title","value":"playerDidChangeResolutionWithVideoSize:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate~1playerDidChangeResolution(videoSize:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate\/title","value":"HMSHLSPlaybackDelegate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate\/fragments","value":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}