{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(removedFromRoom:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"removedFromRoom"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemovedFromRoomNotification","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRemovedFromRoomNotification","text":"HMSRemovedFromRoomNotification"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"notification","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the notification containing reason for removing and the initiating peer"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(removedfromroom:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(removedfromroom:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(removedFromRoom:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when someone removes the local peer for the current room"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removedFromRoom:"}],"role":"symbol","title":"on(removedFromRoom:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"removedFromRoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRemovedFromRoomNotification","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRemovedFromRoomNotification"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener(im)removedFromRoom:","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(removedFromRoom:)":{"navigatorTitle":[{"kind":"identifier","text":"removedFromRoom:"}],"role":"symbol","title":"on(removedFromRoom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"removedFromRoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRemovedFromRoomNotification","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRemovedFromRoomNotification"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when someone removes the local peer for the current room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(removedFromRoom:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(removedfromroom:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemovedFromRoomNotification":{"role":"symbol","title":"HMSRemovedFromRoomNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemovedFromRoomNotification"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemovedFromRoomNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemovedFromRoomNotification"}],"url":"\/documentation\/hmssdk\/hmsremovedfromroomnotification"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removedFromRoom:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removedFromRoom:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removedFromRoom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemovedFromRoomNotification","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRemovedFromRoomNotification","text":"HMSRemovedFromRoomNotification"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(removedFromRoom:)\/title","value":"removedFromRoom:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(removedFromRoom:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removedFromRoom:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemovedFromRoomNotification\/title","value":"HMSRemovedFromRoomNotification"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemovedFromRoomNotification\/fragments","value":[{"kind":"identifier","text":"HMSRemovedFromRoomNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}