{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localVideoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","preciseIdentifier":"c:objc(cs)HMSLocalVideoTrack","text":"HMSLocalVideoTrack"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalpeer\/localvideotrack()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalpeer\/localvideotrack()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer\/localVideoTrack()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localVideoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSLocalVideoTrack","preciseIdentifier":"c:objc(cs)HMSLocalVideoTrack"},{"kind":"text","text":"?"}],"title":"localVideoTrack()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSLocalPeer(im)localVideoTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"localVideoTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalPeer/localVideoTrack()":{"role":"symbol","title":"localVideoTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localVideoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSLocalVideoTrack","preciseIdentifier":"c:objc(cs)HMSLocalVideoTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer\/localVideoTrack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalpeer\/localvideotrack()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack":{"role":"symbol","title":"HMSLocalVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalPeer":{"role":"symbol","title":"HMSLocalPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalPeer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalPeer"}],"url":"\/documentation\/hmssdk\/hmslocalpeer"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"localVideoTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"localVideoTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","preciseIdentifier":"c:objc(cs)HMSLocalVideoTrack","text":"HMSLocalVideoTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"localVideoTrack"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer~1localVideoTrack()\/title","value":"localVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer~1localVideoTrack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"localVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer\/title","value":"HMSLocalPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer\/fragments","value":[{"kind":"identifier","text":"HMSLocalPeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}