{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotsupported"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/devicenotsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/devicenotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/deviceNotsupported","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotsupported"}],"title":"HMSPluginUnsupportedErrorTypes.deviceNotsupported","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes@HMSPluginUnsupportedErrorTypesDeviceNotsupported","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/deviceNotsupported":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes.deviceNotsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotsupported"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/deviceNotsupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/devicenotsupported"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1deviceNotsupported\/title","value":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1deviceNotsupported\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/title","value":"HMSPluginUnsupportedErrorTypes"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}