{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatingSystemNotSupported"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/operatingsystemnotsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/operatingsystemnotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/operatingSystemNotSupported","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatingSystemNotSupported"}],"title":"HMSPluginUnsupportedErrorTypes.operatingSystemNotSupported","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes@HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/operatingSystemNotSupported":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes.operatingSystemNotSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatingSystemNotSupported"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/operatingSystemNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/operatingsystemnotsupported"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/title","value":"HMSPluginUnsupportedErrorTypes"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1operatingSystemNotSupported\/title","value":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1operatingSystemNotSupported\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}