{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind","text":"HMSTrackKind"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstrack\/kind"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstrack\/kind"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack\/kind","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind"}],"title":"kind","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSTrack(py)kind","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kind"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack/kind":{"role":"symbol","title":"kind","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack\/kind","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kind"}],"url":"\/documentation\/hmssdk\/hmstrack\/kind"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackKind":{"role":"symbol","title":"HMSTrackKind","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackKind"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackKind","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackKind"}],"url":"\/documentation\/hmssdk\/hmstrackkind"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack":{"role":"symbol","title":"HMSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrack"}],"abstract":[{"type":"text","text":"A track represents either the audio or video that makes up a stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrack"}],"url":"\/documentation\/hmssdk\/hmstrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"kind"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kind"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind","text":"HMSTrackKind"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack~1kind\/title","value":"kind"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack~1kind\/fragments","value":[{"kind":"identifier","text":"kind"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/title","value":"HMSTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/fragments","value":[{"kind":"identifier","text":"HMSTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}