{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPCMBuffer","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiobufferplayernode\/play(buffer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiobufferplayernode\/play(buffer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode\/play(buffer:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPCMBuffer","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"play(buffer:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSAudioBufferPlayerNode(im)playWithBuffer:error:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"playWithBuffer:error:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioBufferPlayerNode":{"role":"symbol","title":"HMSAudioBufferPlayerNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioBufferPlayerNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioBufferPlayerNode"}],"url":"\/documentation\/hmssdk\/hmsaudiobufferplayernode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioBufferPlayerNode/play(buffer:)":{"role":"symbol","title":"play(buffer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPCMBuffer","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode\/play(buffer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playWithBuffer:error:"}],"url":"\/documentation\/hmssdk\/hmsaudiobufferplayernode\/play(buffer:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playWithBuffer:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithBuffer:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"playWithBuffer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPCMBuffer","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferPlayerNode\/title","value":"HMSAudioBufferPlayerNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferPlayerNode\/fragments","value":[{"kind":"identifier","text":"HMSAudioBufferPlayerNode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferPlayerNode~1play(buffer:)\/title","value":"playWithBuffer:error:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferPlayerNode~1play(buffer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithBuffer:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}