{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipient","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessageRecipient","text":"HMSMessageRecipient"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsmessage\/recipient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsmessage\/recipient"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/recipient","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSMessageRecipient","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessageRecipient"}],"title":"recipient","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSMessage(py)recipient","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"recipient"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage/recipient":{"role":"symbol","title":"recipient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSMessageRecipient","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessageRecipient"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage\/recipient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recipient"}],"url":"\/documentation\/hmssdk\/hmsmessage\/recipient"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage":{"role":"symbol","title":"HMSMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessage"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessage"}],"url":"\/documentation\/hmssdk\/hmsmessage"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessageRecipient":{"role":"symbol","title":"HMSMessageRecipient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessageRecipient"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipient"}],"url":"\/documentation\/hmssdk\/hmsmessagerecipient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recipient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recipient"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipient","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessageRecipient","text":"HMSMessageRecipient"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recipient"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1recipient\/title","value":"recipient"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage~1recipient\/fragments","value":[{"kind":"identifier","text":"recipient"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage\/title","value":"HMSMessage"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage\/fragments","value":[{"kind":"identifier","text":"HMSMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipient\/title","value":"HMSMessageRecipient"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipient\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}