{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"earpiece"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice","text":"HMSAudioOutputDevice"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiooutputdevice\/earpiece"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiooutputdevice\/earpiece"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice\/earpiece","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"earpiece"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice"}],"title":"earpiece","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice(cpy)earpiece","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"earpiece"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioOutputDevice":{"role":"symbol","title":"HMSAudioOutputDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioOutputDevice"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioOutputDevice"}],"url":"\/documentation\/hmssdk\/hmsaudiooutputdevice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioOutputDevice/earpiece":{"role":"symbol","title":"earpiece","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"earpiece"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice\/earpiece","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"earpiece"}],"url":"\/documentation\/hmssdk\/hmsaudiooutputdevice\/earpiece"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"earpiece"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"earpiece"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice","text":"HMSAudioOutputDevice"},{"kind":"text","text":" * "},{"kind":"identifier","text":"earpiece"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice\/title","value":"HMSAudioOutputDevice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice\/fragments","value":[{"kind":"identifier","text":"HMSAudioOutputDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice~1earpiece\/title","value":"earpiece"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice~1earpiece\/fragments","value":[{"kind":"identifier","text":"earpiece"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}