{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice","text":"HMSAudioOutputDevice"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiooutputdevice\/speaker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiooutputdevice\/speaker"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice\/speaker","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice"}],"title":"speaker","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice(cpy)speaker","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"speaker"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioOutputDevice/speaker":{"role":"symbol","title":"speaker","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice\/speaker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speaker"}],"url":"\/documentation\/hmssdk\/hmsaudiooutputdevice\/speaker"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioOutputDevice":{"role":"symbol","title":"HMSAudioOutputDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioOutputDevice"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioOutputDevice"}],"url":"\/documentation\/hmssdk\/hmsaudiooutputdevice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"speaker"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speaker"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice","text":"HMSAudioOutputDevice"},{"kind":"text","text":" * "},{"kind":"identifier","text":"speaker"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice~1speaker\/title","value":"speaker"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice~1speaker\/fragments","value":[{"kind":"identifier","text":"speaker"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice\/title","value":"HMSAudioOutputDevice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioOutputDevice\/fragments","value":[{"kind":"identifier","text":"HMSAudioOutputDevice"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}