{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer","text":"HMSSimulcastLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastlayerdefinition\/init(layer:resolution:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastlayerdefinition\/init(layer:resolution:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/init(layer:resolution:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"title":"init(layer:resolution:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)HMSSimulcastLayerDefinition(im)initWithLayer:resolution:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLayer:resolution:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerDefinition/init(layer:resolution:)":{"role":"symbol","title":"init(layer:resolution:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/init(layer:resolution:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLayer:resolution:"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayerdefinition\/init(layer:resolution:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer":{"role":"symbol","title":"HMSSimulcastLayer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayer"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerDefinition":{"role":"symbol","title":"HMSSimulcastLayerDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayerdefinition"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLayer:resolution:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:resolution:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer","text":"HMSSimulcastLayer"},{"kind":"text","text":") "},{"kind":"internalParam","text":"layer"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"resolution"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1init(layer:resolution:)\/title","value":"initWithLayer:resolution:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1init(layer:resolution:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:resolution:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition\/title","value":"HMSSimulcastLayerDefinition"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}