{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(onJoin:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"join"},{"kind":"text","text":" "},{"kind":"internalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"room","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the room which was joined"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(join:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(join:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(join:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This will be called on a successful JOIN of the room by the user"},{"type":"text","text":" "},{"type":"text","text":"This is the point where applications can stop showing its loading state"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onJoin:"}],"role":"symbol","title":"on(join:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"join"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener(im)onJoin:","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(join:)":{"navigatorTitle":[{"kind":"identifier","text":"onJoin:"}],"role":"symbol","title":"on(join:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"join"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called on a successful JOIN of the room by the user"},{"type":"text","text":" "},{"type":"text","text":"This is the point where applications can stop showing its loading state"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(join:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(join:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom":{"role":"symbol","title":"HMSRoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}],"url":"\/documentation\/hmssdk\/hmsroom"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onJoin:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onJoin:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onJoin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"room"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(join:)\/title","value":"onJoin:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(join:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onJoin:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/title","value":"HMSRoom"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}