{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(onPeer:update:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate","text":"HMSPeerUpdate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"peer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the peer who joined\/left or was updated"}]}]},{"name":"update","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the triggered update type. Should be used to perform different UI Actions"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(peer:update:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(peer:update:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(peer:update:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This will be called whenever there is an update on an existing peer"},{"type":"text","text":" "},{"type":"text","text":"or a new peer got added\/existing peer is removed."},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to keep a track of all the peers in the room"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPeer:update:"}],"role":"symbol","title":"on(peer:update:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener(im)onPeer:update:","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate":{"role":"symbol","title":"HMSPeerUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdate"}],"url":"\/documentation\/hmssdk\/hmspeerupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(peer:update:)":{"navigatorTitle":[{"kind":"identifier","text":"onPeer:update:"}],"role":"symbol","title":"on(peer:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called whenever there is an update on an existing peer"},{"type":"text","text":" "},{"type":"text","text":"or a new peer got added\/existing peer is removed."},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to keep a track of all the peers in the room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(peer:update:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(peer:update:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPeer:update:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPeer:update:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPeer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peer"},{"kind":"text","text":" "},{"kind":"identifier","text":"update:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate","text":"HMSPeerUpdate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"update"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/title","value":"HMSPeerUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(peer:update:)\/title","value":"onPeer:update:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(peer:update:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPeer:update:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}