{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(onRTCStats:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtcStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsReport","preciseIdentifier":"c:objc(cs)HMSRTCStatsReport","text":"HMSRTCStatsReport"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"rtcStats","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the stats payload"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(rtcstats:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(rtcstats:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(rtcStats:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when stats have been collected for the current session"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtcStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRTCStatsReport","preciseIdentifier":"c:objc(cs)HMSRTCStatsReport"},{"kind":"text","text":")"}],"title":"on(rtcStats:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener(im)onRTCStats:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"onRTCStats:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(rtcStats:)":{"role":"symbol","title":"on(rtcStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtcStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRTCStatsReport","preciseIdentifier":"c:objc(cs)HMSRTCStatsReport"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when stats have been collected for the current session"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(rtcStats:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRTCStats:"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(rtcstats:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsReport":{"role":"symbol","title":"HMSRTCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStatsReport"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRTCStatsReport"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsreport"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onRTCStats:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRTCStats:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onRTCStats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsReport","preciseIdentifier":"c:objc(cs)HMSRTCStatsReport","text":"HMSRTCStatsReport"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rtcStats"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(rtcStats:)\/title","value":"onRTCStats:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(rtcStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRTCStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsReport\/title","value":"HMSRTCStatsReport"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsReport\/fragments","value":[{"kind":"identifier","text":"HMSRTCStatsReport"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}