{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(onSessionStoreAvailable:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionStoreAvailable"},{"kind":"text","text":" "},{"kind":"internalParam","text":"store"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSessionStore","text":"HMSSessionStore"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"store","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the HMSSessionStore instance for this session"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(sessionstoreavailable:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(sessionstoreavailable:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(sessionStoreAvailable:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when HMSSessionStore is ready for use"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionStoreAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSessionStore","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSessionStore"},{"kind":"text","text":")"}],"title":"on(sessionStoreAvailable:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener(im)onSessionStoreAvailable:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"onSessionStoreAvailable:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(sessionStoreAvailable:)":{"role":"symbol","title":"on(sessionStoreAvailable:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionStoreAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSessionStore","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSessionStore"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when HMSSessionStore is ready for use"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(sessionStoreAvailable:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSessionStoreAvailable:"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(sessionstoreavailable:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore":{"role":"symbol","title":"HMSSessionStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSessionStore"}],"abstract":[{"type":"text","text":"The HMSSessionStore class provides a centralized storage solution for session-related data."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSessionStore"}],"url":"\/documentation\/hmssdk\/hmssessionstore"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSessionStoreAvailable:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSessionStoreAvailable:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSessionStoreAvailable:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSessionStore","text":"HMSSessionStore"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"store"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(sessionStoreAvailable:)\/title","value":"onSessionStoreAvailable:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(sessionStoreAvailable:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSessionStoreAvailable:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore\/title","value":"HMSSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore\/fragments","value":[{"kind":"identifier","text":"HMSSessionStore"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}