{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(onUpdatedSpeakers:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"updated"},{"kind":"text","text":" "},{"kind":"internalParam","text":"speakers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSpeaker","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSpeaker","text":"HMSSpeaker"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"speakers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the list of speakers"}]}]}]},{"kind":"content","content":[{"anchor":"A-HMSSpeaker-object-contains","level":2,"type":"heading","text":"A HMSSpeaker object contains -"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"peer: the peer who is speaking"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"track: the track which is emitting audio"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"level: a number within range 1-100 indicating the audio volume"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A peer who is not present in the list indicates that the peer is not speaking"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This can be used to highlight currently speaking peers in the room"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(updated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsupdatelistener\/on(updated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(updated:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called every 1 second with list of active speakers"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onUpdatedSpeakers:"}],"role":"symbol","title":"on(updated:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"updated"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSpeaker","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSpeaker"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@HMSSDK@objc(pl)HMSUpdateListener(im)onUpdatedSpeakers:","required":true,"modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener/on(updated:)":{"navigatorTitle":[{"kind":"identifier","text":"onUpdatedSpeakers:"}],"role":"symbol","title":"on(updated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"updated"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSpeaker","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSpeaker"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"This is called every 1 second with list of active speakers"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener\/on(updated:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsupdatelistener\/on(updated:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSpeaker":{"role":"symbol","title":"HMSSpeaker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSpeaker"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSpeaker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSpeaker"}],"url":"\/documentation\/hmssdk\/hmsspeaker"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onUpdatedSpeakers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUpdatedSpeakers:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUpdatedSpeakers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<HMSSpeaker *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"speakers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(updated:)\/title","value":"onUpdatedSpeakers:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener~1on(updated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUpdatedSpeakers:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSpeaker\/title","value":"HMSSpeaker"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSpeaker\/fragments","value":[{"kind":"identifier","text":"HMSSpeaker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}