{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponsePeerInfo","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponsePeerInfo","text":"HMSPollResponsePeerInfo"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestionresponse\/peer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestionresponse\/peer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/peer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The peer information associated with the response. Depends on the tracking type selected for poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResponsePeerInfo","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponsePeerInfo"},{"kind":"text","text":"?"}],"title":"peer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponse(py)peer","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"peer"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollResponsePeerInfo":{"role":"symbol","title":"HMSPollResponsePeerInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollResponsePeerInfo"}],"abstract":[{"type":"text","text":"Represents the peer information associated with a poll response. The properties are filled according to HMSPollUserTrackingMode selected for the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponsePeerInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollResponsePeerInfo"}],"url":"\/documentation\/hmssdk\/hmspollresponsepeerinfo"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse":{"role":"symbol","title":"HMSPollQuestionResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponse"}],"abstract":[{"type":"text","text":"Represents a response for a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionResponse"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponse/peer":{"role":"symbol","title":"peer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResponsePeerInfo","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponsePeerInfo"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The peer information associated with the response. Depends on the tracking type selected for poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponse\/peer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peer"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponse\/peer"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"peer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"peer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponsePeerInfo","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponsePeerInfo","text":"HMSPollResponsePeerInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"peer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResponsePeerInfo\/title","value":"HMSPollResponsePeerInfo"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResponsePeerInfo\/fragments","value":[{"kind":"identifier","text":"HMSPollResponsePeerInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse\/title","value":"HMSPollQuestionResponse"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1peer\/title","value":"peer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponse~1peer\/fragments","value":[{"kind":"identifier","text":"peer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}