{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roles"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsmessagerecipienttype\/roles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsmessagerecipienttype\/roles"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType\/roles","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roles"}],"title":"HMSMessageRecipientType.roles","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSMessageRecipientType@HMSMessageRecipientTypeRoles","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipientTypeRoles"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessageRecipientType":{"role":"symbol","title":"HMSMessageRecipientType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessageRecipientType"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipientType"}],"url":"\/documentation\/hmssdk\/hmsmessagerecipienttype"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessageRecipientType/roles":{"role":"symbol","title":"HMSMessageRecipientType.roles","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roles"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType\/roles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipientTypeRoles"}],"url":"\/documentation\/hmssdk\/hmsmessagerecipienttype\/roles"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSMessageRecipientTypeRoles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipientTypeRoles"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSMessageRecipientTypeRoles"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType\/title","value":"HMSMessageRecipientType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipientType"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType~1roles\/title","value":"HMSMessageRecipientTypeRoles"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType~1roles\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipientTypeRoles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}