{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"question"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestionresponseresult\/question"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestionresponseresult\/question"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponseResult\/question","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The ID of the question associated with the response result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"question"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"question","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponseResult(py)question","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"question"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponseResult"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponseResult/question":{"role":"symbol","title":"question","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"question"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The ID of the question associated with the response result."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponseResult\/question","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"question"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponseresult\/question"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponseResult":{"role":"symbol","title":"HMSPollQuestionResponseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponseResult"}],"abstract":[{"type":"text","text":"Represents the result of a poll question response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponseResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionResponseResult"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponseresult"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"question"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"question"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"question"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponseResult~1question\/title","value":"question"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponseResult~1question\/fragments","value":[{"kind":"identifier","text":"question"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponseResult\/title","value":"HMSPollQuestionResponseResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponseResult\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionResponseResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}