{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSVariant","text":"HMSHLSVariant"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsstreamingstate\/variants"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsstreamingstate\/variants"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStreamingState\/variants","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSHLSVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSVariant"},{"kind":"text","text":"]"}],"title":"variants","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSHLSStreamingState(py)variants","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"variants"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStreamingState"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStreamingState/variants":{"role":"symbol","title":"variants","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"variants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSHLSVariant","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSVariant"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStreamingState\/variants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"variants"}],"url":"\/documentation\/hmssdk\/hmshlsstreamingstate\/variants"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStreamingState":{"role":"symbol","title":"HMSHLSStreamingState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStreamingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSStreamingState"}],"url":"\/documentation\/hmssdk\/hmshlsstreamingstate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSVariant":{"role":"symbol","title":"HMSHLSVariant","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSVariant"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSVariant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSVariant"}],"url":"\/documentation\/hmssdk\/hmshlsvariant"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"variants"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"variants"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSHLSVariant *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"variants"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStreamingState~1variants\/title","value":"variants"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStreamingState~1variants\/fragments","value":[{"kind":"identifier","text":"variants"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStreamingState\/title","value":"HMSHLSStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStreamingState\/fragments","value":[{"kind":"identifier","text":"HMSHLSStreamingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSVariant\/title","value":"HMSHLSVariant"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSVariant\/fragments","value":[{"kind":"identifier","text":"HMSHLSVariant"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}