{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCanBeSkipped"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"canBeSkipped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","text":"HMSPollQuestionBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"canBeSkipped","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A flag indicating whether the question can be skipped."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated question builder instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestionbuilder\/withcanbeskipped(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestionbuilder\/withcanbeskipped(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanBeSkipped(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets whether the question can be skipped."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCanBeSkipped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"title":"withCanBeSkipped(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder(im)withCanBeSkipped:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"withCanBeSkipped:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder/withCanBeSkipped(_:)":{"role":"symbol","title":"withCanBeSkipped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCanBeSkipped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Sets whether the question can be skipped."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder\/withCanBeSkipped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withCanBeSkipped:"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder\/withcanbeskipped(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder":{"role":"symbol","title":"HMSPollQuestionBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"withCanBeSkipped:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCanBeSkipped:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","text":"HMSPollQuestionBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"withCanBeSkipped:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"canBeSkipped"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withCanBeSkipped(_:)\/title","value":"withCanBeSkipped:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder~1withCanBeSkipped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCanBeSkipped:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/title","value":"HMSPollQuestionBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}