{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticsevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticsevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/agent()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/deviceID()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/endpoint()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/eventID()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/includesPII()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/jsonDictionary()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/level()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/name()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/peer()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/properties()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/timestamp()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/token()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/websocketEndpoint()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"}],"title":"HMSAnalyticsEvent","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)HMSAnalyticsEvent","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/agent()":{"navigatorTitle":[{"kind":"identifier","text":"agent"}],"role":"symbol","title":"agent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"agent"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/agent()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/agent()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/name()":{"navigatorTitle":[{"kind":"identifier","text":"name"}],"role":"symbol","title":"name()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/name()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/name()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/peer()":{"navigatorTitle":[{"kind":"identifier","text":"peer"}],"role":"symbol","title":"peer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/peer()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/peer()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/jsonDictionary()":{"navigatorTitle":[{"kind":"identifier","text":"JSONDictionary"}],"role":"symbol","title":"jsonDictionary()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonDictionary"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/jsonDictionary()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/jsondictionary()"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/properties()":{"navigatorTitle":[{"kind":"identifier","text":"properties"}],"role":"symbol","title":"properties()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/properties()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/properties()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/websocketEndpoint()":{"navigatorTitle":[{"kind":"identifier","text":"websocketEndpoint"}],"role":"symbol","title":"websocketEndpoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketEndpoint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/websocketEndpoint()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/websocketendpoint()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/deviceID()":{"navigatorTitle":[{"kind":"identifier","text":"deviceID"}],"role":"symbol","title":"deviceID()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/deviceID()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/deviceid()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent":{"role":"symbol","title":"HMSAnalyticsEvent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEvent"}],"url":"\/documentation\/hmssdk\/hmsanalyticsevent"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/timestamp()":{"navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"role":"symbol","title":"timestamp()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/timestamp()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/timestamp()"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/endpoint()":{"navigatorTitle":[{"kind":"identifier","text":"endpoint"}],"role":"symbol","title":"endpoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpoint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/endpoint()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/endpoint()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/token()":{"navigatorTitle":[{"kind":"identifier","text":"token"}],"role":"symbol","title":"token()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/token()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/token()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/includesPII()":{"navigatorTitle":[{"kind":"identifier","text":"includesPII"}],"role":"symbol","title":"includesPII()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"includesPII"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/includesPII()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/includespii()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/level()":{"navigatorTitle":[{"kind":"identifier","text":"level"}],"role":"symbol","title":"level()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/level()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/level()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEvent/eventID()":{"navigatorTitle":[{"kind":"identifier","text":"eventID"}],"role":"symbol","title":"eventID()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventID"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/eventID()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticsevent\/eventid()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HMSAnalyticsEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/agent()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/deviceID()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/endpoint()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/eventID()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/includesPII()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/jsonDictionary()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/level()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/name()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/peer()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/properties()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/timestamp()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/token()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEvent\/websocketEndpoint()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEvent"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1agent()\/title","value":"agent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1agent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"agent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1name()\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1name()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1peer()\/title","value":"peer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1peer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1jsonDictionary()\/title","value":"JSONDictionary"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1jsonDictionary()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"JSONDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1properties()\/title","value":"properties"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1properties()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"properties"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1websocketEndpoint()\/title","value":"websocketEndpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1websocketEndpoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"websocketEndpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1deviceID()\/title","value":"deviceID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1deviceID()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deviceID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/title","value":"HMSAnalyticsEvent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1timestamp()\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1timestamp()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1endpoint()\/title","value":"endpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1endpoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1token()\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1token()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"token"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1includesPII()\/title","value":"includesPII"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1includesPII()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"includesPII"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1level()\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1level()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1eventID()\/title","value":"eventID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEvent~1eventID()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eventID"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}