{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettings"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCopying","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(builder:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:audioSource:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioSource:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/maxBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/trackDescription"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/build(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"title":"HMSAudioTrackSettings","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSAudioTrackSettings","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init(builder:)":{"role":"symbol","title":"init(builder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrackSettingsBuilder","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettingsBuilder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(builder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuilder:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init(builder:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init(maxBitrate:trackDescription:audioSource:)":{"role":"symbol","title":"init(maxBitrate:trackDescription:audioSource:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:audioSource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:audioSource:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:audiosource:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/audioSource":{"role":"symbol","title":"audioSource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSource"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/audiosource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)":{"role":"symbol","title":"init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioMode:audioSource:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:initialmutestate:audiomode:audiosource:)"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/audioMode":{"role":"symbol","title":"audioMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioMode"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/audiomode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/trackDescription":{"role":"symbol","title":"trackDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/trackDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackDescription"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/trackdescription"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings":{"role":"symbol","title":"HMSAudioTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/initialMuteState":{"role":"symbol","title":"initialMuteState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/initialMuteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialMuteState"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/initialmutestate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init(maxBitrate:trackDescription:initialMuteState:audioSource:)":{"role":"symbol","title":"init(maxBitrate:trackDescription:initialMuteState:audioSource:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioSource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:initialmutestate:audiosource:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init(maxBitrate:trackDescription:)":{"role":"symbol","title":"init(maxBitrate:trackDescription:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:)"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/maxBitrate":{"role":"symbol","title":"maxBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/maxBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxBitrate"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/maxbitrate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/build(_:)":{"role":"symbol","title":"build(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"HMSAudioTrackSettingsBuilder","preciseIdentifier":"c:objc(cs)HMSAudioTrackSettingsBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/build(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/build(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init()"},"doc://live.100ms.HMS/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSCopying"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/audioSource","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/maxBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/trackDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(builder:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:audioSource:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioSource:)"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/build(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(builder:)\/title","value":"initWithBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(builder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:audioSource:)\/title","value":"initWithMaxBitrate:trackDescription:audioSource:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:audioSource:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:audioSource:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1audioSource\/title","value":"audioSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1audioSource\/fragments","value":[{"kind":"identifier","text":"audioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)\/title","value":"initWithMaxBitrate:trackDescription:initialMuteState:audioMode:audioSource:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:initialMuteState:audioMode:audioSource:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioMode:audioSource:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1audioMode\/title","value":"audioMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1audioMode\/fragments","value":[{"kind":"identifier","text":"audioMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1trackDescription\/title","value":"trackDescription"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1trackDescription\/fragments","value":[{"kind":"identifier","text":"trackDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1initialMuteState\/title","value":"initialMuteState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1initialMuteState\/fragments","value":[{"kind":"identifier","text":"initialMuteState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:initialMuteState:audioSource:)\/title","value":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:initialMuteState:audioSource:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:)\/title","value":"initWithMaxBitrate:trackDescription:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1maxBitrate\/title","value":"maxBitrate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1maxBitrate\/fragments","value":[{"kind":"identifier","text":"maxBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1build(_:)\/title","value":"build:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1build(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"build:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}