{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventFactory"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsanalyticseventfactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsanalyticseventfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/joinedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/peer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/room","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/templateId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/token","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/websocketEndpoint"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/cleanup()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/connectedEvent(_:isTerminal:error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/consistencyFailEvent(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/disconnectedEvent(_:isTerminal:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/hlsStreamFailEvent(_:isTerminal:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/joinEvent(_:joinTime:retryCount:fromPreview:error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/performanceEvent(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/publishFailEvent(_:isTerminal:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/subscribeFailEvent(_:isTerminal:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"title":"HMSAnalyticsEventFactory","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)HMSAnalyticsEventFactory","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/endpoint":{"navigatorTitle":[{"kind":"identifier","text":"endpoint"}],"role":"symbol","title":"endpoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/endpoint","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/endpoint"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/peer":{"navigatorTitle":[{"kind":"identifier","text":"peer"}],"role":"symbol","title":"peer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/peer","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/peer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/joinEvent(_:joinTime:retryCount:fromPreview:error:)":{"navigatorTitle":[{"kind":"identifier","text":"joinEvent:joinTime:retryCount:fromPreview:error:"}],"role":"symbol","title":"joinEvent(_:joinTime:retryCount:fromPreview:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"retryCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/joinEvent(_:joinTime:retryCount:fromPreview:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/joinevent(_:jointime:retrycount:frompreview:error:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/room":{"navigatorTitle":[{"kind":"identifier","text":"room"}],"role":"symbol","title":"room","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/room","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/room"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/publishFailEvent(_:isTerminal:)":{"navigatorTitle":[{"kind":"identifier","text":"publishFailEvent:isTerminal:"}],"role":"symbol","title":"publishFailEvent(_:isTerminal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishFailEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTerminal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/publishFailEvent(_:isTerminal:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/publishfailevent(_:isterminal:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/websocketEndpoint":{"navigatorTitle":[{"kind":"identifier","text":"websocketEndpoint"}],"role":"symbol","title":"websocketEndpoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketEndpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/websocketEndpoint","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/websocketendpoint"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/hlsStreamFailEvent(_:isTerminal:)":{"navigatorTitle":[{"kind":"identifier","text":"hlsStreamFailEvent:isTerminal:"}],"role":"symbol","title":"hlsStreamFailEvent(_:isTerminal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsStreamFailEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isTerminal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/hlsStreamFailEvent(_:isTerminal:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/hlsstreamfailevent(_:isterminal:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/cleanup()":{"navigatorTitle":[{"kind":"identifier","text":"cleanup"}],"role":"symbol","title":"cleanup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/cleanup()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/cleanup()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/performanceEvent(_:)":{"navigatorTitle":[{"kind":"identifier","text":"performanceEvent:"}],"role":"symbol","title":"performanceEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performanceEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPerformanceStats","preciseIdentifier":"c:@S@HMSPerformanceStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/performanceEvent(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/performanceevent(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/disconnectedEvent(_:isTerminal:)":{"navigatorTitle":[{"kind":"identifier","text":"disconnectedEvent:isTerminal:"}],"role":"symbol","title":"disconnectedEvent(_:isTerminal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnectedEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isTerminal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/disconnectedEvent(_:isTerminal:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/disconnectedevent(_:isterminal:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/templateId":{"navigatorTitle":[{"kind":"identifier","text":"templateId"}],"role":"symbol","title":"templateId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/templateId","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/templateid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/subscribeFailEvent(_:isTerminal:)":{"navigatorTitle":[{"kind":"identifier","text":"subscribeFailEvent:isTerminal:"}],"role":"symbol","title":"subscribeFailEvent(_:isTerminal:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeFailEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTerminal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/subscribeFailEvent(_:isTerminal:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/subscribefailevent(_:isterminal:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/token":{"navigatorTitle":[{"kind":"identifier","text":"token"}],"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/token","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/token"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory":{"role":"symbol","title":"HMSAnalyticsEventFactory","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventfactory"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/rtcQOSEvent:":{"role":"symbol","title":"rtcQOSEvent:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcQOSEvent:"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/rtcQOSEvent:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcQOSEvent:"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/rtcqosevent:"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/frameworkInfo":{"navigatorTitle":[{"kind":"identifier","text":"frameworkInfo"}],"role":"symbol","title":"frameworkInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/frameworkInfo","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/frameworkinfo"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/connectedEvent(_:isTerminal:error:)":{"navigatorTitle":[{"kind":"identifier","text":"connectedEvent:isTerminal:error:"}],"role":"symbol","title":"connectedEvent(_:isTerminal:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectedEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTerminal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/connectedEvent(_:isTerminal:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/connectedevent(_:isterminal:error:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory":{"role":"symbol","title":"HMSDefaultAnalyticsEventFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/joinedAt":{"navigatorTitle":[{"kind":"identifier","text":"joinedAt"}],"role":"symbol","title":"joinedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/joinedAt","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/joinedat"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory/consistencyFailEvent(_:)":{"navigatorTitle":[{"kind":"identifier","text":"consistencyFailEvent:"}],"role":"symbol","title":"consistencyFailEvent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"consistencyFailEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsEvent","preciseIdentifier":"c:objc(pl)HMSAnalyticsEvent"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/consistencyFailEvent(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsanalyticseventfactory\/consistencyfailevent(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HMSAnalyticsEventFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/joinedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/peer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/room","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/templateId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/token","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/websocketEndpoint"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/cleanup()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/connectedEvent(_:isTerminal:error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/consistencyFailEvent(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/disconnectedEvent(_:isTerminal:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/hlsStreamFailEvent(_:isTerminal:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/joinEvent(_:joinTime:retryCount:fromPreview:error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/performanceEvent(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/publishFailEvent(_:isTerminal:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/rtcQOSEvent:","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory\/subscribeFailEvent(_:isTerminal:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventFactory"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1endpoint\/title","value":"endpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1endpoint\/fragments","value":[{"kind":"identifier","text":"endpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1peer\/title","value":"peer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1peer\/fragments","value":[{"kind":"identifier","text":"peer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1joinEvent(_:joinTime:retryCount:fromPreview:error:)\/title","value":"joinEvent:joinTime:retryCount:fromPreview:error:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1joinEvent(_:joinTime:retryCount:fromPreview:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinEvent:joinTime:retryCount:fromPreview:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1room\/title","value":"room"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1room\/fragments","value":[{"kind":"identifier","text":"room"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1publishFailEvent(_:isTerminal:)\/title","value":"publishFailEvent:isTerminal:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1publishFailEvent(_:isTerminal:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publishFailEvent:isTerminal:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1websocketEndpoint\/title","value":"websocketEndpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1websocketEndpoint\/fragments","value":[{"kind":"identifier","text":"websocketEndpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1hlsStreamFailEvent(_:isTerminal:)\/title","value":"hlsStreamFailEvent:isTerminal:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1hlsStreamFailEvent(_:isTerminal:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hlsStreamFailEvent:isTerminal:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1cleanup()\/title","value":"cleanup"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1cleanup()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanup"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1performanceEvent(_:)\/title","value":"performanceEvent:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1performanceEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"performanceEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1disconnectedEvent(_:isTerminal:)\/title","value":"disconnectedEvent:isTerminal:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1disconnectedEvent(_:isTerminal:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnectedEvent:isTerminal:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1templateId\/title","value":"templateId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1templateId\/fragments","value":[{"kind":"identifier","text":"templateId"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1subscribeFailEvent(_:isTerminal:)\/title","value":"subscribeFailEvent:isTerminal:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1subscribeFailEvent(_:isTerminal:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribeFailEvent:isTerminal:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1token\/fragments","value":[{"kind":"identifier","text":"token"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory\/title","value":"HMSAnalyticsEventFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1frameworkInfo\/title","value":"frameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1frameworkInfo\/fragments","value":[{"kind":"identifier","text":"frameworkInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1connectedEvent(_:isTerminal:error:)\/title","value":"connectedEvent:isTerminal:error:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1connectedEvent(_:isTerminal:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectedEvent:isTerminal:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory\/title","value":"HMSDefaultAnalyticsEventFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory\/fragments","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1joinedAt\/title","value":"joinedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1joinedAt\/fragments","value":[{"kind":"identifier","text":"joinedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1consistencyFailEvent(_:)\/title","value":"consistencyFailEvent:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory~1consistencyFailEvent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"consistencyFailEvent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}