{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudionode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudionode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioFilePlayerNode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMicNode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenBroadcastAudioNode"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioNode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioNode"}],"title":"HMSAudioNode","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSAudioNode","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSAudioNode"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioNode":{"role":"symbol","title":"HMSAudioNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioNode"}],"url":"\/documentation\/hmssdk\/hmsaudionode"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMicNode":{"role":"symbol","title":"HMSMicNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMicNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMicNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMicNode"}],"url":"\/documentation\/hmssdk\/hmsmicnode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioBufferPlayerNode":{"role":"symbol","title":"HMSAudioBufferPlayerNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioBufferPlayerNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioBufferPlayerNode"}],"url":"\/documentation\/hmssdk\/hmsaudiobufferplayernode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenBroadcastAudioNode":{"role":"symbol","title":"HMSScreenBroadcastAudioNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenBroadcastAudioNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenBroadcastAudioNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSScreenBroadcastAudioNode"}],"url":"\/documentation\/hmssdk\/hmsscreenbroadcastaudionode"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioFilePlayerNode":{"role":"symbol","title":"HMSAudioFilePlayerNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioFilePlayerNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioFilePlayerNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioFilePlayerNode"}],"url":"\/documentation\/hmssdk\/hmsaudiofileplayernode"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSAudioNode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSAudioNode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSAudioNode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferPlayerNode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioFilePlayerNode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMicNode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenBroadcastAudioNode"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioNode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioNode\/title","value":"HMSAudioNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioNode\/fragments","value":[{"kind":"identifier","text":"HMSAudioNode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMicNode\/title","value":"HMSMicNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMicNode\/fragments","value":[{"kind":"identifier","text":"HMSMicNode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferPlayerNode\/title","value":"HMSAudioBufferPlayerNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferPlayerNode\/fragments","value":[{"kind":"identifier","text":"HMSAudioBufferPlayerNode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenBroadcastAudioNode\/title","value":"HMSScreenBroadcastAudioNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenBroadcastAudioNode\/fragments","value":[{"kind":"identifier","text":"HMSScreenBroadcastAudioNode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioFilePlayerNode\/title","value":"HMSAudioFilePlayerNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioFilePlayerNode\/fragments","value":[{"kind":"identifier","text":"HMSAudioFilePlayerNode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}