{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"To join a room created, clients need to create a HMSConfig instance and use that instance to call "},{"type":"codeVoice","code":"join"},{"type":"text","text":" method of HMSSDK"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSConfig"}],"title":"HMSConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSConfig","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSConfig"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/authToken","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/captureNetworkQualityInPreview","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/metadata","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/roomID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/shouldSkipPIIEvents","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/userID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/userName"]}],"references":{"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/captureNetworkQualityInPreview":{"role":"symbol","title":"captureNetworkQualityInPreview","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureNetworkQualityInPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"if enabled, SDK will try to estimate the quality of the network when preview API is called."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/captureNetworkQualityInPreview","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureNetworkQualityInPreview"}],"url":"\/documentation\/hmssdk\/hmsconfig\/capturenetworkqualityinpreview"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)":{"deprecated":true,"role":"symbol","title":"init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"roomID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSkipPIIEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"endpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUserName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:"}],"url":"\/documentation\/hmssdk\/hmsconfig\/init(username:userid:roomid:authtoken:shouldskippiievents:metadata:endpoint:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/endpoint":{"role":"symbol","title":"endpoint","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"to override the default endpoint (advanced)"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/endpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endpoint"}],"url":"\/documentation\/hmssdk\/hmsconfig\/endpoint"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/userName":{"role":"symbol","title":"userName","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"the name that the user wants to be displayed while in the room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/userName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userName"}],"url":"\/documentation\/hmssdk\/hmsconfig\/username"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)":{"role":"symbol","title":"init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSkipPIIEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"endpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"captureNetworkQualityInPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUserName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:"}],"url":"\/documentation\/hmssdk\/hmsconfig\/init(username:authtoken:shouldskippiievents:metadata:endpoint:capturenetworkqualityinpreview:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/userID":{"role":"symbol","title":"userID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/userID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userID"}],"url":"\/documentation\/hmssdk\/hmsconfig\/userid"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig":{"role":"symbol","title":"HMSConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSConfig"}],"abstract":[{"type":"text","text":"To join a room created, clients need to create a HMSConfig instance and use that instance to call "},{"type":"codeVoice","code":"join"},{"type":"text","text":" method of HMSSDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSConfig"}],"url":"\/documentation\/hmssdk\/hmsconfig"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/authToken":{"role":"symbol","title":"authToken","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"the auth token to be used"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/authToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authToken"}],"url":"\/documentation\/hmssdk\/hmsconfig\/authtoken"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/roomID":{"role":"symbol","title":"roomID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/roomID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roomID"}],"url":"\/documentation\/hmssdk\/hmsconfig\/roomid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/shouldSkipPIIEvents":{"role":"symbol","title":"shouldSkipPIIEvents","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldSkipPIIEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/shouldSkipPIIEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldSkipPIIEvents"}],"url":"\/documentation\/hmssdk\/hmsconfig\/shouldskippiievents"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSConfig/metadata":{"role":"symbol","title":"metadata","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"any json string or metadata that can be passed while joining"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/metadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"url":"\/documentation\/hmssdk\/hmsconfig\/metadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/authToken","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/captureNetworkQualityInPreview","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/metadata","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/roomID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/shouldSkipPIIEvents","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/userID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/userName"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSConfig\/init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1captureNetworkQualityInPreview\/title","value":"captureNetworkQualityInPreview"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1captureNetworkQualityInPreview\/fragments","value":[{"kind":"identifier","text":"captureNetworkQualityInPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)\/title","value":"initWithUserName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1init(userName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserName:userID:roomID:authToken:shouldSkipPIIEvents:metadata:endpoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1endpoint\/title","value":"endpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1endpoint\/fragments","value":[{"kind":"identifier","text":"endpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1userName\/title","value":"userName"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1userName\/fragments","value":[{"kind":"identifier","text":"userName"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)\/title","value":"initWithUserName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1init(userName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserName:authToken:shouldSkipPIIEvents:metadata:endpoint:captureNetworkQualityInPreview:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1userID\/title","value":"userID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1userID\/fragments","value":[{"kind":"identifier","text":"userID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig\/title","value":"HMSConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig\/fragments","value":[{"kind":"identifier","text":"HMSConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1authToken\/title","value":"authToken"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1authToken\/fragments","value":[{"kind":"identifier","text":"authToken"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1roomID\/title","value":"roomID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1roomID\/fragments","value":[{"kind":"identifier","text":"roomID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1shouldSkipPIIEvents\/title","value":"shouldSkipPIIEvents"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1shouldSkipPIIEvents\/fragments","value":[{"kind":"identifier","text":"shouldSkipPIIEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1metadata\/title","value":"metadata"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSConfig~1metadata\/fragments","value":[{"kind":"identifier","text":"metadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}