{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsdefaultanalyticsservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsdefaultanalyticsservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/level","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/logger","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/shouldSkipPIIEvents"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/shared()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsService"}],"title":"HMSDefaultAnalyticsService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSDefaultAnalyticsService","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsService":{"role":"symbol","title":"HMSAnalyticsService","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsService"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsService"}],"url":"\/documentation\/hmssdk\/hmsanalyticsservice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService/logger":{"role":"symbol","title":"logger","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logger"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"HMSLogger","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSLogger"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logger"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/logger"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService/level":{"role":"symbol","title":"level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"level"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/level"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService":{"role":"symbol","title":"HMSDefaultAnalyticsService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsService"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService/shared()":{"role":"symbol","title":"shared()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/shared()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/shared()"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsService/shouldSkipPIIEvents":{"role":"symbol","title":"shouldSkipPIIEvents","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldSkipPIIEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/shouldSkipPIIEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldSkipPIIEvents"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticsservice\/shouldskippiievents"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSDefaultAnalyticsService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/level","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/logger","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/shouldSkipPIIEvents"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsService\/shared()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsService"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService\/title","value":"HMSAnalyticsService"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsService\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsService"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1logger\/title","value":"logger"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1logger\/fragments","value":[{"kind":"identifier","text":"logger"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1level\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1level\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService\/title","value":"HMSDefaultAnalyticsService"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService\/fragments","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsService"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1shared()\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1shared()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1shouldSkipPIIEvents\/title","value":"shouldSkipPIIEvents"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsService~1shouldSkipPIIEvents\/fragments","value":[{"kind":"identifier","text":"shouldSkipPIIEvents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}