{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/agent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/deviceID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/joinedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/peer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/room","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/templateId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/token","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/websocketEndpoint"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}],"title":"HMSDefaultAnalyticsEventFactory","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSDefaultAnalyticsEventFactory","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/joinedAt":{"role":"symbol","title":"joinedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/joinedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinedAt"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/joinedat"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/templateId":{"role":"symbol","title":"templateId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/templateId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateId"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/templateid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/deviceID":{"role":"symbol","title":"deviceID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/deviceID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceID"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/deviceid"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/room":{"role":"symbol","title":"room","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/room","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"room"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/room"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/token","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"token"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/token"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/frameworkInfo":{"role":"symbol","title":"frameworkInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/frameworkInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameworkInfo"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/frameworkinfo"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/agent":{"role":"symbol","title":"agent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"agent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/agent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"agent"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/agent"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAnalyticsEventFactory":{"role":"symbol","title":"HMSAnalyticsEventFactory","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}],"url":"\/documentation\/hmssdk\/hmsanalyticseventfactory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/peer":{"role":"symbol","title":"peer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/peer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peer"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/peer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory":{"role":"symbol","title":"HMSDefaultAnalyticsEventFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/endpoint":{"role":"symbol","title":"endpoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/endpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endpoint"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/endpoint"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSDefaultAnalyticsEventFactory/websocketEndpoint":{"role":"symbol","title":"websocketEndpoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketEndpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/websocketEndpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"websocketEndpoint"}],"url":"\/documentation\/hmssdk\/hmsdefaultanalyticseventfactory\/websocketendpoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSDefaultAnalyticsEventFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/agent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/deviceID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/joinedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/peer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/room","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/templateId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/token","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSDefaultAnalyticsEventFactory\/websocketEndpoint"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAnalyticsEventFactory"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1joinedAt\/title","value":"joinedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1joinedAt\/fragments","value":[{"kind":"identifier","text":"joinedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1templateId\/title","value":"templateId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1templateId\/fragments","value":[{"kind":"identifier","text":"templateId"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1deviceID\/title","value":"deviceID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1deviceID\/fragments","value":[{"kind":"identifier","text":"deviceID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1room\/title","value":"room"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1room\/fragments","value":[{"kind":"identifier","text":"room"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1token\/fragments","value":[{"kind":"identifier","text":"token"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1frameworkInfo\/title","value":"frameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1frameworkInfo\/fragments","value":[{"kind":"identifier","text":"frameworkInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1agent\/title","value":"agent"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1agent\/fragments","value":[{"kind":"identifier","text":"agent"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory\/title","value":"HMSAnalyticsEventFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAnalyticsEventFactory\/fragments","value":[{"kind":"identifier","text":"HMSAnalyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1peer\/title","value":"peer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1peer\/fragments","value":[{"kind":"identifier","text":"peer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory\/title","value":"HMSDefaultAnalyticsEventFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory\/fragments","value":[{"kind":"identifier","text":"HMSDefaultAnalyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1endpoint\/title","value":"endpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1endpoint\/fragments","value":[{"kind":"identifier","text":"endpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1websocketEndpoint\/title","value":"websocketEndpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSDefaultAnalyticsEventFactory~1websocketEndpoint\/fragments","value":[{"kind":"identifier","text":"websocketEndpoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}