{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorAction"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmserroraction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmserroraction"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/dataChannelSend","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/init","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/join","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/publish","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/subscribe","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/track"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorAction"}],"title":"HMSErrorAction","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSErrorAction","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSErrorAction"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/publish":{"role":"symbol","title":"HMSErrorAction.publish","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/publish","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionPublish"}],"url":"\/documentation\/hmssdk\/hmserroraction\/publish"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmserroraction\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/init":{"role":"symbol","title":"HMSErrorAction.init","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`init`"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionInit"}],"url":"\/documentation\/hmssdk\/hmserroraction\/init"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/subscribe":{"role":"symbol","title":"HMSErrorAction.subscribe","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/subscribe","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionSubscribe"}],"url":"\/documentation\/hmssdk\/hmserroraction\/subscribe"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/none":{"role":"symbol","title":"HMSErrorAction.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionNone"}],"url":"\/documentation\/hmssdk\/hmserroraction\/none"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/join":{"role":"symbol","title":"HMSErrorAction.join","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/join","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionJoin"}],"url":"\/documentation\/hmssdk\/hmserroraction\/join"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/dataChannelSend":{"role":"symbol","title":"HMSErrorAction.dataChannelSend","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataChannelSend"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/dataChannelSend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionDataChannelSend"}],"url":"\/documentation\/hmssdk\/hmserroraction\/datachannelsend"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/track":{"role":"symbol","title":"HMSErrorAction.track","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/track","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorActionTrack"}],"url":"\/documentation\/hmssdk\/hmserroraction\/track"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmserroraction\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmserroraction\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorAction":{"role":"symbol","title":"HMSErrorAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorAction"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorAction"}],"url":"\/documentation\/hmssdk\/hmserroraction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSErrorAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSErrorAction"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSErrorAction"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/dataChannelSend","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/init","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/join","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/publish","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/subscribe","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorAction\/track"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1publish\/title","value":"HMSErrorActionPublish"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1publish\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionPublish"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1init\/title","value":"HMSErrorActionInit"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1init\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionInit"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1subscribe\/title","value":"HMSErrorActionSubscribe"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1subscribe\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionSubscribe"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1none\/title","value":"HMSErrorActionNone"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1none\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionNone"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1join\/title","value":"HMSErrorActionJoin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1join\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionJoin"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1dataChannelSend\/title","value":"HMSErrorActionDataChannelSend"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1dataChannelSend\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionDataChannelSend"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1track\/title","value":"HMSErrorActionTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction~1track\/fragments","value":[{"kind":"identifier","text":"HMSErrorActionTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction\/title","value":"HMSErrorAction"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorAction\/fragments","value":[{"kind":"identifier","text":"HMSErrorAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}