{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorFactory"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmserrorfactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmserrorfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/alreadyJoined(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/audiovideoSubsystemFailure(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/cantAccessCaptureDevice(action:deviceInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/codecChangeNotPermitted(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/createAnswerFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/createOfferFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/endpointUnreachable(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/genericTrack(action:errorInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/httpError(code:action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/iceDisconnected(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/iceFailure(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/invalidEndpointUrl(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/invalidTokenFormat(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/jsonParsingFailed(action:jsonMessage:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/micCaptureFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/notConnected(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/nothingToReturn(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/nsError(error:params:isTerminal:message:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/peerMetadataMissing(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/rtcTrackMissing(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/serverErrors(code:action:serverError:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/setLocalDescriptionFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/setRemoteDescriptionFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/trackMetadataMissing(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/unknown(action:errorInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/unknownSoft(action:errorInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/websocketConnectionLost(action:params:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorFactory"}],"title":"HMSErrorFactory","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSErrorFactory","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSErrorFactory"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/httpError(code:action:params:)":{"role":"symbol","title":"httpError(code:action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/httpError(code:action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"httpErrorWithCode:action:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/httperror(code:action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/invalidEndpointUrl(action:params:)":{"role":"symbol","title":"invalidEndpointUrl(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidEndpointUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/invalidEndpointUrl(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidEndpointUrlWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/invalidendpointurl(action:params:)"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/nsError(error:params:isTerminal:message:)":{"role":"symbol","title":"nsError(error:params:isTerminal:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nsError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"isTerminal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/nsError(error:params:isTerminal:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nsErrorWithError:params:isTerminal:message:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/nserror(error:params:isterminal:message:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/alreadyJoined(action:params:)":{"role":"symbol","title":"alreadyJoined(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyJoined"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/alreadyJoined(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alreadyJoinedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/alreadyjoined(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/peerMetadataMissing(action:params:)":{"role":"symbol","title":"peerMetadataMissing(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerMetadataMissing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/peerMetadataMissing(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerMetadataMissingWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/peermetadatamissing(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/iceDisconnected(action:params:)":{"role":"symbol","title":"iceDisconnected(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"iceDisconnected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/iceDisconnected(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iceDisconnectedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/icedisconnected(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/notConnected(action:params:)":{"role":"symbol","title":"notConnected(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notConnected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/notConnected(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notConnectedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/notconnected(action:params:)"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/unknownSoft(action:errorInfo:params:)":{"role":"symbol","title":"unknownSoft(action:errorInfo:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownSoft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/unknownSoft(action:errorInfo:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unknownSoftWithAction:errorInfo:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/unknownsoft(action:errorinfo:params:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/codecChangeNotPermitted(action:params:)":{"role":"symbol","title":"codecChangeNotPermitted(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecChangeNotPermitted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/codecChangeNotPermitted(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecChangeNotPermittedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/codecchangenotpermitted(action:params:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/trackMetadataMissing(action:params:)":{"role":"symbol","title":"trackMetadataMissing(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackMetadataMissing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/trackMetadataMissing(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackMetadataMissingWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/trackmetadatamissing(action:params:)"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/serverErrors(code:action:serverError:params:)":{"role":"symbol","title":"serverErrors(code:action:serverError:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverErrors"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"serverError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/serverErrors(code:action:serverError:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverErrorsWithCode:action:serverError:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/servererrors(code:action:servererror:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/invalidTokenFormat(action:params:)":{"role":"symbol","title":"invalidTokenFormat(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidTokenFormat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/invalidTokenFormat(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidTokenFormatWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/invalidtokenformat(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/setRemoteDescriptionFailed(action:params:)":{"role":"symbol","title":"setRemoteDescriptionFailed(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteDescriptionFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/setRemoteDescriptionFailed(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteDescriptionFailedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/setremotedescriptionfailed(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/cantAccessCaptureDevice(action:deviceInfo:params:)":{"role":"symbol","title":"cantAccessCaptureDevice(action:deviceInfo:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cantAccessCaptureDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/cantAccessCaptureDevice(action:deviceInfo:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cantAccessCaptureDeviceWithAction:deviceInfo:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/cantaccesscapturedevice(action:deviceinfo:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory":{"role":"symbol","title":"HMSErrorFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSErrorFactory"}],"url":"\/documentation\/hmssdk\/hmserrorfactory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/unknown(action:errorInfo:params:)":{"role":"symbol","title":"unknown(action:errorInfo:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/unknown(action:errorInfo:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unknownWithAction:errorInfo:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/unknown(action:errorinfo:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/jsonParsingFailed(action:jsonMessage:params:)":{"role":"symbol","title":"jsonParsingFailed(action:jsonMessage:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonParsingFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jsonMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/jsonParsingFailed(action:jsonMessage:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jsonParsingFailedWithAction:jsonMessage:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/jsonparsingfailed(action:jsonmessage:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/iceFailure(action:params:)":{"role":"symbol","title":"iceFailure(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"iceFailure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/iceFailure(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iceFailureWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/icefailure(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/createOfferFailed(action:params:)":{"role":"symbol","title":"createOfferFailed(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOfferFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/createOfferFailed(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOfferFailedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/createofferfailed(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/genericTrack(action:errorInfo:params:)":{"role":"symbol","title":"genericTrack(action:errorInfo:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/genericTrack(action:errorInfo:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"genericTrackWithAction:errorInfo:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/generictrack(action:errorinfo:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/audiovideoSubsystemFailure(action:params:)":{"role":"symbol","title":"audiovideoSubsystemFailure(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audiovideoSubsystemFailure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/audiovideoSubsystemFailure(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audiovideoSubsystemFailureWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/audiovideosubsystemfailure(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/endpointUnreachable(action:params:)":{"role":"symbol","title":"endpointUnreachable(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpointUnreachable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/endpointUnreachable(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endpointUnreachableWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/endpointunreachable(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/websocketConnectionLost(action:params:)":{"role":"symbol","title":"websocketConnectionLost(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketConnectionLost"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/websocketConnectionLost(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"websocketConnectionLostWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/websocketconnectionlost(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/createAnswerFailed(action:params:)":{"role":"symbol","title":"createAnswerFailed(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createAnswerFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/createAnswerFailed(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createAnswerFailedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/createanswerfailed(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/nothingToReturn(action:params:)":{"role":"symbol","title":"nothingToReturn(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nothingToReturn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/nothingToReturn(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nothingToReturnWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/nothingtoreturn(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/setLocalDescriptionFailed(action:params:)":{"role":"symbol","title":"setLocalDescriptionFailed(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalDescriptionFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/setLocalDescriptionFailed(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLocalDescriptionFailedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/setlocaldescriptionfailed(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/micCaptureFailed(action:params:)":{"role":"symbol","title":"micCaptureFailed(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"micCaptureFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/micCaptureFailed(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"micCaptureFailedWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/miccapturefailed(action:params:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/init"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSErrorFactory/rtcTrackMissing(action:params:)":{"role":"symbol","title":"rtcTrackMissing(action:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcTrackMissing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSErrorAction","preciseIdentifier":"c:@M@HMSSDK@E@HMSErrorAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/rtcTrackMissing(action:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcTrackMissingWithAction:params:"}],"url":"\/documentation\/hmssdk\/hmserrorfactory\/rtctrackmissing(action:params:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSErrorFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSErrorFactory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSErrorFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/alreadyJoined(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/audiovideoSubsystemFailure(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/cantAccessCaptureDevice(action:deviceInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/codecChangeNotPermitted(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/createAnswerFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/createOfferFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/endpointUnreachable(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/genericTrack(action:errorInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/httpError(code:action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/iceDisconnected(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/iceFailure(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/init","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/invalidEndpointUrl(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/invalidTokenFormat(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/jsonParsingFailed(action:jsonMessage:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/micCaptureFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/notConnected(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/nothingToReturn(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/nsError(error:params:isTerminal:message:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/peerMetadataMissing(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/rtcTrackMissing(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/serverErrors(code:action:serverError:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/setLocalDescriptionFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/setRemoteDescriptionFailed(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/trackMetadataMissing(action:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/unknown(action:errorInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/unknownSoft(action:errorInfo:params:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSErrorFactory\/websocketConnectionLost(action:params:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSErrorFactory"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1httpError(code:action:params:)\/title","value":"httpErrorWithCode:action:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1httpError(code:action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"httpErrorWithCode:action:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1invalidEndpointUrl(action:params:)\/title","value":"invalidEndpointUrlWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1invalidEndpointUrl(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidEndpointUrlWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1nsError(error:params:isTerminal:message:)\/title","value":"nsErrorWithError:params:isTerminal:message:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1nsError(error:params:isTerminal:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nsErrorWithError:params:isTerminal:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1alreadyJoined(action:params:)\/title","value":"alreadyJoinedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1alreadyJoined(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"alreadyJoinedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1peerMetadataMissing(action:params:)\/title","value":"peerMetadataMissingWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1peerMetadataMissing(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerMetadataMissingWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1iceDisconnected(action:params:)\/title","value":"iceDisconnectedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1iceDisconnected(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"iceDisconnectedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1notConnected(action:params:)\/title","value":"notConnectedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1notConnected(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notConnectedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1unknownSoft(action:errorInfo:params:)\/title","value":"unknownSoftWithAction:errorInfo:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1unknownSoft(action:errorInfo:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unknownSoftWithAction:errorInfo:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1codecChangeNotPermitted(action:params:)\/title","value":"codecChangeNotPermittedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1codecChangeNotPermitted(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"codecChangeNotPermittedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1trackMetadataMissing(action:params:)\/title","value":"trackMetadataMissingWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1trackMetadataMissing(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackMetadataMissingWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1serverErrors(code:action:serverError:params:)\/title","value":"serverErrorsWithCode:action:serverError:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1serverErrors(code:action:serverError:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serverErrorsWithCode:action:serverError:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1invalidTokenFormat(action:params:)\/title","value":"invalidTokenFormatWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1invalidTokenFormat(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidTokenFormatWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1setRemoteDescriptionFailed(action:params:)\/title","value":"setRemoteDescriptionFailedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1setRemoteDescriptionFailed(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteDescriptionFailedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1cantAccessCaptureDevice(action:deviceInfo:params:)\/title","value":"cantAccessCaptureDeviceWithAction:deviceInfo:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1cantAccessCaptureDevice(action:deviceInfo:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cantAccessCaptureDeviceWithAction:deviceInfo:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory\/title","value":"HMSErrorFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory\/fragments","value":[{"kind":"identifier","text":"HMSErrorFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1unknown(action:errorInfo:params:)\/title","value":"unknownWithAction:errorInfo:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1unknown(action:errorInfo:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unknownWithAction:errorInfo:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1jsonParsingFailed(action:jsonMessage:params:)\/title","value":"jsonParsingFailedWithAction:jsonMessage:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1jsonParsingFailed(action:jsonMessage:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"jsonParsingFailedWithAction:jsonMessage:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1iceFailure(action:params:)\/title","value":"iceFailureWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1iceFailure(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"iceFailureWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1createOfferFailed(action:params:)\/title","value":"createOfferFailedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1createOfferFailed(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOfferFailedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1genericTrack(action:errorInfo:params:)\/title","value":"genericTrackWithAction:errorInfo:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1genericTrack(action:errorInfo:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"genericTrackWithAction:errorInfo:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1audiovideoSubsystemFailure(action:params:)\/title","value":"audiovideoSubsystemFailureWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1audiovideoSubsystemFailure(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audiovideoSubsystemFailureWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1endpointUnreachable(action:params:)\/title","value":"endpointUnreachableWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1endpointUnreachable(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endpointUnreachableWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1websocketConnectionLost(action:params:)\/title","value":"websocketConnectionLostWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1websocketConnectionLost(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"websocketConnectionLostWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1createAnswerFailed(action:params:)\/title","value":"createAnswerFailedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1createAnswerFailed(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createAnswerFailedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1nothingToReturn(action:params:)\/title","value":"nothingToReturnWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1nothingToReturn(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nothingToReturnWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1setLocalDescriptionFailed(action:params:)\/title","value":"setLocalDescriptionFailedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1setLocalDescriptionFailed(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalDescriptionFailedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1micCaptureFailed(action:params:)\/title","value":"micCaptureFailedWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1micCaptureFailed(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"micCaptureFailedWithAction:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1rtcTrackMissing(action:params:)\/title","value":"rtcTrackMissingWithAction:params:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSErrorFactory~1rtcTrackMissing(action:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcTrackMissingWithAction:params:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}