{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSFrameCapturePlugin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsframecaptureplugin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsframecaptureplugin"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/capture()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/process(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSFrameCapturePlugin"}],"title":"HMSFrameCapturePlugin","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSFrameCapturePlugin","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSFrameCapturePlugin/capture()":{"role":"symbol","title":"capture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"capture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/capture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"capture"}],"url":"\/documentation\/hmssdk\/hmsframecaptureplugin\/capture()"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSFrameCapturePlugin/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsframecaptureplugin\/init"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoPlugin":{"role":"symbol","title":"HMSVideoPlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoPlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoPlugin"}],"url":"\/documentation\/hmssdk\/hmsvideoplugin"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSFrameCapturePlugin/process(_:)":{"role":"symbol","title":"process(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/process(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"process:"}],"url":"\/documentation\/hmssdk\/hmsframecaptureplugin\/process(_:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSFrameCapturePlugin":{"role":"symbol","title":"HMSFrameCapturePlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSFrameCapturePlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}],"url":"\/documentation\/hmssdk\/hmsframecaptureplugin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSFrameCapturePlugin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/capture()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/init","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSFrameCapturePlugin\/process(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSFrameCapturePlugin"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin","text":"HMSVideoPlugin"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin~1capture()\/title","value":"capture"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin~1capture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"capture"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/title","value":"HMSVideoPlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/fragments","value":[{"kind":"identifier","text":"HMSVideoPlugin"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin~1process(_:)\/title","value":"process:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin~1process(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"process:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin\/title","value":"HMSFrameCapturePlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSFrameCapturePlugin\/fragments","value":[{"kind":"identifier","text":"HMSFrameCapturePlugin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}