{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsplaybackdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsplaybackdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/onPlaybackFailure(error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/playerDidChangeResolution(videoSize:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"title":"HMSHLSPlaybackDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@HMSSDK@objc(pl)HMSHLSPlaybackDelegate","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSPlaybackDelegate":{"role":"symbol","title":"HMSHLSPlaybackDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"url":"\/documentation\/hmssdk\/hmshlsplaybackdelegate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSPlaybackDelegate/onPlaybackFailure(error:)":{"role":"symbol","title":"onPlaybackFailure(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackFailure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/onPlaybackFailure(error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPlaybackFailureWithError:"}],"url":"\/documentation\/hmssdk\/hmshlsplaybackdelegate\/onplaybackfailure(error:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSPlaybackDelegate/playerDidChangeResolution(videoSize:)":{"role":"symbol","title":"playerDidChangeResolution(videoSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerDidChangeResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Player has switched to different resolution layer of HLS stream - due to improved\/degraded network condition or when user manually picks a different resolution"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/playerDidChangeResolution(videoSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"}],"url":"\/documentation\/hmssdk\/hmshlsplaybackdelegate\/playerdidchangeresolution(videosize:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HMSHLSPlaybackDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/onPlaybackFailure(error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate\/playerDidChangeResolution(videoSize:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate\/title","value":"HMSHLSPlaybackDelegate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate\/fragments","value":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate~1onPlaybackFailure(error:)\/title","value":"onPlaybackFailureWithError:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate~1onPlaybackFailure(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackFailureWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate~1playerDidChangeResolution(videoSize:)\/title","value":"playerDidChangeResolutionWithVideoSize:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate~1playerDidChangeResolution(videoSize:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerDidChangeResolutionWithVideoSize:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}