{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsstatsmonitor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsstatsmonitor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/bitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/bufferedDuration","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/bytesDownloaded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/delegate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/distanceFromLiveEdge","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/droppedFrames","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/estimatedBandwidth","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/videoSize","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/watchDuration"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/observeValue(forKeyPath:of:change:context:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"title":"HMSHLSStatsMonitor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSHLSStatsMonitor","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/estimatedBandwidth":{"role":"symbol","title":"estimatedBandwidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimatedBandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The network bandwidth estimated by the player. This is the bitrate observed by the player in current network conditions"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/estimatedBandwidth","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/estimatedbandwidth"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/distanceFromLiveEdge":{"role":"symbol","title":"distanceFromLiveEdge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceFromLiveEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The distance of current playback position from the live edge of HLS stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/distanceFromLiveEdge","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/distancefromliveedge"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/bitrate":{"role":"symbol","title":"bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The bitrate of current HLS stream (layer) indicated by the server"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/bitrate","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/bitrate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/droppedFrames":{"role":"symbol","title":"droppedFrames","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"droppedFrames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total number of frames dropped till this moment"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/droppedFrames","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/droppedframes"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/bytesDownloaded":{"role":"symbol","title":"bytesDownloaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesDownloaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Total number of bytes downloaded till this moment"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/bytesDownloaded","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/bytesdownloaded"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor":{"role":"symbol","title":"HMSHLSStatsMonitor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"url":"\/documentation\/hmssdk\/hmshlsstatsmonitor"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/bufferedDuration":{"role":"symbol","title":"bufferedDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferedDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The duration of forward buffer that player has downloaded and ready to play"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/bufferedDuration","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/bufferedduration"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/observeValue(forKeyPath:of:change:context:)":{"role":"symbol","title":"observeValue(forKeyPath:of:change:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/observeValue(forKeyPath:of:change:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/observevalue(forkeypath:of:change:context:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSPlaybackDelegate","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSHLSPlaybackDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/delegate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/watchDuration":{"role":"symbol","title":"watchDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"watchDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"Total duration that the user has watched the stream in milliseconds (includes any rewatch time)"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/watchDuration","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/watchduration"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/videoSize":{"role":"symbol","title":"videoSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The resolution of the HLS stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/videoSize","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/videosize"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSHLSStatsMonitor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/observeValue(forKeyPath:of:change:context:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStatsMonitor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor\/title","value":"HMSHLSStatsMonitor"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor\/fragments","value":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor~1observeValue(forKeyPath:of:change:context:)\/title","value":"observeValueForKeyPath:ofObject:change:context:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor~1observeValue(forKeyPath:of:change:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}