{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSIOSurfaceServer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsiosurfaceserver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsiosurfaceserver"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/init(groupName:sdkId:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/delegate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/isSharingSurface","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/sharedSurface"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/cleanup()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSIOSurfaceServer"}],"title":"HMSIOSurfaceServer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSIOSurfaceServer","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSIOSurfaceServer"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSIOSurfaceServer/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSScreenVideoBufferReceiver","preciseIdentifier":"c:objc(pl)HMSScreenVideoBufferReceiver"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/hmssdk\/hmsiosurfaceserver\/delegate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSIOSurfaceServer/init(groupName:sdkId:)":{"role":"symbol","title":"init(groupName:sdkId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sdkId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/init(groupName:sdkId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithGroupName:sdkId:"}],"url":"\/documentation\/hmssdk\/hmsiosurfaceserver\/init(groupname:sdkid:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSIOSurfaceServer":{"role":"symbol","title":"HMSIOSurfaceServer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSIOSurfaceServer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSIOSurfaceServer"}],"url":"\/documentation\/hmssdk\/hmsiosurfaceserver"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSIOSurfaceServer/cleanup()":{"role":"symbol","title":"cleanup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/cleanup()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanup"}],"url":"\/documentation\/hmssdk\/hmsiosurfaceserver\/cleanup()"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSIOSurfaceServer/sharedSurface":{"role":"symbol","title":"sharedSurface","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedSurface"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IOSurfaceRef","preciseIdentifier":"c:@T@IOSurfaceRef"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/sharedSurface","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedSurface"}],"url":"\/documentation\/hmssdk\/hmsiosurfaceserver\/sharedsurface"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSIOSurfaceServer/isSharingSurface":{"role":"symbol","title":"isSharingSurface","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSharingSurface"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/isSharingSurface","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isSharingSurface"}],"url":"\/documentation\/hmssdk\/hmsiosurfaceserver\/issharingsurface"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSIOSurfaceServer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSIOSurfaceServer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSIOSurfaceServer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/delegate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/isSharingSurface","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/sharedSurface"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/cleanup()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSIOSurfaceServer\/init(groupName:sdkId:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSIOSurfaceServer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1init(groupName:sdkId:)\/title","value":"initWithGroupName:sdkId:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1init(groupName:sdkId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGroupName:sdkId:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer\/title","value":"HMSIOSurfaceServer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer\/fragments","value":[{"kind":"identifier","text":"HMSIOSurfaceServer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1cleanup()\/title","value":"cleanup"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1cleanup()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanup"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1sharedSurface\/title","value":"sharedSurface"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1sharedSurface\/fragments","value":[{"kind":"identifier","text":"sharedSurface"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1isSharingSurface\/title","value":"isSharingSurface"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSIOSurfaceServer~1isSharingSurface\/fragments","value":[{"kind":"identifier","text":"isSharingSurface"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}