{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides interactivity features."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"title":"HMSInteractivityCenter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/polls"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/add(response:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/addPollUpdateListner(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/create(poll:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollList(state:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollQuestions(poll:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollResult(for:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchResponses(for:offset:count:myResponseOnly:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/quickStartPoll(with:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/setPollQuestions(poll:questions:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/start(poll:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/stop(poll:completion:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/HMSPollListener"]}],"references":{"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/create(poll:completion:)":{"role":"symbol","title":"create(poll:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSAnalyticsEventTransport.h@T@HMSOperationStatusHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/create(poll:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithPoll:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/create(poll:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/HMSPollListener":{"role":"symbol","title":"HMSInteractivityCenter.HMSPollListener","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollListener"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/HMSPollListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollListener"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/hmspolllistener"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/add(response:completion:)":{"role":"symbol","title":"add(response:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResponseBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponseBuilder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSPollQuestionResponseResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponseResult"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Adds a poll response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/add(response:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addWithResponse:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/add(response:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/polls":{"role":"symbol","title":"polls","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polls"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The array of polls managed by the interactivity center."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/polls","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"polls"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/polls"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/fetchPollList(state:completion:)":{"role":"symbol","title":"fetchPollList(state:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPollList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollState","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Fetches the list of polls based on the given poll state."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollList(state:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchPollListWithState:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/fetchpolllist(state:completion:)"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter":{"role":"symbol","title":"HMSInteractivityCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Provides interactivity features."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSInteractivityCenter"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/fetchResponses(for:offset:count:myResponseOnly:completion:)":{"role":"symbol","title":"fetchResponses(for:offset:count:myResponseOnly:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchResponses"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"myResponseOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSPollQuestionResponse","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponse"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Fetches the responses for a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchResponses(for:offset:count:myResponseOnly:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchResponsesFor:offset:count:myResponseOnly:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/fetchresponses(for:offset:count:myresponseonly:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/quickStartPoll(with:completion:)":{"role":"symbol","title":"quickStartPoll(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"quickStartPoll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Creates a poll, sets the poll questions and starts it with the provided poll builder."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/quickStartPoll(with:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quickStartPollWith:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/quickstartpoll(with:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/fetchPollQuestions(poll:completion:)":{"role":"symbol","title":"fetchPollQuestions(poll:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPollQuestions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Fetches the questions for a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollQuestions(poll:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchPollQuestionsWithPoll:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/fetchpollquestions(poll:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/addPollUpdateListner(_:)":{"role":"symbol","title":"addPollUpdateListner(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPollUpdateListner"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollListener","preciseIdentifier":"s:6HMSSDK22HMSInteractivityCenterC15HMSPollListenera"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds a poll update listener to receive poll updates."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/addPollUpdateListner(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPollUpdateListner:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/addpollupdatelistner(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/fetchPollResult(for:completion:)":{"role":"symbol","title":"fetchPollResult(for:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPollResult"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Fetches the result of a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollResult(for:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchPollResultFor:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/fetchpollresult(for:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/start(poll:completion:)":{"role":"symbol","title":"start(poll:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSAnalyticsEventTransport.h@T@HMSOperationStatusHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/start(poll:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithPoll:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/start(poll:completion:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/setPollQuestions(poll:questions:completion:)":{"role":"symbol","title":"setPollQuestions(poll:questions:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPollQuestions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSAnalyticsEventTransport.h@T@HMSOperationStatusHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the questions for a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/setPollQuestions(poll:questions:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/setpollquestions(poll:questions:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/stop(poll:completion:)":{"role":"symbol","title":"stop(poll:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPoll","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPoll"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Stops a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/stop(poll:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopWithPoll:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/stop(poll:completion:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSInteractivityCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/polls"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/add(response:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/addPollUpdateListner(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/create(poll:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollList(state:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollQuestions(poll:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchPollResult(for:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/fetchResponses(for:offset:count:myResponseOnly:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/quickStartPoll(with:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/start(poll:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/stop(poll:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1create(poll:completion:)\/title","value":"createWithPoll:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1create(poll:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createWithPoll:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1add(response:completion:)\/title","value":"addWithResponse:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1add(response:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithResponse:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1polls\/title","value":"polls"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1polls\/fragments","value":[{"kind":"identifier","text":"polls"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchPollList(state:completion:)\/title","value":"fetchPollListWithState:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchPollList(state:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPollListWithState:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/title","value":"HMSInteractivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/fragments","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchResponses(for:offset:count:myResponseOnly:completion:)\/title","value":"fetchResponsesFor:offset:count:myResponseOnly:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchResponses(for:offset:count:myResponseOnly:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchResponsesFor:offset:count:myResponseOnly:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1quickStartPoll(with:completion:)\/title","value":"quickStartPollWith:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1quickStartPoll(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"quickStartPollWith:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchPollQuestions(poll:completion:)\/title","value":"fetchPollQuestionsWithPoll:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchPollQuestions(poll:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPollQuestionsWithPoll:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1addPollUpdateListner(_:)\/title","value":"addPollUpdateListner:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1addPollUpdateListner(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPollUpdateListner:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchPollResult(for:completion:)\/title","value":"fetchPollResultFor:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1fetchPollResult(for:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPollResultFor:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1start(poll:completion:)\/title","value":"startWithPoll:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1start(poll:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithPoll:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1stop(poll:completion:)\/title","value":"stopWithPoll:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1stop(poll:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopWithPoll:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}