{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSJoinParameters"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsjoinparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsjoinparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/authToken","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/enableServerSideDegradation","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/enableSimulcast","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerCustomMetadata","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerName","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/skipOffer"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSJoinParameters"}],"title":"HMSJoinParameters","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSJoinParameters","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSJoinParameters"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/enableServerSideDegradation":{"role":"symbol","title":"enableServerSideDegradation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableServerSideDegradation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/enableServerSideDegradation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableServerSideDegradation"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/enableserversidedegradation"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/authToken":{"role":"symbol","title":"authToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/authToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authToken"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/authtoken"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/frameworkInfo":{"role":"symbol","title":"frameworkInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/frameworkInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameworkInfo"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/frameworkinfo"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/enableSimulcast":{"role":"symbol","title":"enableSimulcast","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSimulcast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/enableSimulcast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableSimulcast"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/enablesimulcast"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/peerCustomMetadata":{"role":"symbol","title":"peerCustomMetadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerCustomMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerCustomMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerCustomMetadata"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/peercustommetadata"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters":{"role":"symbol","title":"HMSJoinParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSJoinParameters"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSJoinParameters"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/peerId":{"role":"symbol","title":"peerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerId"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/peerid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/endpoint":{"role":"symbol","title":"endpoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/endpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endpoint"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/endpoint"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/skipOffer":{"role":"symbol","title":"skipOffer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipOffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/skipOffer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"skipOffer"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/skipoffer"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSJoinParameters/peerName":{"role":"symbol","title":"peerName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerName"}],"url":"\/documentation\/hmssdk\/hmsjoinparameters\/peername"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSJoinParameters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSJoinParameters"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSJoinParameters"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/authToken","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/enableServerSideDegradation","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/enableSimulcast","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/endpoint","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerCustomMetadata","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/peerName","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSJoinParameters\/skipOffer"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSJoinParameters"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1enableServerSideDegradation\/title","value":"enableServerSideDegradation"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1enableServerSideDegradation\/fragments","value":[{"kind":"identifier","text":"enableServerSideDegradation"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1authToken\/title","value":"authToken"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1authToken\/fragments","value":[{"kind":"identifier","text":"authToken"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1frameworkInfo\/title","value":"frameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1frameworkInfo\/fragments","value":[{"kind":"identifier","text":"frameworkInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1enableSimulcast\/title","value":"enableSimulcast"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1enableSimulcast\/fragments","value":[{"kind":"identifier","text":"enableSimulcast"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1peerCustomMetadata\/title","value":"peerCustomMetadata"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1peerCustomMetadata\/fragments","value":[{"kind":"identifier","text":"peerCustomMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters\/title","value":"HMSJoinParameters"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters\/fragments","value":[{"kind":"identifier","text":"HMSJoinParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1peerId\/title","value":"peerId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1peerId\/fragments","value":[{"kind":"identifier","text":"peerId"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1endpoint\/title","value":"endpoint"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1endpoint\/fragments","value":[{"kind":"identifier","text":"endpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1skipOffer\/title","value":"skipOffer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1skipOffer\/fragments","value":[{"kind":"identifier","text":"skipOffer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1peerName\/title","value":"peerName"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSJoinParameters~1peerName\/fragments","value":[{"kind":"identifier","text":"peerName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}