{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/error","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/off","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/verbose","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLogLevel"}],"title":"HMSLogLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSLogLevel","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSLogLevel"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel":{"role":"symbol","title":"HMSLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLogLevel"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLogLevel"}],"url":"\/documentation\/hmssdk\/hmsloglevel"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsloglevel\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsloglevel\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsloglevel\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/error":{"role":"symbol","title":"HMSLogLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLogLevelError"}],"url":"\/documentation\/hmssdk\/hmsloglevel\/error"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/off":{"role":"symbol","title":"HMSLogLevel.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLogLevelOff"}],"url":"\/documentation\/hmssdk\/hmsloglevel\/off"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/warning":{"role":"symbol","title":"HMSLogLevel.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLogLevelWarning"}],"url":"\/documentation\/hmssdk\/hmsloglevel\/warning"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLogLevel/verbose":{"role":"symbol","title":"HMSLogLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLogLevelVerbose"}],"url":"\/documentation\/hmssdk\/hmsloglevel\/verbose"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSLogLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSLogLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSLogLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/error","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/off","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/verbose","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLogLevel\/warning"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel\/title","value":"HMSLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel\/fragments","value":[{"kind":"identifier","text":"HMSLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1error\/title","value":"HMSLogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1error\/fragments","value":[{"kind":"identifier","text":"HMSLogLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1off\/title","value":"HMSLogLevelOff"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1off\/fragments","value":[{"kind":"identifier","text":"HMSLogLevelOff"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1warning\/title","value":"HMSLogLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1warning\/fragments","value":[{"kind":"identifier","text":"HMSLogLevelWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1verbose\/title","value":"HMSLogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLogLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"HMSLogLevelVerbose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}