{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalScreenTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalscreentrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalscreentrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack\/didReceiveVideoData(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalScreenTrack"}],"title":"HMSLocalScreenTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSLocalScreenTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSLocalScreenTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalScreenTrack/didReceiveVideoData(_:)":{"role":"symbol","title":"didReceiveVideoData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveVideoData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack\/didReceiveVideoData(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveVideoData:"}],"url":"\/documentation\/hmssdk\/hmslocalscreentrack\/didreceivevideodata(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalScreenTrack":{"role":"symbol","title":"HMSLocalScreenTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalScreenTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalScreenTrack"}],"url":"\/documentation\/hmssdk\/hmslocalscreentrack"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack":{"role":"symbol","title":"HMSVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsvideotrack"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(pl)_HMSScreenVideoBufferReceiver":{"type":"unresolvable","title":"_HMSScreenVideoBufferReceiver","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)_HMSScreenVideoBufferReceiver"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSLocalScreenTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSLocalScreenTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSLocalScreenTrack"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack\/didReceiveVideoData(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)_HMSScreenVideoBufferReceiver"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalScreenTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack","text":"HMSVideoTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalScreenTrack~1didReceiveVideoData(_:)\/title","value":"didReceiveVideoData:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalScreenTrack~1didReceiveVideoData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveVideoData:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalScreenTrack\/title","value":"HMSLocalScreenTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalScreenTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalScreenTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/title","value":"HMSVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}