{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/settings"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/captureImageAtMaxSupportedResolution(withFlash:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/modifyCaptureDevice(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/setFocus(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/setMute(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/switchCamera()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/switchCamera(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"title":"HMSLocalVideoTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSLocalVideoTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/setFocus(_:)":{"role":"symbol","title":"setFocus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFocus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/setFocus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFocus:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/setfocus(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/modifyCaptureDevice(_:)":{"role":"symbol","title":"modifyCaptureDevice(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyCaptureDevice"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/modifyCaptureDevice(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/modifycapturedevice(_:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack":{"role":"symbol","title":"HMSVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsvideotrack"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack":{"role":"symbol","title":"HMSLocalVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/settings":{"role":"symbol","title":"settings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrackSettings","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/settings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"settings"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/settings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/switchCamera(_:)":{"role":"symbol","title":"switchCamera(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCamera"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/switchCamera(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchCamera:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/switchcamera(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/captureImageAtMaxSupportedResolution(withFlash:completion:)":{"role":"symbol","title":"captureImageAtMaxSupportedResolution(withFlash:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFlash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/captureImageAtMaxSupportedResolution(withFlash:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/captureimageatmaxsupportedresolution(withflash:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/setMute(_:)":{"role":"symbol","title":"setMute(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMute"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/setMute(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMute:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/setmute(_:)"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/switchCamera()":{"role":"symbol","title":"switchCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCamera"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/switchCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchCamera"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/switchcamera()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/settings"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/captureImageAtMaxSupportedResolution(withFlash:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/modifyCaptureDevice(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/setFocus(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/setMute(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/switchCamera()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/switchCamera(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack","text":"HMSVideoTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1setFocus(_:)\/title","value":"setFocus:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1setFocus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFocus:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1modifyCaptureDevice(_:)\/title","value":"modifyCaptureDeviceUsingBlock:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1modifyCaptureDevice(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/title","value":"HMSVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1settings\/title","value":"settings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1settings\/fragments","value":[{"kind":"identifier","text":"settings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1switchCamera(_:)\/title","value":"switchCamera:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1switchCamera(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchCamera:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1captureImageAtMaxSupportedResolution(withFlash:completion:)\/title","value":"captureImageAtMaxSupportedResolutionWithFlash:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1captureImageAtMaxSupportedResolution(withFlash:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1setMute(_:)\/title","value":"setMute:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1setMute(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMute:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1switchCamera()\/title","value":"switchCamera"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1switchCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchCamera"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}