{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsnetworkhealthconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsnetworkhealthconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/scoreMap","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/timeout","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/jsonDictionary()"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/fromJSONDictionary(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"title":"HMSNetworkHealthConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSNetworkHealthConfig","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig/fromJSONDictionary(_:)":{"role":"symbol","title":"fromJSONDictionary(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromJSONDictionary"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/fromJSONDictionary(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromJSONDictionary:"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig\/fromjsondictionary(_:)"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/url","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig\/url"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig/scoreMap":{"role":"symbol","title":"scoreMap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"HMSScoreMap","preciseIdentifier":"c:objc(cs)HMSScoreMap"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/scoreMap","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scoreMap"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig\/scoremap"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig/timeout":{"role":"symbol","title":"timeout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/timeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timeout"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig\/timeout"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig/jsonDictionary()":{"role":"symbol","title":"jsonDictionary()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonDictionary"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/jsonDictionary()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONDictionary"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig\/jsondictionary()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig":{"role":"symbol","title":"HMSNetworkHealthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSNetworkHealthConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/scoreMap","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/timeout","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/jsonDictionary()"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/fromJSONDictionary(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSNetworkHealthConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1fromJSONDictionary(_:)\/title","value":"fromJSONDictionary:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1fromJSONDictionary(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJSONDictionary:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1scoreMap\/title","value":"scoreMap"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1scoreMap\/fragments","value":[{"kind":"identifier","text":"scoreMap"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1timeout\/title","value":"timeout"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1timeout\/fragments","value":[{"kind":"identifier","text":"timeout"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1jsonDictionary()\/title","value":"JSONDictionary"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1jsonDictionary()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"JSONDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig\/title","value":"HMSNetworkHealthConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig\/fragments","value":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}