{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollusertrackingmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollusertrackingmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/Se","doc:\/\/live.100ms.HMS\/SE","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the user tracking mode for poll participation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"title":"HMSPollUserTrackingMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSPollUserTrackingMode","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/customerUserID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/peerID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/userName"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/userName":{"role":"symbol","title":"HMSPollUserTrackingMode.userName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userName"}],"abstract":[{"type":"text","text":"User tracking is based on the username."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/userName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingModeUserName"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/username"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/live.100ms.HMS\/SE"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode":{"role":"symbol","title":"HMSPollUserTrackingMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"abstract":[{"type":"text","text":"Represents the user tracking mode for poll participation."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/customerUserID":{"role":"symbol","title":"HMSPollUserTrackingMode.customerUserID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerUserID"}],"abstract":[{"type":"text","text":"User tracking is based on the customer ID."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/customerUserID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/customeruserid"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/peerID":{"role":"symbol","title":"HMSPollUserTrackingMode.peerID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerID"}],"abstract":[{"type":"text","text":"User tracking is based on the peer ID."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/peerID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollUserTrackingModePeerID"}],"url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/peerid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollUserTrackingMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspollusertrackingmode\/rawrepresentable-implementations"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/live.100ms.HMS\/Se"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollUserTrackingMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/customerUserID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/peerID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollUserTrackingMode\/userName"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollUserTrackingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1userName\/title","value":"HMSPollUserTrackingModeUserName"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1userName\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingModeUserName"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode\/title","value":"HMSPollUserTrackingMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1customerUserID\/title","value":"HMSPollUserTrackingModeCustomerUserID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1customerUserID\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingModeCustomerUserID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1peerID\/title","value":"HMSPollUserTrackingModePeerID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollUserTrackingMode~1peerID\/fragments","value":[{"kind":"identifier","text":"HMSPollUserTrackingModePeerID"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}