{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspoll"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspoll"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/Se","doc:\/\/live.100ms.HMS\/SE","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a poll object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"title":"HMSPoll","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSPoll","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/anonymous","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/createdBy","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/duration","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/mode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/pollID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/questionCount","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/questions","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/result","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanViewResponses","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanVote","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedBy","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/state","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/stoppedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/stoppedBy","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/title","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/encode(to:)"]}],"references":{"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/rolesThatCanViewResponses":{"role":"symbol","title":"rolesThatCanViewResponses","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rolesThatCanViewResponses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The roles that can view the poll responses."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanViewResponses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rolesThatCanViewResponses"}],"url":"\/documentation\/hmssdk\/hmspoll\/rolesthatcanviewresponses"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/anonymous":{"role":"symbol","title":"anonymous","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"anonymous"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A flag indicating whether the poll is anonymous or not."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/anonymous","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"anonymous"}],"url":"\/documentation\/hmssdk\/hmspoll\/anonymous"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The duration of the poll in seconds."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/hmssdk\/hmspoll\/duration"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/questions":{"role":"symbol","title":"questions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestion","preciseIdentifier":"s:6HMSSDK15HMSPollQuestionC"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The list of questions in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/questions","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspoll\/questions"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll":{"role":"symbol","title":"HMSPoll","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"}],"abstract":[{"type":"text","text":"Represents a poll object."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPoll"}],"url":"\/documentation\/hmssdk\/hmspoll"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/questionCount":{"role":"symbol","title":"questionCount","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"questionCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The number of questions in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/questionCount","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspoll\/questioncount"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/startedBy":{"role":"symbol","title":"startedBy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"startedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The peer who started the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startedBy"}],"url":"\/documentation\/hmssdk\/hmspoll\/startedby"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/stoppedBy":{"role":"symbol","title":"stoppedBy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stoppedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The peer who stopped the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/stoppedBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stoppedBy"}],"url":"\/documentation\/hmssdk\/hmspoll\/stoppedby"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspoll\/encode(to:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/mode":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollUserTrackingMode","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollUserTrackingMode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The tracking mode for user participation in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/mode","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspoll\/mode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory"}],"abstract":[{"type":"text","text":"The type of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/hmssdk\/hmspoll\/type"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/rolesThatCanVote":{"role":"symbol","title":"rolesThatCanVote","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rolesThatCanVote"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The roles that can vote in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanVote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rolesThatCanVote"}],"url":"\/documentation\/hmssdk\/hmspoll\/rolesthatcanvote"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/startedAt":{"role":"symbol","title":"startedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The date and time when the poll was started."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startedAt"}],"url":"\/documentation\/hmssdk\/hmspoll\/startedat"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspoll\/init(from:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollState","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollState"}],"abstract":[{"type":"text","text":"The current state of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"url":"\/documentation\/hmssdk\/hmspoll\/state"},"doc://live.100ms.HMS/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/live.100ms.HMS\/SE"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/pollID":{"role":"symbol","title":"pollID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The unique identifier of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/pollID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pollID"}],"url":"\/documentation\/hmssdk\/hmspoll\/pollid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/stoppedAt":{"role":"symbol","title":"stoppedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stoppedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The date and time when the poll was stopped."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/stoppedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stoppedAt"}],"url":"\/documentation\/hmssdk\/hmspoll\/stoppedat"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The title of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/hmssdk\/hmspoll\/title"},"doc://live.100ms.HMS/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/live.100ms.HMS\/Se"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/result":{"role":"symbol","title":"result","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResult"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The result of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"result"}],"url":"\/documentation\/hmssdk\/hmspoll\/result"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPoll/createdBy":{"role":"symbol","title":"createdBy","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The peer who created the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/createdBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdBy"}],"url":"\/documentation\/hmssdk\/hmspoll\/createdby"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSPoll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/anonymous","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/createdBy","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/duration","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/pollID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/result","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanViewResponses","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/rolesThatCanVote","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/startedBy","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/state","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/stoppedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/stoppedBy","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/title","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPoll\/type"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPoll"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1rolesThatCanViewResponses\/title","value":"rolesThatCanViewResponses"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1rolesThatCanViewResponses\/fragments","value":[{"kind":"identifier","text":"rolesThatCanViewResponses"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1anonymous\/title","value":"anonymous"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1anonymous\/fragments","value":[{"kind":"identifier","text":"anonymous"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/title","value":"HMSPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll\/fragments","value":[{"kind":"identifier","text":"HMSPoll"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1startedBy\/title","value":"startedBy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1startedBy\/fragments","value":[{"kind":"identifier","text":"startedBy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1stoppedBy\/title","value":"stoppedBy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1stoppedBy\/fragments","value":[{"kind":"identifier","text":"stoppedBy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1rolesThatCanVote\/title","value":"rolesThatCanVote"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1rolesThatCanVote\/fragments","value":[{"kind":"identifier","text":"rolesThatCanVote"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1startedAt\/title","value":"startedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1startedAt\/fragments","value":[{"kind":"identifier","text":"startedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1pollID\/title","value":"pollID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1pollID\/fragments","value":[{"kind":"identifier","text":"pollID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1stoppedAt\/title","value":"stoppedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1stoppedAt\/fragments","value":[{"kind":"identifier","text":"stoppedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1title\/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1result\/title","value":"result"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1result\/fragments","value":[{"kind":"identifier","text":"result"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1createdBy\/title","value":"createdBy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPoll~1createdBy\/fragments","value":[{"kind":"identifier","text":"createdBy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}