{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspeerupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspeerupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/defaultUpdate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/metadataUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/nameUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/networkQualityUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/peerJoined","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/peerLeft","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/roleUpdated"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"}],"title":"HMSPeerUpdate","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSPeerUpdate","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdate"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate":{"role":"symbol","title":"HMSPeerUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdate"}],"url":"\/documentation\/hmssdk\/hmspeerupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/defaultUpdate":{"role":"symbol","title":"HMSPeerUpdate.defaultUpdate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/defaultUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateDefaultUpdate"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/defaultupdate"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/roleUpdated":{"role":"symbol","title":"HMSPeerUpdate.roleUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roleUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/roleUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateRoleUpdated"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/roleupdated"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/peerJoined":{"role":"symbol","title":"HMSPeerUpdate.peerJoined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerJoined"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/peerJoined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdatePeerJoined"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/peerjoined"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/nameUpdated":{"role":"symbol","title":"HMSPeerUpdate.nameUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/nameUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateNameUpdated"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/nameupdated"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspeerupdate\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/peerLeft":{"role":"symbol","title":"HMSPeerUpdate.peerLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerLeft"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/peerLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdatePeerLeft"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/peerleft"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspeerupdate\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspeerupdate\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/metadataUpdated":{"role":"symbol","title":"HMSPeerUpdate.metadataUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/metadataUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/metadataupdated"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/description","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspeerupdate\/description"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeerUpdate/networkQualityUpdated":{"role":"symbol","title":"HMSPeerUpdate.networkQualityUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkQualityUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/networkQualityUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeerUpdateNetworkQualityUpdated"}],"url":"\/documentation\/hmssdk\/hmspeerupdate\/networkqualityupdated"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSPeerUpdate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPeerUpdate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/defaultUpdate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/metadataUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/nameUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/networkQualityUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/peerJoined","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/peerLeft","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeerUpdate\/roleUpdated"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeerUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/title","value":"HMSPeerUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1defaultUpdate\/title","value":"HMSPeerUpdateDefaultUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1defaultUpdate\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateDefaultUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1roleUpdated\/title","value":"HMSPeerUpdateRoleUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1roleUpdated\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateRoleUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1peerJoined\/title","value":"HMSPeerUpdatePeerJoined"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1peerJoined\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdatePeerJoined"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1nameUpdated\/title","value":"HMSPeerUpdateNameUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1nameUpdated\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateNameUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1peerLeft\/title","value":"HMSPeerUpdatePeerLeft"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1peerLeft\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdatePeerLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1metadataUpdated\/title","value":"HMSPeerUpdateMetadataUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1metadataUpdated\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateMetadataUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1networkQualityUpdated\/title","value":"HMSPeerUpdateNetworkQualityUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeerUpdate~1networkQualityUpdated\/fragments","value":[{"kind":"identifier","text":"HMSPeerUpdateNetworkQualityUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}