{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPlugin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsplugin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsplugin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/activate()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/checkSupport()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/deactivate()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPlugin"}],"title":"HMSPlugin","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@HMSSDK@objc(pl)HMSPlugin","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPlugin"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPlugin/activate()":{"navigatorTitle":[{"kind":"identifier","text":"activate"}],"role":"symbol","title":"activate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/activate()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsplugin\/activate()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPlugin/checkSupport()":{"navigatorTitle":[{"kind":"identifier","text":"checkSupport"}],"role":"symbol","title":"checkSupport()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkSupport"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/checkSupport()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsplugin\/checksupport()"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPlugin/deactivate()":{"navigatorTitle":[{"kind":"identifier","text":"deactivate"}],"role":"symbol","title":"deactivate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deactivate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/deactivate()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsplugin\/deactivate()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPlugin":{"role":"symbol","title":"HMSPlugin","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPlugin"}],"url":"\/documentation\/hmssdk\/hmsplugin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HMSPlugin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPlugin"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPlugin"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/activate()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/checkSupport()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPlugin\/deactivate()"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPlugin"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1activate()\/title","value":"activate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1activate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1checkSupport()\/title","value":"checkSupport"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1checkSupport()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkSupport"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1deactivate()\/title","value":"deactivate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin~1deactivate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deactivate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin\/title","value":"HMSPlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPlugin\/fragments","value":[{"kind":"identifier","text":"HMSPlugin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}