{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginsupportresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginsupportresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/init(type:errorType:errorMessage:)"]},{"title":"Type Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/deviceNotSupported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/operatingSystemNotSupported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/supported"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"}],"title":"HMSPluginSupportResult","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResult"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult":{"role":"symbol","title":"HMSPluginSupportResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResult"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult/supported":{"role":"symbol","title":"supported","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/supported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"supported"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult\/supported"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult/operatingSystemNotSupported":{"role":"symbol","title":"operatingSystemNotSupported","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatingSystemNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/operatingSystemNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operatingSystemNotSupported"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult\/operatingsystemnotsupported"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult/deviceNotSupported":{"role":"symbol","title":"deviceNotSupported","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPluginSupportResult"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/deviceNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceNotSupported"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult\/devicenotsupported"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResult/init(type:errorType:errorMessage:)":{"role":"symbol","title":"init(type:errorType:errorMessage:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginSupportResultType","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginSupportResultType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPluginUnsupportedErrorTypes","preciseIdentifier":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/init(type:errorType:errorMessage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithType:errorType:errorMessage:"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresult\/init(type:errortype:errormessage:)"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSPluginSupportResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPluginSupportResult"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/init(type:errorType:errorMessage:)"]},{"title":"Type Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/deviceNotSupported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/operatingSystemNotSupported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResult\/supported"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/title","value":"HMSPluginSupportResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResult"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1supported\/title","value":"supported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1supported\/fragments","value":[{"kind":"identifier","text":"supported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1operatingSystemNotSupported\/title","value":"operatingSystemNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1operatingSystemNotSupported\/fragments","value":[{"kind":"identifier","text":"operatingSystemNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1deviceNotSupported\/title","value":"deviceNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1deviceNotSupported\/fragments","value":[{"kind":"identifier","text":"deviceNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1init(type:errorType:errorMessage:)\/title","value":"initWithType:errorType:errorMessage:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResult~1init(type:errorType:errorMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:errorType:errorMessage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}