{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPreviewListener"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspreviewlistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspreviewlistener"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(peer:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(room:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/onPreview(room:localTracks:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPreviewListener"}],"title":"HMSPreviewListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@HMSSDK@objc(pl)HMSPreviewListener","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPreviewListener"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPreviewListener/on(error:)":{"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","title":"on(error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called when there is an error during preview checks"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmspreviewlistener\/on(error:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPreviewListener/on(peer:update:)":{"role":"symbol","title":"on(peer:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeerUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSPeerUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This will be called whenever there is an update on an existing peer"},{"type":"text","text":" "},{"type":"text","text":"or a new peer got added\/existing peer is removed."},{"type":"text","text":" "},{"type":"text","text":"This callback can be used to keep a track of all the peers in the room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(peer:update:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPeer:update:"}],"url":"\/documentation\/hmssdk\/hmspreviewlistener\/on(peer:update:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPreviewListener/on(room:update:)":{"navigatorTitle":[{"kind":"identifier","text":"onRoom:update:"}],"role":"symbol","title":"on(room:update:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"("},{"kind":"externalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoomUpdate","preciseIdentifier":"c:@M@HMSSDK@E@HMSRoomUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when there is a change in any property of the Room"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(room:update:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmspreviewlistener\/on(room:update:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPreviewListener":{"role":"symbol","title":"HMSPreviewListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPreviewListener"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPreviewListener"}],"url":"\/documentation\/hmssdk\/hmspreviewlistener"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPreviewListener/onPreview(room:localTracks:)":{"navigatorTitle":[{"kind":"identifier","text":"onPreview:localTracks:"}],"role":"symbol","title":"onPreview(room:localTracks:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPreview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localTracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"This will be called when preview checks have been passed successfully and local tracks"},{"type":"text","text":" "},{"type":"text","text":"were created if needed for the role."},{"type":"text","text":" "},{"type":"text","text":"This is the point where applications can start showing a preview screen"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/onPreview(room:localTracks:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmspreviewlistener\/onpreview(room:localtracks:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"HMSPreviewListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPreviewListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPreviewListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(peer:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/on(room:update:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPreviewListener\/onPreview(room:localTracks:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPreviewListener"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1on(error:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1on(error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1on(peer:update:)\/title","value":"onPeer:update:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1on(peer:update:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPeer:update:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1on(room:update:)\/title","value":"onRoom:update:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1on(room:update:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRoom:update:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener\/title","value":"HMSPreviewListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener\/fragments","value":[{"kind":"identifier","text":"HMSPreviewListener"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1onPreview(room:localTracks:)\/title","value":"onPreview:localTracks:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPreviewListener~1onPreview(room:localTracks:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPreview:localTracks:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}