{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPerformanceStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsperformancestats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsperformancestats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/init()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/init(cpu:memory:battery:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/battery","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/cpu","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/memory"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPerformanceStats"}],"title":"HMSPerformanceStats","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@S@HMSPerformanceStats","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPerformanceStats"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/init()","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsperformancestats\/init()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats/init(cpu:memory:battery:)":{"role":"symbol","title":"init(cpu:memory:battery:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"memory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"battery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/init(cpu:memory:battery:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsperformancestats\/init(cpu:memory:battery:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats/cpu":{"role":"symbol","title":"cpu","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/cpu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cpu"}],"url":"\/documentation\/hmssdk\/hmsperformancestats\/cpu"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats/battery":{"role":"symbol","title":"battery","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"battery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/battery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"battery"}],"url":"\/documentation\/hmssdk\/hmsperformancestats\/battery"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats":{"role":"symbol","title":"HMSPerformanceStats","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPerformanceStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPerformanceStats"}],"url":"\/documentation\/hmssdk\/hmsperformancestats"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPerformanceStats/memory":{"role":"symbol","title":"memory","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/memory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memory"}],"url":"\/documentation\/hmssdk\/hmsperformancestats\/memory"},"doc://live.100ms.HMS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/live.100ms.HMS\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"HMSPerformanceStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"struct"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPerformanceStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPerformanceStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/battery","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/cpu","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPerformanceStats\/memory"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPerformanceStats"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats~1cpu\/title","value":"cpu"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats~1cpu\/fragments","value":[{"kind":"identifier","text":"cpu"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats~1battery\/title","value":"battery"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats~1battery\/fragments","value":[{"kind":"identifier","text":"battery"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats\/title","value":"HMSPerformanceStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats\/fragments","value":[{"kind":"identifier","text":"HMSPerformanceStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats~1memory\/title","value":"memory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPerformanceStats~1memory\/fragments","value":[{"kind":"identifier","text":"memory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}