{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginunsupportederrortypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginunsupportederrortypes"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/deviceNotsupported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/operatingSystemNotSupported"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"title":"HMSPluginUnsupportedErrorTypes","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSPluginUnsupportedErrorTypes","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/none":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesNone"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/none"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/operatingSystemNotSupported":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes.operatingSystemNotSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operatingSystemNotSupported"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/operatingSystemNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/operatingsystemnotsupported"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginUnsupportedErrorTypes/deviceNotsupported":{"role":"symbol","title":"HMSPluginUnsupportedErrorTypes.deviceNotsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotsupported"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/deviceNotsupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}],"url":"\/documentation\/hmssdk\/hmspluginunsupportederrortypes\/devicenotsupported"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSPluginUnsupportedErrorTypes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/deviceNotsupported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginUnsupportedErrorTypes\/operatingSystemNotSupported"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/title","value":"HMSPluginUnsupportedErrorTypes"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1none\/title","value":"HMSPluginUnsupportedErrorTypesNone"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1none\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesNone"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1operatingSystemNotSupported\/title","value":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1operatingSystemNotSupported\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesOperatingSystemNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1deviceNotsupported\/title","value":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginUnsupportedErrorTypes~1deviceNotsupported\/fragments","value":[{"kind":"identifier","text":"HMSPluginUnsupportedErrorTypesDeviceNotsupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}