{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspeer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspeer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"title":"HMSPeer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSPeer","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/==(_:_:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/audioTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/auxiliaryTracks","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/customerUserID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/isLocal","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/joinedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/metadata","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/name","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/networkQuality","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/peerID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/role","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/updatedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/videoTrack"]}],"references":{"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/joinedAt":{"role":"symbol","title":"joinedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/joinedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinedAt"}],"url":"\/documentation\/hmssdk\/hmspeer\/joinedat"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/auxiliaryTracks":{"role":"symbol","title":"auxiliaryTracks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"auxiliaryTracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/auxiliaryTracks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"auxiliaryTracks"}],"url":"\/documentation\/hmssdk\/hmspeer\/auxiliarytracks"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/audioTrack":{"role":"symbol","title":"audioTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioTrack","preciseIdentifier":"c:objc(cs)HMSAudioTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/audioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioTrack"}],"url":"\/documentation\/hmssdk\/hmspeer\/audiotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/metadata":{"role":"symbol","title":"metadata","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/metadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"url":"\/documentation\/hmssdk\/hmspeer\/metadata"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/peerID":{"role":"symbol","title":"peerID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/peerID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerID"}],"url":"\/documentation\/hmssdk\/hmspeer\/peerid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/hmssdk\/hmspeer\/name"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/==(_:_:)":{"role":"symbol","title":"==(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/==(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspeer\/==(_:_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/updatedAt":{"role":"symbol","title":"updatedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/updatedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatedAt"}],"url":"\/documentation\/hmssdk\/hmspeer\/updatedat"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/networkQuality":{"role":"symbol","title":"networkQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSNetworkQuality","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSNetworkQuality"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/networkQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"networkQuality"}],"url":"\/documentation\/hmssdk\/hmspeer\/networkquality"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/customerUserID":{"role":"symbol","title":"customerUserID","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerUserID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/customerUserID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customerUserID"}],"url":"\/documentation\/hmssdk\/hmspeer\/customeruserid"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/videoTrack":{"role":"symbol","title":"videoTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/videoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoTrack"}],"url":"\/documentation\/hmssdk\/hmspeer\/videotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/isLocal":{"role":"symbol","title":"isLocal","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLocal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/isLocal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLocal"}],"url":"\/documentation\/hmssdk\/hmspeer\/islocal"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer/role":{"role":"symbol","title":"role","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/role","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"role"}],"url":"\/documentation\/hmssdk\/hmspeer\/role"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalPeer":{"role":"symbol","title":"HMSLocalPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalPeer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalPeer"}],"url":"\/documentation\/hmssdk\/hmslocalpeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemotePeer":{"role":"symbol","title":"HMSRemotePeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemotePeer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemotePeer"}],"url":"\/documentation\/hmssdk\/hmsremotepeer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSPeer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPeer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/audioTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/auxiliaryTracks","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/customerUserID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/isLocal","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/joinedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/metadata","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/name","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/networkQuality","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/peerID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/role","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/updatedAt","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer\/videoTrack"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1joinedAt\/title","value":"joinedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1joinedAt\/fragments","value":[{"kind":"identifier","text":"joinedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1auxiliaryTracks\/title","value":"auxiliaryTracks"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1auxiliaryTracks\/fragments","value":[{"kind":"identifier","text":"auxiliaryTracks"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1audioTrack\/title","value":"audioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1audioTrack\/fragments","value":[{"kind":"identifier","text":"audioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1metadata\/title","value":"metadata"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1metadata\/fragments","value":[{"kind":"identifier","text":"metadata"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1peerID\/title","value":"peerID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1peerID\/fragments","value":[{"kind":"identifier","text":"peerID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1updatedAt\/title","value":"updatedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1updatedAt\/fragments","value":[{"kind":"identifier","text":"updatedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1networkQuality\/title","value":"networkQuality"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1networkQuality\/fragments","value":[{"kind":"identifier","text":"networkQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1customerUserID\/title","value":"customerUserID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1customerUserID\/fragments","value":[{"kind":"identifier","text":"customerUserID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1videoTrack\/title","value":"videoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1videoTrack\/fragments","value":[{"kind":"identifier","text":"videoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1isLocal\/title","value":"isLocal"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1isLocal\/fragments","value":[{"kind":"identifier","text":"isLocal"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1role\/title","value":"role"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer~1role\/fragments","value":[{"kind":"identifier","text":"role"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer\/title","value":"HMSLocalPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer\/fragments","value":[{"kind":"identifier","text":"HMSLocalPeer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemotePeer\/title","value":"HMSRemotePeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemotePeer\/fragments","value":[{"kind":"identifier","text":"HMSRemotePeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}