{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResultType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspluginsupportresulttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspluginsupportresulttype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/supported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/unsupported"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResultType"}],"title":"HMSPluginSupportResultType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSPluginSupportResultType","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResultType"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspluginsupportresulttype\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType":{"role":"symbol","title":"HMSPluginSupportResultType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResultType"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResultType"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresulttype"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmspluginsupportresulttype\/rawrepresentable-implementations"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType/supported":{"role":"symbol","title":"HMSPluginSupportResultType.supported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"supported"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/supported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResultTypeSupported"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresulttype\/supported"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmspluginsupportresulttype\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPluginSupportResultType/unsupported":{"role":"symbol","title":"HMSPluginSupportResultType.unsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupported"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/unsupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPluginSupportResultTypeUnsupported"}],"url":"\/documentation\/hmssdk\/hmspluginsupportresulttype\/unsupported"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSPluginSupportResultType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResultType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSPluginSupportResultType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/supported","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPluginSupportResultType\/unsupported"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPluginSupportResultType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType\/title","value":"HMSPluginSupportResultType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResultType"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType~1supported\/title","value":"HMSPluginSupportResultTypeSupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType~1supported\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResultTypeSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType~1unsupported\/title","value":"HMSPluginSupportResultTypeUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPluginSupportResultType~1unsupported\/fragments","value":[{"kind":"identifier","text":"HMSPluginSupportResultTypeUnsupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}