{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReasons"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreasons"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreasons"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/bandwidth","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/cpu","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/other","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/qualityLimitationResolutionChanges","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/reason"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReasons"}],"title":"HMSQualityLimitationReasons","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSQualityLimitationReasons","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/none":{"role":"symbol","title":"none","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"none"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/none"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/bandwidth":{"role":"symbol","title":"bandwidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bandwidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/bandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bandwidth"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/bandwidth"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons":{"role":"symbol","title":"HMSQualityLimitationReasons","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReasons"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/qualityLimitationResolutionChanges":{"role":"symbol","title":"qualityLimitationResolutionChanges","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityLimitationResolutionChanges"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/qualityLimitationResolutionChanges","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityLimitationResolutionChanges"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/qualitylimitationresolutionchanges"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/other":{"role":"symbol","title":"other","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"other"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/other"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/cpu":{"role":"symbol","title":"cpu","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/cpu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cpu"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/cpu"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/reason":{"role":"symbol","title":"reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSQualityLimitationReason","preciseIdentifier":"c:@E@HMSQualityLimitationReason"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/reason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reason"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/reason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSQualityLimitationReasons"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/bandwidth","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/cpu","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/other","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/qualityLimitationResolutionChanges","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/reason"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReasons"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1none\/title","value":"none"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1none\/fragments","value":[{"kind":"identifier","text":"none"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1bandwidth\/title","value":"bandwidth"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1bandwidth\/fragments","value":[{"kind":"identifier","text":"bandwidth"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons\/title","value":"HMSQualityLimitationReasons"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1qualityLimitationResolutionChanges\/title","value":"qualityLimitationResolutionChanges"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1qualityLimitationResolutionChanges\/fragments","value":[{"kind":"identifier","text":"qualityLimitationResolutionChanges"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1other\/title","value":"other"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1other\/fragments","value":[{"kind":"identifier","text":"other"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1cpu\/title","value":"cpu"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1cpu\/fragments","value":[{"kind":"identifier","text":"cpu"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1reason\/title","value":"reason"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1reason\/fragments","value":[{"kind":"identifier","text":"reason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}