{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY","doc:\/\/live.100ms.HMS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/CPU","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/bandwidth","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/other","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/unkown"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"}],"title":"HMSQualityLimitationReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@HMSQualityLimitationReason","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/none":{"role":"symbol","title":"HMSQualityLimitationReason.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonNone"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/none"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/bandwidth":{"role":"symbol","title":"HMSQualityLimitationReason.bandwidth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bandwidth"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/bandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/bandwidth"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/CPU":{"role":"symbol","title":"HMSQualityLimitationReason.CPU","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CPU"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/CPU","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonCPU"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/cpu"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/other":{"role":"symbol","title":"HMSQualityLimitationReason.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonOther"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/other"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/unkown":{"role":"symbol","title":"HMSQualityLimitationReason.unkown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unkown"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/unkown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/unkown"},"doc://live.100ms.HMS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/live.100ms.HMS\/s8SendableP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason":{"role":"symbol","title":"HMSQualityLimitationReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReason"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSQualityLimitationReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/CPU","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/bandwidth","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/none","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/other","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/unkown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1none\/title","value":"kHMSQualityLimitationReasonNone"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1none\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonNone"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1bandwidth\/title","value":"kHMSQualityLimitationReasonBandwidth"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1bandwidth\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1CPU\/title","value":"kHMSQualityLimitationReasonCPU"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1CPU\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonCPU"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1other\/title","value":"kHMSQualityLimitationReasonOther"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1other\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonOther"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1unkown\/title","value":"kHMSQualityLimitationReasonUnkown"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1unkown\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/title","value":"HMSQualityLimitationReason"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}