{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsroom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsroom"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"title":"HMSRoom","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSRoom","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/browserRecordingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/hlsRecordingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/hlsStreamingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/metaData","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/name","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/peerCount","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/peers","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/roomID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/rtmpStreamingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/serverRecordingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/sessionID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/sessionStartedAt"]}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/sessionStartedAt":{"role":"symbol","title":"sessionStartedAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionStartedAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/sessionStartedAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionStartedAt"}],"url":"\/documentation\/hmssdk\/hmsroom\/sessionstartedat"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/peers":{"role":"symbol","title":"peers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/peers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peers"}],"url":"\/documentation\/hmssdk\/hmsroom\/peers"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom":{"role":"symbol","title":"HMSRoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}],"url":"\/documentation\/hmssdk\/hmsroom"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/hlsRecordingState":{"role":"symbol","title":"hlsRecordingState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsRecordingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSRecordingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/hlsRecordingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hlsRecordingState"}],"url":"\/documentation\/hmssdk\/hmsroom\/hlsrecordingstate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/rtmpStreamingState":{"role":"symbol","title":"rtmpStreamingState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmpStreamingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRTMPStreamingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRTMPStreamingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/rtmpStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtmpStreamingState"}],"url":"\/documentation\/hmssdk\/hmsroom\/rtmpstreamingstate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/peerCount":{"role":"symbol","title":"peerCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/peerCount","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsroom\/peercount"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/hmssdk\/hmsroom\/name"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/hlsStreamingState":{"role":"symbol","title":"hlsStreamingState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsStreamingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSStreamingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSStreamingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/hlsStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hlsStreamingState"}],"url":"\/documentation\/hmssdk\/hmsroom\/hlsstreamingstate"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/roomID":{"role":"symbol","title":"roomID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/roomID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roomID"}],"url":"\/documentation\/hmssdk\/hmsroom\/roomid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/browserRecordingState":{"role":"symbol","title":"browserRecordingState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"browserRecordingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSBrowserRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSBrowserRecordingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/browserRecordingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"browserRecordingState"}],"url":"\/documentation\/hmssdk\/hmsroom\/browserrecordingstate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/sessionID":{"role":"symbol","title":"sessionID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/sessionID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionID"}],"url":"\/documentation\/hmssdk\/hmsroom\/sessionid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/serverRecordingState":{"role":"symbol","title":"serverRecordingState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverRecordingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSServerRecordingState","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSServerRecordingState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/serverRecordingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverRecordingState"}],"url":"\/documentation\/hmssdk\/hmsroom\/serverrecordingstate"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom/metaData":{"role":"symbol","title":"metaData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/metaData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metaData"}],"url":"\/documentation\/hmssdk\/hmsroom\/metadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSRoom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSRoom"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/browserRecordingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/hlsRecordingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/hlsStreamingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/metaData","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/name","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/peers","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/roomID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/rtmpStreamingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/serverRecordingState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/sessionID","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom\/sessionStartedAt"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1sessionStartedAt\/title","value":"sessionStartedAt"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1sessionStartedAt\/fragments","value":[{"kind":"identifier","text":"sessionStartedAt"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1peers\/title","value":"peers"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1peers\/fragments","value":[{"kind":"identifier","text":"peers"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/title","value":"HMSRoom"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1hlsRecordingState\/title","value":"hlsRecordingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1hlsRecordingState\/fragments","value":[{"kind":"identifier","text":"hlsRecordingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1rtmpStreamingState\/title","value":"rtmpStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1rtmpStreamingState\/fragments","value":[{"kind":"identifier","text":"rtmpStreamingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1hlsStreamingState\/title","value":"hlsStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1hlsStreamingState\/fragments","value":[{"kind":"identifier","text":"hlsStreamingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1roomID\/title","value":"roomID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1roomID\/fragments","value":[{"kind":"identifier","text":"roomID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1browserRecordingState\/title","value":"browserRecordingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1browserRecordingState\/fragments","value":[{"kind":"identifier","text":"browserRecordingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1sessionID\/title","value":"sessionID"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1sessionID\/fragments","value":[{"kind":"identifier","text":"sessionID"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1serverRecordingState\/title","value":"serverRecordingState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1serverRecordingState\/fragments","value":[{"kind":"identifier","text":"serverRecordingState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1metaData\/title","value":"metaData"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom~1metaData\/fragments","value":[{"kind":"identifier","text":"metaData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}