{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteAudioTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsremoteaudiotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsremoteaudiotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/isPlaybackAllowed()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/setPlaybackAllowed(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/setVolume(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteAudioTrack"}],"title":"HMSRemoteAudioTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSRemoteAudioTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrack":{"role":"symbol","title":"HMSAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrack"}],"url":"\/documentation\/hmssdk\/hmsaudiotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteAudioTrack":{"role":"symbol","title":"HMSRemoteAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteAudioTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}],"url":"\/documentation\/hmssdk\/hmsremoteaudiotrack"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteAudioTrack/setVolume(_:)":{"role":"symbol","title":"setVolume(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/setVolume(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVolume:"}],"url":"\/documentation\/hmssdk\/hmsremoteaudiotrack\/setvolume(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteAudioTrack/isPlaybackAllowed()":{"role":"symbol","title":"isPlaybackAllowed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaybackAllowed"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/isPlaybackAllowed()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPlaybackAllowed"}],"url":"\/documentation\/hmssdk\/hmsremoteaudiotrack\/isplaybackallowed()"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteAudioTrack/setPlaybackAllowed(_:)":{"role":"symbol","title":"setPlaybackAllowed(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPlaybackAllowed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/setPlaybackAllowed(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPlaybackAllowed:"}],"url":"\/documentation\/hmssdk\/hmsremoteaudiotrack\/setplaybackallowed(_:)"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSRemoteAudioTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/isPlaybackAllowed()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/setPlaybackAllowed(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack\/setVolume(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteAudioTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrack","preciseIdentifier":"c:objc(cs)HMSAudioTrack","text":"HMSAudioTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrack\/title","value":"HMSAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrack\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack\/title","value":"HMSRemoteAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack\/fragments","value":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack~1setVolume(_:)\/title","value":"setVolume:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack~1setVolume(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVolume:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack~1isPlaybackAllowed()\/title","value":"isPlaybackAllowed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack~1isPlaybackAllowed()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPlaybackAllowed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack~1setPlaybackAllowed(_:)\/title","value":"setPlaybackAllowed:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack~1setPlaybackAllowed(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPlaybackAllowed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}