{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSReceiverStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsreceiverstats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsreceiverstats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoStats"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/bitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/bytesReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/jitter","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/packetsReceived"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSReceiverStats"}],"title":"HMSReceiverStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSReceiverStats","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSReceiverStats"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSReceiverStats/jitter":{"role":"symbol","title":"jitter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/jitter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jitter"}],"url":"\/documentation\/hmssdk\/hmsreceiverstats\/jitter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSReceiverStats":{"role":"symbol","title":"HMSReceiverStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSReceiverStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSReceiverStats"}],"url":"\/documentation\/hmssdk\/hmsreceiverstats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoStats":{"role":"symbol","title":"HMSRemoteVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteVideoStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemoteVideoStats"}],"url":"\/documentation\/hmssdk\/hmsremotevideostats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSReceiverStats/bitrate":{"role":"symbol","title":"bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/bitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrate"}],"url":"\/documentation\/hmssdk\/hmsreceiverstats\/bitrate"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSReceiverStats/bytesReceived":{"role":"symbol","title":"bytesReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/bytesReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytesReceived"}],"url":"\/documentation\/hmssdk\/hmsreceiverstats\/bytesreceived"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSReceiverStats/packetsReceived":{"role":"symbol","title":"packetsReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/packetsReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetsReceived"}],"url":"\/documentation\/hmssdk\/hmsreceiverstats\/packetsreceived"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSReceiverStats/packetsLost":{"role":"symbol","title":"packetsLost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/packetsLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetsLost"}],"url":"\/documentation\/hmssdk\/hmsreceiverstats\/packetslost"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteAudioStats":{"role":"symbol","title":"HMSRemoteAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteAudioStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemoteAudioStats"}],"url":"\/documentation\/hmssdk\/hmsremoteaudiostats"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSReceiverStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSReceiverStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSReceiverStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/bitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/bytesReceived","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/jitter","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSReceiverStats\/packetsReceived"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoStats"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSReceiverStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1jitter\/title","value":"jitter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1jitter\/fragments","value":[{"kind":"identifier","text":"jitter"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats\/title","value":"HMSReceiverStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats\/fragments","value":[{"kind":"identifier","text":"HMSReceiverStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoStats\/title","value":"HMSRemoteVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoStats\/fragments","value":[{"kind":"identifier","text":"HMSRemoteVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1bitrate\/title","value":"bitrate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1bitrate\/fragments","value":[{"kind":"identifier","text":"bitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1bytesReceived\/title","value":"bytesReceived"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1bytesReceived\/fragments","value":[{"kind":"identifier","text":"bytesReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1packetsReceived\/title","value":"packetsReceived"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1packetsReceived\/fragments","value":[{"kind":"identifier","text":"packetsReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1packetsLost\/title","value":"packetsLost"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSReceiverStats~1packetsLost\/fragments","value":[{"kind":"identifier","text":"packetsLost"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioStats\/title","value":"HMSRemoteAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioStats\/fragments","value":[{"kind":"identifier","text":"HMSRemoteAudioStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}