{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStatsInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsrtcstatsinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsrtcstatsinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/audioLevel","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/incomingAvailableBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/outgoingAvailableBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/peerId"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStatsInfo"}],"title":"HMSRTCStatsInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSRTCStatsInfo","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRTCStatsInfo"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsInfo/audioLevel":{"role":"symbol","title":"audioLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/audioLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioLevel"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsinfo\/audiolevel"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsInfo/peerId":{"role":"symbol","title":"peerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/peerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerId"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsinfo\/peerid"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsInfo/incomingAvailableBitrate":{"role":"symbol","title":"incomingAvailableBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"incomingAvailableBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/incomingAvailableBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"incomingAvailableBitrate"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsinfo\/incomingavailablebitrate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsInfo/outgoingAvailableBitrate":{"role":"symbol","title":"outgoingAvailableBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outgoingAvailableBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/outgoingAvailableBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"outgoingAvailableBitrate"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsinfo\/outgoingavailablebitrate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsInfo":{"role":"symbol","title":"HMSRTCStatsInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStatsInfo"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRTCStatsInfo"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsinfo"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRTCStatsInfo/packetsLost":{"role":"symbol","title":"packetsLost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/packetsLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetsLost"}],"url":"\/documentation\/hmssdk\/hmsrtcstatsinfo\/packetslost"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSRTCStatsInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRTCStatsInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSRTCStatsInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/audioLevel","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/incomingAvailableBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/outgoingAvailableBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRTCStatsInfo\/peerId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRTCStatsInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1audioLevel\/title","value":"audioLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1audioLevel\/fragments","value":[{"kind":"identifier","text":"audioLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1peerId\/title","value":"peerId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1peerId\/fragments","value":[{"kind":"identifier","text":"peerId"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1incomingAvailableBitrate\/title","value":"incomingAvailableBitrate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1incomingAvailableBitrate\/fragments","value":[{"kind":"identifier","text":"incomingAvailableBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1outgoingAvailableBitrate\/title","value":"outgoingAvailableBitrate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1outgoingAvailableBitrate\/fragments","value":[{"kind":"identifier","text":"outgoingAvailableBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo\/title","value":"HMSRTCStatsInfo"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo\/fragments","value":[{"kind":"identifier","text":"HMSRTCStatsInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1packetsLost\/title","value":"packetsLost"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRTCStatsInfo~1packetsLost\/fragments","value":[{"kind":"identifier","text":"packetsLost"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}