{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsroomupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsroomupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/browserRecordingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsRecordingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsStreamingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/metaDataUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/roomTypeChanged","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/rtmpStreamingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/serverRecordingStateUpdated"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"title":"HMSRoomUpdate","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSRoomUpdate","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdate"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate":{"role":"symbol","title":"HMSRoomUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdate"}],"url":"\/documentation\/hmssdk\/hmsroomupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/description","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsroomupdate\/description"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/roomTypeChanged":{"role":"symbol","title":"HMSRoomUpdate.roomTypeChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomTypeChanged"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/roomTypeChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/roomtypechanged"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsroomupdate\/rawrepresentable-implementations"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/hlsStreamingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.hlsStreamingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsStreamingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsStreamingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateHlsStreamingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/hlsstreamingstateupdated"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/serverRecordingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.serverRecordingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverRecordingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/serverRecordingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateServerRecordingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/serverrecordingstateupdated"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/metaDataUpdated":{"role":"symbol","title":"HMSRoomUpdate.metaDataUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"metaDataUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/metaDataUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateMetaDataUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/metadataupdated"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsroomupdate\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/rtmpStreamingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.rtmpStreamingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmpStreamingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/rtmpStreamingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/rtmpstreamingstateupdated"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsroomupdate\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/browserRecordingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.browserRecordingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"browserRecordingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/browserRecordingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateBrowserRecordingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/browserrecordingstateupdated"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoomUpdate/hlsRecordingStateUpdated":{"role":"symbol","title":"HMSRoomUpdate.hlsRecordingStateUpdated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsRecordingStateUpdated"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsRecordingStateUpdated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}],"url":"\/documentation\/hmssdk\/hmsroomupdate\/hlsrecordingstateupdated"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSRoomUpdate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/browserRecordingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsRecordingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/hlsStreamingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/metaDataUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/roomTypeChanged","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/rtmpStreamingStateUpdated","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoomUpdate\/serverRecordingStateUpdated"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoomUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/title","value":"HMSRoomUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1roomTypeChanged\/title","value":"HMSRoomUpdateRoomTypeChanged"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1roomTypeChanged\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateRoomTypeChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1hlsStreamingStateUpdated\/title","value":"HMSRoomUpdateHlsStreamingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1hlsStreamingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateHlsStreamingStateUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1serverRecordingStateUpdated\/title","value":"HMSRoomUpdateServerRecordingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1serverRecordingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateServerRecordingStateUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1metaDataUpdated\/title","value":"HMSRoomUpdateMetaDataUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1metaDataUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateMetaDataUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1rtmpStreamingStateUpdated\/title","value":"HMSRoomUpdateRtmpStreamingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1rtmpStreamingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateRtmpStreamingStateUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1browserRecordingStateUpdated\/title","value":"HMSRoomUpdateBrowserRecordingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1browserRecordingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateBrowserRecordingStateUpdated"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1hlsRecordingStateUpdated\/title","value":"HMSRoomUpdateHlsRecordingStateUpdated"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoomUpdate~1hlsRecordingStateUpdated\/fragments","value":[{"kind":"identifier","text":"HMSRoomUpdateHlsRecordingStateUpdated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}