{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastlayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastlayer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY","doc:\/\/live.100ms.HMS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/high","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/low","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/mid"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayer"}],"title":"HMSSimulcastLayer","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@HMSSimulcastLayer","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayer"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer":{"role":"symbol","title":"HMSSimulcastLayer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayer"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmssimulcastlayer\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/high":{"role":"symbol","title":"HMSSimulcastLayer.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSSimulcastLayerHigh"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer\/high"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssimulcastlayer\/init(rawvalue:)"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/mid":{"role":"symbol","title":"HMSSimulcastLayer.mid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/mid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer\/mid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmssimulcastlayer\/rawrepresentable-implementations"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayer/low":{"role":"symbol","title":"HMSSimulcastLayer.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSSimulcastLayerLow"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayer\/low"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/live.100ms.HMS\/s8SendableP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSSimulcastLayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSSimulcastLayer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/high","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/low","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayer\/mid"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer\/title","value":"HMSSimulcastLayer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1high\/title","value":"kHMSSimulcastLayerHigh"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1high\/fragments","value":[{"kind":"identifier","text":"kHMSSimulcastLayerHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1mid\/title","value":"kHMSSimulcastLayerMid"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1mid\/fragments","value":[{"kind":"identifier","text":"kHMSSimulcastLayerMid"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1low\/title","value":"kHMSSimulcastLayerLow"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayer~1low\/fragments","value":[{"kind":"identifier","text":"kHMSSimulcastLayerLow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}