{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastlayersettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastlayersettings"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCopying","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/maxBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/maxFrameRate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/rid","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/scaleResolutionDownBy"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerSettings"}],"title":"HMSSimulcastLayerSettings","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSSimulcastLayerSettings","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings/maxBitrate":{"role":"symbol","title":"maxBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/maxBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxBitrate"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings\/maxbitrate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings/init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)":{"role":"symbol","title":"init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"witRID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaleResolutionDownBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWitRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings\/init(witrid:maxbitrate:maxframerate:scaleresolutiondownby:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings":{"role":"symbol","title":"HMSSimulcastLayerSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings/maxFrameRate":{"role":"symbol","title":"maxFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/maxFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxFrameRate"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings\/maxframerate"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings/scaleResolutionDownBy":{"role":"symbol","title":"scaleResolutionDownBy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleResolutionDownBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/scaleResolutionDownBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scaleResolutionDownBy"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings\/scaleresolutiondownby"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSCopying"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerSettings/rid":{"role":"symbol","title":"rid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/rid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rid"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayersettings\/rid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSSimulcastLayerSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/maxBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/maxFrameRate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/rid","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/scaleResolutionDownBy"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerSettings\/init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1maxBitrate\/title","value":"maxBitrate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1maxBitrate\/fragments","value":[{"kind":"identifier","text":"maxBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)\/title","value":"initWitRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1init(witRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWitRID:maxBitrate:maxFrameRate:scaleResolutionDownBy:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings\/title","value":"HMSSimulcastLayerSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1maxFrameRate\/title","value":"maxFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1maxFrameRate\/fragments","value":[{"kind":"identifier","text":"maxFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1scaleResolutionDownBy\/title","value":"scaleResolutionDownBy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1scaleResolutionDownBy\/fragments","value":[{"kind":"identifier","text":"scaleResolutionDownBy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1rid\/title","value":"rid"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerSettings~1rid\/fragments","value":[{"kind":"identifier","text":"rid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}