{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSenderStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssenderstats"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/availableBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/bitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/bytesSent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/jitter","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/packetsLost","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/packetsSent","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/packetsSentDelay","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/roundTripTime","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/source","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/ssrc","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/trackId"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSenderStats"}],"title":"HMSSenderStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSSenderStats","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSenderStats"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/packetsLost":{"role":"symbol","title":"packetsLost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/packetsLost","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/packetslost"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/bitrate":{"role":"symbol","title":"bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/bitrate","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/bitrate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/jitter":{"role":"symbol","title":"jitter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/jitter","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/jitter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/availableBitrate":{"role":"symbol","title":"availableBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/availableBitrate","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/availablebitrate"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/source","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/source"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoStats":{"role":"symbol","title":"HMSLocalVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoStats"}],"url":"\/documentation\/hmssdk\/hmslocalvideostats"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/roundTripTime":{"role":"symbol","title":"roundTripTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundTripTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/roundTripTime","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/roundtriptime"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/trackId":{"role":"symbol","title":"trackId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/trackId","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/trackid"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalAudioStats":{"role":"symbol","title":"HMSLocalAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalAudioStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalAudioStats"}],"url":"\/documentation\/hmssdk\/hmslocalaudiostats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/packetsSentDelay":{"role":"symbol","title":"packetsSentDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsSentDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/packetsSentDelay","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/packetssentdelay"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/ssrc":{"role":"symbol","title":"ssrc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ssrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/ssrc","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/ssrc"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats":{"role":"symbol","title":"HMSSenderStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSenderStats"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSenderStats"}],"url":"\/documentation\/hmssdk\/hmssenderstats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/bytesSent":{"role":"symbol","title":"bytesSent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/bytesSent","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/bytessent"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSenderStats/packetsSent":{"role":"symbol","title":"packetsSent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsSent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSenderStats\/packetsSent","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssenderstats\/packetssent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats\/title","value":"HMSLocalVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoStats\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioStats\/title","value":"HMSLocalAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioStats\/fragments","value":[{"kind":"identifier","text":"HMSLocalAudioStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}