{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssimulcastlayerdefinition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssimulcastlayerdefinition"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/init(layer:resolution:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/layer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/resolution"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}],"title":"HMSSimulcastLayerDefinition","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSSimulcastLayerDefinition","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerDefinition/layer":{"role":"symbol","title":"layer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/layer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layer"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayerdefinition\/layer"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerDefinition/resolution":{"role":"symbol","title":"resolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/resolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resolution"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayerdefinition\/resolution"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerDefinition/init(layer:resolution:)":{"role":"symbol","title":"init(layer:resolution:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSimulcastLayer","preciseIdentifier":"c:@E@HMSSimulcastLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/init(layer:resolution:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLayer:resolution:"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayerdefinition\/init(layer:resolution:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSimulcastLayerDefinition":{"role":"symbol","title":"HMSSimulcastLayerDefinition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}],"url":"\/documentation\/hmssdk\/hmssimulcastlayerdefinition"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSSimulcastLayerDefinition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/layer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/resolution"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSimulcastLayerDefinition\/init(layer:resolution:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSimulcastLayerDefinition"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1layer\/title","value":"layer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1layer\/fragments","value":[{"kind":"identifier","text":"layer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1resolution\/title","value":"resolution"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1resolution\/fragments","value":[{"kind":"identifier","text":"resolution"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1init(layer:resolution:)\/title","value":"initWithLayer:resolution:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition~1init(layer:resolution:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:resolution:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition\/title","value":"HMSSimulcastLayerDefinition"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSimulcastLayerDefinition\/fragments","value":[{"kind":"identifier","text":"HMSSimulcastLayerDefinition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}