{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSessionStore"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssessionstore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssessionstore"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The HMSSessionStore class provides a centralized storage solution for session-related data."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSessionStore"}],"title":"HMSSessionStore","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSSessionStore","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSessionStore"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/object(forKey:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/observeChanges(forKeys:changeObserver:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/removeObserver(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/set(_:forKey:completion:)"]}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore/set(_:forKey:completion:)":{"role":"symbol","title":"set(_:forKey:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sets an object in the session store for a specified key."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/set(_:forKey:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"set:forKey:completion:"}],"url":"\/documentation\/hmssdk\/hmssessionstore\/set(_:forkey:completion:)"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore/removeObserver(_:)":{"role":"symbol","title":"removeObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the previously registerd change observer. It will no longer receive updates post this call."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/removeObserver(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"url":"\/documentation\/hmssdk\/hmssessionstore\/removeobserver(_:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore/observeChanges(forKeys:changeObserver:completion:)":{"role":"symbol","title":"observeChanges(forKeys:changeObserver:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChanges"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"changeObserver"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Adds a change observer for the specified keys in the session store."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/observeChanges(forKeys:changeObserver:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeChangesForKeys:changeObserver:completion:"}],"url":"\/documentation\/hmssdk\/hmssessionstore\/observechanges(forkeys:changeobserver:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore/object(forKey:completion:)":{"role":"symbol","title":"object(forKey:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Retrieves an object from the session store for a specified key"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/object(forKey:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"objectForKey:completion:"}],"url":"\/documentation\/hmssdk\/hmssessionstore\/object(forkey:completion:)"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSessionStore":{"role":"symbol","title":"HMSSessionStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSessionStore"}],"abstract":[{"type":"text","text":"The HMSSessionStore class provides a centralized storage solution for session-related data."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSessionStore"}],"url":"\/documentation\/hmssdk\/hmssessionstore"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSSessionStore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSSessionStore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSSessionStore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/object(forKey:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/observeChanges(forKeys:changeObserver:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/removeObserver(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSessionStore\/set(_:forKey:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSessionStore"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1set(_:forKey:completion:)\/title","value":"set:forKey:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1set(_:forKey:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"set:forKey:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1removeObserver(_:)\/title","value":"removeObserver:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1removeObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeObserver:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1observeChanges(forKeys:changeObserver:completion:)\/title","value":"observeChangesForKeys:changeObserver:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1observeChanges(forKeys:changeObserver:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeChangesForKeys:changeObserver:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1object(forKey:completion:)\/title","value":"objectForKey:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore~1object(forKey:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectForKey:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore\/title","value":"HMSSessionStore"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSessionStore\/fragments","value":[{"kind":"identifier","text":"HMSSessionStore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}