{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenShareConstants"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsscreenshareconstants"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsscreenshareconstants"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSActiveSDKId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSActiveSDKIdForAudio","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSAudioMachPortName","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSScreenMachPortName","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSScreenOrientationKey"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenShareConstants"}],"title":"HMSScreenShareConstants","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSScreenShareConstants","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSScreenShareConstants"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants":{"role":"symbol","title":"HMSScreenShareConstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenShareConstants"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSScreenShareConstants"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants/kHMSActiveSDKIdForAudio":{"role":"symbol","title":"kHMSActiveSDKIdForAudio","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kHMSActiveSDKIdForAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSActiveSDKIdForAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSActiveSDKIdForAudio"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants\/khmsactivesdkidforaudio"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants/kHMSAudioMachPortName":{"role":"symbol","title":"kHMSAudioMachPortName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kHMSAudioMachPortName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSAudioMachPortName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSAudioMachPortName"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants\/khmsaudiomachportname"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants/kHMSActiveSDKId":{"role":"symbol","title":"kHMSActiveSDKId","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kHMSActiveSDKId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSActiveSDKId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSActiveSDKId"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants\/khmsactivesdkid"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants/kHMSScreenOrientationKey":{"role":"symbol","title":"kHMSScreenOrientationKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kHMSScreenOrientationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSScreenOrientationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSScreenOrientationKey"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants\/khmsscreenorientationkey"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants\/init"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenShareConstants/kHMSScreenMachPortName":{"role":"symbol","title":"kHMSScreenMachPortName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kHMSScreenMachPortName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSScreenMachPortName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSScreenMachPortName"}],"url":"\/documentation\/hmssdk\/hmsscreenshareconstants\/khmsscreenmachportname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSScreenShareConstants"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSScreenShareConstants"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSScreenShareConstants"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSActiveSDKId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSActiveSDKIdForAudio","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSAudioMachPortName","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSScreenMachPortName","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenShareConstants\/kHMSScreenOrientationKey"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenShareConstants"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants\/title","value":"HMSScreenShareConstants"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants\/fragments","value":[{"kind":"identifier","text":"HMSScreenShareConstants"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSActiveSDKIdForAudio\/title","value":"kHMSActiveSDKIdForAudio"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSActiveSDKIdForAudio\/fragments","value":[{"kind":"identifier","text":"kHMSActiveSDKIdForAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSAudioMachPortName\/title","value":"kHMSAudioMachPortName"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSAudioMachPortName\/fragments","value":[{"kind":"identifier","text":"kHMSAudioMachPortName"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSActiveSDKId\/title","value":"kHMSActiveSDKId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSActiveSDKId\/fragments","value":[{"kind":"identifier","text":"kHMSActiveSDKId"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSScreenOrientationKey\/title","value":"kHMSScreenOrientationKey"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSScreenOrientationKey\/fragments","value":[{"kind":"identifier","text":"kHMSScreenOrientationKey"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSScreenMachPortName\/title","value":"kHMSScreenMachPortName"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenShareConstants~1kHMSScreenMachPortName\/fragments","value":[{"kind":"identifier","text":"kHMSScreenMachPortName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}