{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Key Concepts"}]}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Room"}]},{"type":"text","text":" - A room represents a real-time audio, video session, the basic building block of the 100mslive Video SDK"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Track"}]},{"type":"text","text":" - A track represents either the audio or video that makes up a stream"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Peer"}]},{"type":"text","text":" - A peer represents all participants connected to a room. Peers can be “local” or “remote”"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Broadcast"}]},{"type":"text","text":" - A local peer can send any message\/data to all remote peers in the room"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"HMSSDK has other methods which the client app can use to get more info about the Room, Peer and Tracks"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/@M@HMSAnalyticsSDK@objc(pl)HMSAnalytics","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"title":"HMSSDK","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/analyticsLevel","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/appGroup","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/interactivityCenter","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/localPeer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/logger","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/remotePeers","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/roles","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/room","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/trackSettings"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/accept(changeRole:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/activateForScreenSharing()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/add(delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/cancelPreview()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/change(metadata:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/change(name:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeRole(for:to:force:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeRolesOfAllPeers(to:limitToRoles:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(for:mute:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(mute:for:source:roles:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/endRoom(lock:reason:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getAudioOutputDeviceList()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getAuthTokenByRoomCode(_:userID:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getSessionMetadata(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/join(config:delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/leave(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/prepareForExternalAudioPlayback()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/preview(config:delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/preview(role:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/remove(delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/removePeer(_:reason:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/resumeAfterExternalAudioPlayback()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/screenBroadcastAudioReceiverNode()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendBroadcastMessage(type:message:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendDirectMessage(type:message:peer:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendGroupMessage(type:message:roles:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendHLSTimedMetadata(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/setSessionMetadata(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startAppScreenCapture(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startHLSStreaming(config:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startRTMPOrRecording(config:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopAppScreenCapture(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopHLSStreaming(config:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopRTMPAndRecording(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/switchAudioOutput(to:)"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/build(block:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/HMSAnalytics-Implementations"],"generated":true}],"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/setSessionMetadata(_:completion:)":{"deprecated":true,"role":"symbol","title":"setSessionMetadata(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSessionMetadata"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set session metadata"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/setSessionMetadata(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSessionMetadata:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/setsessionmetadata(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/switchAudioOutput(to:)":{"role":"symbol","title":"switchAudioOutput(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchAudioOutput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Routes output audio to a particular HMSAudioOutputDevice; You should pass one of the available audio output devices returned when calling getAudioDeviceList API"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/switchAudioOutput(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchAudioOutputTo:error:"}],"url":"\/documentation\/hmssdk\/hmssdk\/switchaudiooutput(to:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/cancelPreview()":{"role":"symbol","title":"cancelPreview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelPreview"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Call this API in case the tracks obtained via preview(role:) API are no longer needed. There is no need to call this if role change happened. Call this if user has decided not to change role to release camera\/mic."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/cancelPreview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelPreview"}],"url":"\/documentation\/hmssdk\/hmssdk\/cancelpreview()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/appGroup":{"role":"symbol","title":"appGroup","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets the app group"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/appGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appGroup"}],"url":"\/documentation\/hmssdk\/hmssdk\/appgroup"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/build(block:)":{"role":"symbol","title":"build(block:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSSDK","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSDK"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"HMSSDK","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSDK"}],"abstract":[{"type":"text","text":"this will instantiate an HMSSDK object"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/build(block:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildWithBlock:"}],"url":"\/documentation\/hmssdk\/hmssdk\/build(block:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/logger":{"role":"symbol","title":"logger","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logger"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSLogger","preciseIdentifier":"c:@M@HMSAnalyticsSDK@objc(pl)HMSLogger"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets the logger instance to use for piping logs"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logger"}],"url":"\/documentation\/hmssdk\/hmssdk\/logger"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/stopAppScreenCapture(completion:)":{"role":"symbol","title":"stopAppScreenCapture(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAppScreenCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Stop sharing in-app screen content"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopAppScreenCapture(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAppScreenCaptureWithCompletion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/stopappscreencapture(completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/sendBroadcastMessage(type:message:priority:completion:)":{"role":"symbol","title":"sendBroadcastMessage(type:message:priority:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBroadcastMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sends a message to everyone in the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendBroadcastMessage(type:message:priority:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendBroadcastMessageWithType:message:priority:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/sendbroadcastmessage(type:message:priority:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/startRTMPOrRecording(config:completion:)":{"role":"symbol","title":"startRTMPOrRecording(config:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRTMPOrRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRTMPConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRTMPConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Start RTMP stream and\/or room recording."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startRTMPOrRecording(config:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startRTMPOrRecordingWithConfig:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/startrtmporrecording(config:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/roles":{"role":"symbol","title":"roles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns all roles in the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/roles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roles"}],"url":"\/documentation\/hmssdk\/hmssdk\/roles"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/changeTrackState(for:mute:completion:)":{"role":"symbol","title":"changeTrackState(for:mute:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeTrackState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"To change the mute status of a remote HMSTrack."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(for:mute:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeTrackStateFor:mute:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/changetrackstate(for:mute:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/HMSAnalytics-Implementations":{"role":"collectionGroup","title":"HMSAnalytics Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/HMSAnalytics-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmssdk\/hmsanalytics-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/startHLSStreaming(config:completion:)":{"role":"symbol","title":"startHLSStreaming(config:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startHLSStreaming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSConfig"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Start HLS stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startHLSStreaming(config:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startHLSStreamingWithConfig:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/starthlsstreaming(config:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/leave(_:)":{"role":"symbol","title":"leave(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leave"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Call the "},{"type":"codeVoice","code":"leave"},{"type":"text","text":" method on the HMSSDK instance to leave the current room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/leave(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leave:"}],"url":"\/documentation\/hmssdk\/hmssdk\/leave(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/localPeer":{"role":"symbol","title":"localPeer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localPeer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSLocalPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSLocalPeer"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the local peer, which contains the local tracks."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/localPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localPeer"}],"url":"\/documentation\/hmssdk\/hmssdk\/localpeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/change(name:priority:completion:)":{"role":"symbol","title":"change(name:priority:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Changes name field of the local HMSPeer instance and sends the updated metadata to the other peers in the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/change(name:priority:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeWithName:priority:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/change(name:priority:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/accept(changeRole:completion:)":{"role":"symbol","title":"accept(changeRole:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accept"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changeRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoleChangeRequest","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoleChangeRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Call to accept the role change request sent to the current peer."},{"type":"text","text":" "},{"type":"text","text":"Once this method is called, the peer’s role will be changed to the requested one."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/accept(changeRole:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptWithChangeRole:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/accept(changerole:completion:)"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/sendDirectMessage(type:message:peer:priority:completion:)":{"role":"symbol","title":"sendDirectMessage(type:message:peer:priority:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendDirectMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sends a direct message to the specified peer only."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendDirectMessage(type:message:peer:priority:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendDirectMessageWithType:message:peer:priority:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/senddirectmessage(type:message:peer:priority:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/trackSettings":{"role":"symbol","title":"trackSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackSettings","preciseIdentifier":"c:objc(cs)HMSTrackSettings"}],"abstract":[{"type":"text","text":"Use to override track settings coming from role policy"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/trackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackSettings"}],"url":"\/documentation\/hmssdk\/hmssdk\/tracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/activateForScreenSharing()":{"role":"symbol","title":"activateForScreenSharing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activateForScreenSharing"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"When using multiple hms sdk sessions concurrently in single app, call this to set active sdk to share screen from"},{"type":"text","text":" "},{"type":"text","text":"Note: not required to be called when using just single hms sdk session"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/activateForScreenSharing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activateForScreenSharing"}],"url":"\/documentation\/hmssdk\/hmssdk\/activateforscreensharing()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/endRoom(lock:reason:completion:)":{"role":"symbol","title":"endRoom(lock:reason:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endRoom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"End the room and make all participants leave."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/endRoom(lock:reason:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endRoomWithLock:reason:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/endroom(lock:reason:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/sendHLSTimedMetadata(_:completion:)":{"role":"symbol","title":"sendHLSTimedMetadata(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendHLSTimedMetadata"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSHLSTimedMetadata","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSTimedMetadata"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send HLS timed metadata"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendHLSTimedMetadata(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendHLSTimedMetadata:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/sendhlstimedmetadata(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/preview(role:completion:)":{"role":"symbol","title":"preview(role:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Call this preview API any time after joining in case you need to show a preview for a certain role. i.e before doing\/accepting a role change request."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/preview(role:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewWithRole:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/preview(role:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/change(metadata:priority:completion:)":{"role":"symbol","title":"change(metadata:priority:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Changes metadata field of the local HMSPeer instance and sends the updated metadata to the other peers in the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/change(metadata:priority:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeWithMetadata:priority:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/change(metadata:priority:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/room":{"role":"symbol","title":"room","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the room which was joined."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/room","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"room"}],"url":"\/documentation\/hmssdk\/hmssdk\/room"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/join(config:delegate:)":{"role":"symbol","title":"join(config:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSUpdateListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSUpdateListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Join the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/join(config:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinWithConfig:delegate:"}],"url":"\/documentation\/hmssdk\/hmssdk\/join(config:delegate:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/remove(delegate:)":{"role":"symbol","title":"remove(delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSUpdateListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSUpdateListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the listener of SDK updates"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/remove(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeWithDelegate:"}],"url":"\/documentation\/hmssdk\/hmssdk\/remove(delegate:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/getAudioOutputDeviceList()":{"role":"symbol","title":"getAudioOutputDeviceList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioOutputDeviceList"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"HMSAudioOutputDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioOutputDevice"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns a list of available audio output devices"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getAudioOutputDeviceList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAudioOutputDeviceList"}],"url":"\/documentation\/hmssdk\/hmssdk\/getaudiooutputdevicelist()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/screenBroadcastAudioReceiverNode()":{"role":"symbol","title":"screenBroadcastAudioReceiverNode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNode"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"HMSScreenBroadcastAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSScreenBroadcastAudioNode"}],"abstract":[{"type":"text","text":"Get audio node which receives audio from screen broadcast extension"},{"type":"text","text":" "},{"type":"text","text":"App group needs to be set on hmssdk instance for it to work"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/screenBroadcastAudioReceiverNode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"}],"url":"\/documentation\/hmssdk\/hmssdk\/screenbroadcastaudioreceivernode()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/startAppScreenCapture(completion:)":{"role":"symbol","title":"startAppScreenCapture(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAppScreenCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Start sharing in-app screen content (use this to capture the content inside your own app only)"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startAppScreenCapture(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startAppScreenCaptureWithCompletion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/startappscreencapture(completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/remotePeers":{"role":"symbol","title":"remotePeers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remotePeers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRemotePeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRemotePeer"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Returns all remote peers in the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/remotePeers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remotePeers"}],"url":"\/documentation\/hmssdk\/hmssdk\/remotepeers"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/changeRolesOfAllPeers(to:limitToRoles:completion:)":{"role":"symbol","title":"changeRolesOfAllPeers(to:limitToRoles:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRolesOfAllPeers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limitToRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Requests a change of role for all peers except for the local peer."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeRolesOfAllPeers(to:limitToRoles:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeRolesOfAllPeersTo:limitToRoles:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/changerolesofallpeers(to:limittoroles:completion:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/prepareForExternalAudioPlayback()":{"role":"symbol","title":"prepareForExternalAudioPlayback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForExternalAudioPlayback"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/prepareForExternalAudioPlayback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForExternalAudioPlayback"}],"url":"\/documentation\/hmssdk\/hmssdk\/prepareforexternalaudioplayback()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/stopHLSStreaming(config:completion:)":{"role":"symbol","title":"stopHLSStreaming(config:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopHLSStreaming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSConfig"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Stop HLS stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopHLSStreaming(config:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopHLSStreamingWithConfig:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/stophlsstreaming(config:completion:)"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/resumeAfterExternalAudioPlayback()":{"role":"symbol","title":"resumeAfterExternalAudioPlayback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeAfterExternalAudioPlayback"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/resumeAfterExternalAudioPlayback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resumeAfterExternalAudioPlayback"}],"url":"\/documentation\/hmssdk\/hmssdk\/resumeafterexternalaudioplayback()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/preview(config:delegate:)":{"role":"symbol","title":"preview(config:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSConfig","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPreviewListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSPreviewListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Begin a preview so that the local peer’s audio and video can be displayed to them before they join the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/preview(config:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewWithConfig:delegate:"}],"url":"\/documentation\/hmssdk\/hmssdk\/preview(config:delegate:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/changeTrackState(mute:for:source:roles:completion:)":{"role":"symbol","title":"changeTrackState(mute:for:source:roles:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeTrackState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"roles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"To change the mute status of multiple tracks of specific kinds for every peer or for peers with certain roles."},{"type":"text","text":" "},{"type":"text","text":"Call changeTrackState(mute: true) to mute everybody’s audio and video."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(mute:for:source:roles:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssdk\/changetrackstate(mute:for:source:roles:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/getAuthTokenByRoomCode(_:userID:completion:)":{"role":"symbol","title":"getAuthTokenByRoomCode(_:userID:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAuthTokenByRoomCode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get authentication token using room short code"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getAuthTokenByRoomCode(_:userID:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAuthTokenByRoomCode:userID:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/getauthtokenbyroomcode(_:userid:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/changeRole(for:to:force:completion:)":{"role":"symbol","title":"changeRole(for:to:force:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeRole"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"force"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Requests a change of role for specified peer."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeRole(for:to:force:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeRoleFor:to:force:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/changerole(for:to:force:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/getSessionMetadata(completion:)":{"deprecated":true,"role":"symbol","title":"getSessionMetadata(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSessionMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Get session metadata"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getSessionMetadata(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSessionMetadataWithCompletion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/getsessionmetadata(completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/interactivityCenter":{"role":"symbol","title":"interactivityCenter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactivityCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSInteractivityCenter","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Returns the HMSInteractivityCenter for the current session."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/interactivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"interactivityCenter"}],"url":"\/documentation\/hmssdk\/hmssdk\/interactivitycenter"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/sendGroupMessage(type:message:roles:priority:completion:)":{"role":"symbol","title":"sendGroupMessage(type:message:roles:priority:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendGroupMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"roles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sends a message to the specified roles defined. All peers that belong to the specified roles will receive the message."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendGroupMessage(type:message:roles:priority:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendGroupMessageWithType:message:roles:priority:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/sendgroupmessage(type:message:roles:priority:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/removePeer(_:reason:completion:)":{"role":"symbol","title":"removePeer(_:reason:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePeer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Removes the specified peer from the current room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/removePeer(_:reason:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removePeer:reason:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/removepeer(_:reason:completion:)"},"doc://live.100ms.HMS/@M@HMSAnalyticsSDK@objc(pl)HMSAnalytics":{"type":"unresolvable","title":"HMSAnalytics","identifier":"doc:\/\/live.100ms.HMS\/@M@HMSAnalyticsSDK@objc(pl)HMSAnalytics"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/add(delegate:)":{"role":"symbol","title":"add(delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSUpdateListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSUpdateListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds another listener of SDK updates"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/add(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addWithDelegate:"}],"url":"\/documentation\/hmssdk\/hmssdk\/add(delegate:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/analyticsLevel":{"role":"symbol","title":"analyticsLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"analyticsLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventLevel","preciseIdentifier":"c:@E@HMSAnalyticsEventLevel"}],"abstract":[{"type":"text","text":"Sets the verbosity of analytics events"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/analyticsLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"analyticsLevel"}],"url":"\/documentation\/hmssdk\/hmssdk\/analyticslevel"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/stopRTMPAndRecording(completion:)":{"role":"symbol","title":"stopRTMPAndRecording(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRTMPAndRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Stop RTMP stream and room recording."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopRTMPAndRecording(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopRTMPAndRecordingWithCompletion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/stoprtmpandrecording(completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSSDK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/analyticsLevel","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/appGroup","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/interactivityCenter","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/localPeer","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/logger","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/remotePeers","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/roles","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/room","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/trackSettings"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/accept(changeRole:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/activateForScreenSharing()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/add(delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/cancelPreview()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/change(metadata:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/change(name:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeRole(for:to:force:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeRolesOfAllPeers(to:limitToRoles:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(for:mute:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/endRoom(lock:reason:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getAudioOutputDeviceList()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getAuthTokenByRoomCode(_:userID:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/getSessionMetadata(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/join(config:delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/leave(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/prepareForExternalAudioPlayback()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/preview(config:delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/preview(role:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/remove(delegate:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/removePeer(_:reason:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/resumeAfterExternalAudioPlayback()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/screenBroadcastAudioReceiverNode()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendBroadcastMessage(type:message:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendDirectMessage(type:message:peer:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendGroupMessage(type:message:roles:priority:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendHLSTimedMetadata(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/setSessionMetadata(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startAppScreenCapture(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startHLSStreaming(config:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/startRTMPOrRecording(config:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopAppScreenCapture(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopHLSStreaming(config:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/stopRTMPAndRecording(completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/switchAudioOutput(to:)"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/build(block:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/HMSAnalytics-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/@M@HMSAnalyticsSDK@objc(pl)HMSAnalytics"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1setSessionMetadata(_:completion:)\/title","value":"setSessionMetadata:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1setSessionMetadata(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSessionMetadata:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1switchAudioOutput(to:)\/title","value":"switchAudioOutputTo:error:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1switchAudioOutput(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchAudioOutputTo:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1cancelPreview()\/title","value":"cancelPreview"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1cancelPreview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1appGroup\/title","value":"appGroup"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1appGroup\/fragments","value":[{"kind":"identifier","text":"appGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1build(block:)\/title","value":"buildWithBlock:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1build(block:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildWithBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1logger\/title","value":"logger"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1logger\/fragments","value":[{"kind":"identifier","text":"logger"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1stopAppScreenCapture(completion:)\/title","value":"stopAppScreenCaptureWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1stopAppScreenCapture(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAppScreenCaptureWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendBroadcastMessage(type:message:priority:completion:)\/title","value":"sendBroadcastMessageWithType:message:priority:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendBroadcastMessage(type:message:priority:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendBroadcastMessageWithType:message:priority:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1startRTMPOrRecording(config:completion:)\/title","value":"startRTMPOrRecordingWithConfig:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1startRTMPOrRecording(config:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRTMPOrRecordingWithConfig:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1roles\/title","value":"roles"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1roles\/fragments","value":[{"kind":"identifier","text":"roles"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1changeTrackState(for:mute:completion:)\/title","value":"changeTrackStateFor:mute:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1changeTrackState(for:mute:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeTrackStateFor:mute:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1startHLSStreaming(config:completion:)\/title","value":"startHLSStreamingWithConfig:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1startHLSStreaming(config:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startHLSStreamingWithConfig:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1leave(_:)\/title","value":"leave:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1leave(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leave:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1localPeer\/title","value":"localPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1localPeer\/fragments","value":[{"kind":"identifier","text":"localPeer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1change(name:priority:completion:)\/title","value":"changeWithName:priority:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1change(name:priority:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeWithName:priority:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1accept(changeRole:completion:)\/title","value":"acceptWithChangeRole:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1accept(changeRole:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"acceptWithChangeRole:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendDirectMessage(type:message:peer:priority:completion:)\/title","value":"sendDirectMessageWithType:message:peer:priority:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendDirectMessage(type:message:peer:priority:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendDirectMessageWithType:message:peer:priority:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1trackSettings\/title","value":"trackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1trackSettings\/fragments","value":[{"kind":"identifier","text":"trackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1activateForScreenSharing()\/title","value":"activateForScreenSharing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1activateForScreenSharing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activateForScreenSharing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1endRoom(lock:reason:completion:)\/title","value":"endRoomWithLock:reason:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1endRoom(lock:reason:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRoomWithLock:reason:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendHLSTimedMetadata(_:completion:)\/title","value":"sendHLSTimedMetadata:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendHLSTimedMetadata(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendHLSTimedMetadata:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1preview(role:completion:)\/title","value":"previewWithRole:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1preview(role:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewWithRole:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1change(metadata:priority:completion:)\/title","value":"changeWithMetadata:priority:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1change(metadata:priority:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeWithMetadata:priority:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1room\/title","value":"room"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1room\/fragments","value":[{"kind":"identifier","text":"room"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1join(config:delegate:)\/title","value":"joinWithConfig:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1join(config:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinWithConfig:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1remove(delegate:)\/title","value":"removeWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1remove(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1getAudioOutputDeviceList()\/title","value":"getAudioOutputDeviceList"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1getAudioOutputDeviceList()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAudioOutputDeviceList"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1screenBroadcastAudioReceiverNode()\/title","value":"screenBroadcastAudioReceiverNodeAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1screenBroadcastAudioReceiverNode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1startAppScreenCapture(completion:)\/title","value":"startAppScreenCaptureWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1startAppScreenCapture(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAppScreenCaptureWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1remotePeers\/title","value":"remotePeers"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1remotePeers\/fragments","value":[{"kind":"identifier","text":"remotePeers"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1changeRolesOfAllPeers(to:limitToRoles:completion:)\/title","value":"changeRolesOfAllPeersTo:limitToRoles:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1changeRolesOfAllPeers(to:limitToRoles:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeRolesOfAllPeersTo:limitToRoles:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1prepareForExternalAudioPlayback()\/title","value":"prepareForExternalAudioPlayback"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1prepareForExternalAudioPlayback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForExternalAudioPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1stopHLSStreaming(config:completion:)\/title","value":"stopHLSStreamingWithConfig:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1stopHLSStreaming(config:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopHLSStreamingWithConfig:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1resumeAfterExternalAudioPlayback()\/title","value":"resumeAfterExternalAudioPlayback"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1resumeAfterExternalAudioPlayback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resumeAfterExternalAudioPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1preview(config:delegate:)\/title","value":"previewWithConfig:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1preview(config:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewWithConfig:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1getAuthTokenByRoomCode(_:userID:completion:)\/title","value":"getAuthTokenByRoomCode:userID:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1getAuthTokenByRoomCode(_:userID:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAuthTokenByRoomCode:userID:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1changeRole(for:to:force:completion:)\/title","value":"changeRoleFor:to:force:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1changeRole(for:to:force:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeRoleFor:to:force:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1getSessionMetadata(completion:)\/title","value":"getSessionMetadataWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1getSessionMetadata(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSessionMetadataWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1interactivityCenter\/title","value":"interactivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1interactivityCenter\/fragments","value":[{"kind":"identifier","text":"interactivityCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendGroupMessage(type:message:roles:priority:completion:)\/title","value":"sendGroupMessageWithType:message:roles:priority:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendGroupMessage(type:message:roles:priority:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendGroupMessageWithType:message:roles:priority:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1removePeer(_:reason:completion:)\/title","value":"removePeer:reason:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1removePeer(_:reason:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removePeer:reason:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1add(delegate:)\/title","value":"addWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1add(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1analyticsLevel\/title","value":"analyticsLevel"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1analyticsLevel\/fragments","value":[{"kind":"identifier","text":"analyticsLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1stopRTMPAndRecording(completion:)\/title","value":"stopRTMPAndRecordingWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1stopRTMPAndRecording(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopRTMPAndRecordingWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}