{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstransport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstransport"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/init(_:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/analyticsEventFactory","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/canUseMic","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/connectionState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/joined","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/logger","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/networkHealthConfig","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onFailure","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onLocalAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onLocalVideoStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onNotification","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRTCStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onReconnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onReconnecting","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRemoteAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRemoteVideoStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackDegraded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackPriority","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackRemoved","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackRestored","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publishedTracks","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sdkId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/simulcastEnabled"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/addTransciever(for:connection:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/analyticsService()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/cleanup()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/connect(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/dataChannelDidChangeState(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/establishRTCIfNeeded(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/join(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/leave(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/peerConnectionFactory()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/preview(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publish(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publishedTrackStates()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sendJoinEvent(_:error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sendRPCall(_:withIdentifier:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/setCanUseMic(_:trackSettings:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/track(for:streamId:shouldRegister:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/unpublish(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/willUnpublish(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"}],"title":"HMSTransport","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSTransport","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSTransport"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/publish(_:)":{"role":"symbol","title":"publish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publish:"}],"url":"\/documentation\/hmssdk\/hmstransport\/publish(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onTrackRestored":{"role":"symbol","title":"onTrackRestored","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTrackRestored"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackRestored","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTrackRestored"}],"url":"\/documentation\/hmssdk\/hmstransport\/ontrackrestored"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/track(for:streamId:shouldRegister:)":{"role":"symbol","title":"track(for:streamId:shouldRegister:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRegister"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/track(for:streamId:shouldRegister:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackFor:streamId:shouldRegister:"}],"url":"\/documentation\/hmssdk\/hmstransport\/track(for:streamid:shouldregister:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/join(_:completion:)":{"role":"symbol","title":"join(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSJoinParameters","preciseIdentifier":"c:objc(cs)HMSJoinParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSOperationStatusHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/join(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"join:completion:"}],"url":"\/documentation\/hmssdk\/hmstransport\/join(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onTrack":{"role":"symbol","title":"onTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTrack"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTrack"}],"url":"\/documentation\/hmssdk\/hmstransport\/ontrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/unpublish(_:completion:)":{"role":"symbol","title":"unpublish(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpublish"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSOperationStatusHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/unpublish(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unpublish:completion:"}],"url":"\/documentation\/hmssdk\/hmstransport\/unpublish(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/cleanup()":{"role":"symbol","title":"cleanup()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/cleanup()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cleanup"}],"url":"\/documentation\/hmssdk\/hmstransport\/cleanup()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/analyticsEventFactory":{"role":"symbol","title":"analyticsEventFactory","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"analyticsEventFactory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAnalyticsEventFactory","preciseIdentifier":"c:objc(pl)HMSAnalyticsEventFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/analyticsEventFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"analyticsEventFactory"}],"url":"\/documentation\/hmssdk\/hmstransport\/analyticseventfactory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/publishedTracks":{"role":"symbol","title":"publishedTracks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishedTracks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableSet","preciseIdentifier":"c:objc(cs)NSMutableSet"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publishedTracks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishedTracks"}],"url":"\/documentation\/hmssdk\/hmstransport\/publishedtracks"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onTrackDegraded":{"role":"symbol","title":"onTrackDegraded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTrackDegraded"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackDegraded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTrackDegraded"}],"url":"\/documentation\/hmssdk\/hmstransport\/ontrackdegraded"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/init(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWith:"}],"url":"\/documentation\/hmssdk\/hmstransport\/init(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/simulcastEnabled":{"role":"symbol","title":"simulcastEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulcastEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/simulcastEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"simulcastEnabled"}],"url":"\/documentation\/hmssdk\/hmstransport\/simulcastenabled"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/networkHealthConfig":{"role":"symbol","title":"networkHealthConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkHealthConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSNetworkHealthConfig","preciseIdentifier":"c:objc(cs)HMSNetworkHealthConfig"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/networkHealthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"networkHealthConfig"}],"url":"\/documentation\/hmssdk\/hmstransport\/networkhealthconfig"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/analyticsService()":{"role":"symbol","title":"analyticsService()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"analyticsService"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSAnalyticsService","preciseIdentifier":"c:objc(pl)HMSAnalyticsService"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/analyticsService()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"analyticsService"}],"url":"\/documentation\/hmssdk\/hmstransport\/analyticsservice()"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/dataChannelDidChangeState(_:)":{"role":"symbol","title":"dataChannelDidChangeState(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataChannelDidChangeState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCDataChannel","preciseIdentifier":"c:objc(cs)RTCDataChannel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/dataChannelDidChangeState(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataChannelDidChangeState:"}],"url":"\/documentation\/hmssdk\/hmstransport\/datachanneldidchangestate(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/setCanUseMic(_:trackSettings:)":{"role":"symbol","title":"setCanUseMic(_:trackSettings:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCanUseMic"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackSettings","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrackSettings"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/setCanUseMic(_:trackSettings:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCanUseMic:trackSettings:"}],"url":"\/documentation\/hmssdk\/hmstransport\/setcanusemic(_:tracksettings:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onNotification":{"role":"symbol","title":"onNotification","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onNotification"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onNotification"}],"url":"\/documentation\/hmssdk\/hmstransport\/onnotification"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/sendJoinEvent(_:error:)":{"role":"symbol","title":"sendJoinEvent(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendJoinEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sendJoinEvent(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendJoinEvent:error:"}],"url":"\/documentation\/hmssdk\/hmstransport\/sendjoinevent(_:error:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/leave(_:completion:)":{"role":"symbol","title":"leave(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSOperationStatusHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/leave(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leave:completion:"}],"url":"\/documentation\/hmssdk\/hmstransport\/leave(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onRemoteAudioStats":{"role":"symbol","title":"onRemoteAudioStats","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRemoteAudioStats"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSRemoteAudioStats","preciseIdentifier":"c:objc(cs)HMSRemoteAudioStats"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRemoteAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRemoteAudioStats"}],"url":"\/documentation\/hmssdk\/hmstransport\/onremoteaudiostats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/willUnpublish(_:)":{"role":"symbol","title":"willUnpublish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUnpublish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/willUnpublish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willUnpublish:"}],"url":"\/documentation\/hmssdk\/hmstransport\/willunpublish(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onFailure":{"role":"symbol","title":"onFailure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onFailure"}],"url":"\/documentation\/hmssdk\/hmstransport\/onfailure"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onReconnected":{"role":"symbol","title":"onReconnected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReconnected"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onReconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onReconnected"}],"url":"\/documentation\/hmssdk\/hmstransport\/onreconnected"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onLocalAudioStats":{"role":"symbol","title":"onLocalAudioStats","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocalAudioStats"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSLocalAudioStats","preciseIdentifier":"c:objc(cs)HMSLocalAudioStats"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onLocalAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onLocalAudioStats"}],"url":"\/documentation\/hmssdk\/hmstransport\/onlocalaudiostats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onTrackPriority":{"role":"symbol","title":"onTrackPriority","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTrackPriority"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTrackPriority"}],"url":"\/documentation\/hmssdk\/hmstransport\/ontrackpriority"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/frameworkInfo":{"role":"symbol","title":"frameworkInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/frameworkInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameworkInfo"}],"url":"\/documentation\/hmssdk\/hmstransport\/frameworkinfo"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onLocalVideoStats":{"role":"symbol","title":"onLocalVideoStats","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocalVideoStats"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSLocalVideoStats","preciseIdentifier":"c:objc(cs)HMSLocalVideoStats"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onLocalVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onLocalVideoStats"}],"url":"\/documentation\/hmssdk\/hmstransport\/onlocalvideostats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/publishedTrackStates()":{"role":"symbol","title":"publishedTrackStates()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishedTrackStates"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publishedTrackStates()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishedTrackStates"}],"url":"\/documentation\/hmssdk\/hmstransport\/publishedtrackstates()"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onRTCStats":{"role":"symbol","title":"onRTCStats","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRTCStats"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSRTCStatsReport","preciseIdentifier":"c:objc(cs)HMSRTCStatsReport"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRTCStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRTCStats"}],"url":"\/documentation\/hmssdk\/hmstransport\/onrtcstats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/establishRTCIfNeeded(_:)":{"role":"symbol","title":"establishRTCIfNeeded(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"establishRTCIfNeeded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSOperationStatusHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/establishRTCIfNeeded(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"establishRTCIfNeeded:"}],"url":"\/documentation\/hmssdk\/hmstransport\/establishrtcifneeded(_:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onTrackRemoved":{"role":"symbol","title":"onTrackRemoved","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTrackRemoved"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackRemoved","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTrackRemoved"}],"url":"\/documentation\/hmssdk\/hmstransport\/ontrackremoved"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/connectionState":{"role":"symbol","title":"connectionState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoConnectionState","preciseIdentifier":"c:@E@HMSVideoConnectionState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/connectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionState"}],"url":"\/documentation\/hmssdk\/hmstransport\/connectionstate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/addTransciever(for:connection:)":{"role":"symbol","title":"addTransciever(for:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTransciever"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/addTransciever(for:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addTranscieverForTrack:connection:"}],"url":"\/documentation\/hmssdk\/hmstransport\/addtransciever(for:connection:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport":{"role":"symbol","title":"HMSTransport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTransport"}],"url":"\/documentation\/hmssdk\/hmstransport"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/sendRPCall(_:withIdentifier:completion:)":{"role":"symbol","title":"sendRPCall(_:withIdentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendRPCall"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRequestCompletionHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSRequestCompletionHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sendRPCall(_:withIdentifier:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendRPCall:withIdentifier:completion:"}],"url":"\/documentation\/hmssdk\/hmstransport\/sendrpcall(_:withidentifier:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/sdkId":{"role":"symbol","title":"sdkId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sdkId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sdkId"}],"url":"\/documentation\/hmssdk\/hmstransport\/sdkid"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/canUseMic":{"role":"symbol","title":"canUseMic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canUseMic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/canUseMic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canUseMic"}],"url":"\/documentation\/hmssdk\/hmstransport\/canusemic"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/logger":{"role":"symbol","title":"logger","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logger"},{"kind":"text","text":": AnyObject?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logger"}],"url":"\/documentation\/hmssdk\/hmstransport\/logger"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/connect(_:completion:)":{"role":"symbol","title":"connect(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSJoinParameters","preciseIdentifier":"c:objc(cs)HMSJoinParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSOperationStatusHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/connect(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connect:completion:"}],"url":"\/documentation\/hmssdk\/hmstransport\/connect(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/joined":{"role":"symbol","title":"joined","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"joined"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/joined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joined"}],"url":"\/documentation\/hmssdk\/hmstransport\/joined"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onRemoteVideoStats":{"role":"symbol","title":"onRemoteVideoStats","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRemoteVideoStats"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSRemoteVideoStats","preciseIdentifier":"c:objc(cs)HMSRemoteVideoStats"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRemoteVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRemoteVideoStats"}],"url":"\/documentation\/hmssdk\/hmstransport\/onremotevideostats"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/onReconnecting":{"role":"symbol","title":"onReconnecting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReconnecting"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onReconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onReconnecting"}],"url":"\/documentation\/hmssdk\/hmstransport\/onreconnecting"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/peerConnectionFactory()":{"role":"symbol","title":"peerConnectionFactory()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionFactory"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"RTCPeerConnectionFactory","preciseIdentifier":"c:objc(cs)RTCPeerConnectionFactory"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/peerConnectionFactory()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnectionFactory"}],"url":"\/documentation\/hmssdk\/hmstransport\/peerconnectionfactory()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTransport/preview(_:completion:)":{"role":"symbol","title":"preview(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSJoinParameters","preciseIdentifier":"c:objc(cs)HMSJoinParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSOperationStatusHandler","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSOperationStatusHandler"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/preview(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preview:completion:"}],"url":"\/documentation\/hmssdk\/hmstransport\/preview(_:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSTransport"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSTransport"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSTransport"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/analyticsEventFactory","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/canUseMic","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/connectionState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/frameworkInfo","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/joined","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/logger","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/networkHealthConfig","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onFailure","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onLocalAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onLocalVideoStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onNotification","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRTCStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onReconnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onReconnecting","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRemoteAudioStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onRemoteVideoStats","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackDegraded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackPriority","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackRemoved","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/onTrackRestored","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publishedTracks","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sdkId","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/simulcastEnabled"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/addTransciever(for:connection:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/analyticsService()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/cleanup()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/connect(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/dataChannelDidChangeState(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/establishRTCIfNeeded(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/init(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/join(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/leave(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/peerConnectionFactory()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/preview(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publish(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/publishedTrackStates()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sendJoinEvent(_:error:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/sendRPCall(_:withIdentifier:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/setCanUseMic(_:trackSettings:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/track(for:streamId:shouldRegister:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/unpublish(_:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTransport\/willUnpublish(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTransport"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1publish(_:)\/title","value":"publish:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1publish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publish:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackRestored\/title","value":"onTrackRestored"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackRestored\/fragments","value":[{"kind":"identifier","text":"onTrackRestored"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1track(for:streamId:shouldRegister:)\/title","value":"trackFor:streamId:shouldRegister:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1track(for:streamId:shouldRegister:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackFor:streamId:shouldRegister:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1join(_:completion:)\/title","value":"join:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1join(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"join:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrack\/title","value":"onTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrack\/fragments","value":[{"kind":"identifier","text":"onTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1unpublish(_:completion:)\/title","value":"unpublish:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1unpublish(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unpublish:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1cleanup()\/title","value":"cleanup"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1cleanup()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cleanup"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1analyticsEventFactory\/title","value":"analyticsEventFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1analyticsEventFactory\/fragments","value":[{"kind":"identifier","text":"analyticsEventFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1publishedTracks\/title","value":"publishedTracks"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1publishedTracks\/fragments","value":[{"kind":"identifier","text":"publishedTracks"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackDegraded\/title","value":"onTrackDegraded"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackDegraded\/fragments","value":[{"kind":"identifier","text":"onTrackDegraded"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1init(_:)\/title","value":"initWith:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1init(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1simulcastEnabled\/title","value":"simulcastEnabled"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1simulcastEnabled\/fragments","value":[{"kind":"identifier","text":"simulcastEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1networkHealthConfig\/title","value":"networkHealthConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1networkHealthConfig\/fragments","value":[{"kind":"identifier","text":"networkHealthConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1analyticsService()\/title","value":"analyticsService"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1analyticsService()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"analyticsService"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1dataChannelDidChangeState(_:)\/title","value":"dataChannelDidChangeState:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1dataChannelDidChangeState(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataChannelDidChangeState:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1setCanUseMic(_:trackSettings:)\/title","value":"setCanUseMic:trackSettings:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1setCanUseMic(_:trackSettings:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCanUseMic:trackSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onNotification\/title","value":"onNotification"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onNotification\/fragments","value":[{"kind":"identifier","text":"onNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1sendJoinEvent(_:error:)\/title","value":"sendJoinEvent:error:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1sendJoinEvent(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendJoinEvent:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1leave(_:completion:)\/title","value":"leave:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1leave(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leave:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onRemoteAudioStats\/title","value":"onRemoteAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onRemoteAudioStats\/fragments","value":[{"kind":"identifier","text":"onRemoteAudioStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1willUnpublish(_:)\/title","value":"willUnpublish:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1willUnpublish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willUnpublish:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onFailure\/title","value":"onFailure"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onFailure\/fragments","value":[{"kind":"identifier","text":"onFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onReconnected\/title","value":"onReconnected"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onReconnected\/fragments","value":[{"kind":"identifier","text":"onReconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onLocalAudioStats\/title","value":"onLocalAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onLocalAudioStats\/fragments","value":[{"kind":"identifier","text":"onLocalAudioStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackPriority\/title","value":"onTrackPriority"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackPriority\/fragments","value":[{"kind":"identifier","text":"onTrackPriority"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1frameworkInfo\/title","value":"frameworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1frameworkInfo\/fragments","value":[{"kind":"identifier","text":"frameworkInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onLocalVideoStats\/title","value":"onLocalVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onLocalVideoStats\/fragments","value":[{"kind":"identifier","text":"onLocalVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1publishedTrackStates()\/title","value":"publishedTrackStates"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1publishedTrackStates()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publishedTrackStates"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onRTCStats\/title","value":"onRTCStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onRTCStats\/fragments","value":[{"kind":"identifier","text":"onRTCStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1establishRTCIfNeeded(_:)\/title","value":"establishRTCIfNeeded:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1establishRTCIfNeeded(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"establishRTCIfNeeded:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackRemoved\/title","value":"onTrackRemoved"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onTrackRemoved\/fragments","value":[{"kind":"identifier","text":"onTrackRemoved"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1connectionState\/title","value":"connectionState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1connectionState\/fragments","value":[{"kind":"identifier","text":"connectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1addTransciever(for:connection:)\/title","value":"addTranscieverForTrack:connection:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1addTransciever(for:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTranscieverForTrack:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/title","value":"HMSTransport"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport\/fragments","value":[{"kind":"identifier","text":"HMSTransport"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1sendRPCall(_:withIdentifier:completion:)\/title","value":"sendRPCall:withIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1sendRPCall(_:withIdentifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendRPCall:withIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1sdkId\/title","value":"sdkId"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1sdkId\/fragments","value":[{"kind":"identifier","text":"sdkId"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1canUseMic\/title","value":"canUseMic"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1canUseMic\/fragments","value":[{"kind":"identifier","text":"canUseMic"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1logger\/title","value":"logger"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1logger\/fragments","value":[{"kind":"identifier","text":"logger"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1connect(_:completion:)\/title","value":"connect:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1connect(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connect:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1joined\/title","value":"joined"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1joined\/fragments","value":[{"kind":"identifier","text":"joined"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onRemoteVideoStats\/title","value":"onRemoteVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onRemoteVideoStats\/fragments","value":[{"kind":"identifier","text":"onRemoteVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onReconnecting\/title","value":"onReconnecting"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1onReconnecting\/fragments","value":[{"kind":"identifier","text":"onReconnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1peerConnectionFactory()\/title","value":"peerConnectionFactory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1peerConnectionFactory()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnectionFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1preview(_:completion:)\/title","value":"preview:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTransport~1preview(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preview:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}