{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackUpdate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstrackupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstrackupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackAdded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDegraded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDescriptionChanged","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackMuted","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackRemoved","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackRestored","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackUnmuted"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackUpdate"}],"title":"HMSTrackUpdate","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@HMSSDK@E@HMSTrackUpdate","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdate"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackAdded":{"role":"symbol","title":"HMSTrackUpdate.trackAdded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackAdded"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackAdded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackAdded"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackadded"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmstrackupdate\/rawrepresentable-implementations"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmstrackupdate\/equatable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmstrackupdate\/init(rawvalue:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackDescriptionChanged":{"role":"symbol","title":"HMSTrackUpdate.trackDescriptionChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescriptionChanged"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDescriptionChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackdescriptionchanged"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackRestored":{"role":"symbol","title":"HMSTrackUpdate.trackRestored","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackRestored"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackRestored","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackRestored"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackrestored"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate":{"role":"symbol","title":"HMSTrackUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdate"}],"url":"\/documentation\/hmssdk\/hmstrackupdate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/description","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmstrackupdate\/description"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackRemoved":{"role":"symbol","title":"HMSTrackUpdate.trackRemoved","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackRemoved"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackRemoved","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackRemoved"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackremoved"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackDegraded":{"role":"symbol","title":"HMSTrackUpdate.trackDegraded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDegraded"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDegraded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackDegraded"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackdegraded"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackMuted":{"role":"symbol","title":"HMSTrackUpdate.trackMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackMuted"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackMuted"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackmuted"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackUnmuted":{"role":"symbol","title":"HMSTrackUpdate.trackUnmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackUnmuted"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackUnmuted"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackunmuted"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSTrackUpdate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSTrackUpdate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackAdded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDegraded","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDescriptionChanged","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackMuted","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackRemoved","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackRestored","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackUnmuted"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackAdded\/title","value":"HMSTrackUpdateTrackAdded"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackAdded\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackAdded"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackDescriptionChanged\/title","value":"HMSTrackUpdateTrackDescriptionChanged"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackDescriptionChanged\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackRestored\/title","value":"HMSTrackUpdateTrackRestored"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackRestored\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackRestored"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate\/title","value":"HMSTrackUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackRemoved\/title","value":"HMSTrackUpdateTrackRemoved"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackRemoved\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackRemoved"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackDegraded\/title","value":"HMSTrackUpdateTrackDegraded"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackDegraded\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackDegraded"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackMuted\/title","value":"HMSTrackUpdateTrackMuted"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackMuted\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackUnmuted\/title","value":"HMSTrackUpdateTrackUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackUnmuted\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackUnmuted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}