{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtility"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsutility"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsutility"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/codec(from:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/codecString(from:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/kindString(from:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/messageRetryDelay()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/shouldRetryServerErrorCode(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtility"}],"title":"HMSUtility","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSUtility","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSUtility"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtility/kindString(from:)":{"role":"symbol","title":"kindString(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"kindString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/kindString(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kindStringFrom:"}],"url":"\/documentation\/hmssdk\/hmsutility\/kindstring(from:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtility/shouldRetryServerErrorCode(_:)":{"role":"symbol","title":"shouldRetryServerErrorCode(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRetryServerErrorCode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/shouldRetryServerErrorCode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldRetryServerErrorCode:"}],"url":"\/documentation\/hmssdk\/hmsutility\/shouldretryservererrorcode(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtility":{"role":"symbol","title":"HMSUtility","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtility"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUtility"}],"url":"\/documentation\/hmssdk\/hmsutility"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtility/codec(from:)":{"role":"symbol","title":"codec(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/codec(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecFrom:"}],"url":"\/documentation\/hmssdk\/hmsutility\/codec(from:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtility/codecString(from:)":{"role":"symbol","title":"codecString(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/codecString(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecStringFrom:"}],"url":"\/documentation\/hmssdk\/hmsutility\/codecstring(from:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtility/messageRetryDelay()":{"role":"symbol","title":"messageRetryDelay()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageRetryDelay"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/messageRetryDelay()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageRetryDelay"}],"url":"\/documentation\/hmssdk\/hmsutility\/messageretrydelay()"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSUtility"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSUtility"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSUtility"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/codec(from:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/codecString(from:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/kindString(from:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/messageRetryDelay()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtility\/shouldRetryServerErrorCode(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtility"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1kindString(from:)\/title","value":"kindStringFrom:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1kindString(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"kindStringFrom:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1shouldRetryServerErrorCode(_:)\/title","value":"shouldRetryServerErrorCode:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1shouldRetryServerErrorCode(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shouldRetryServerErrorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility\/title","value":"HMSUtility"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility\/fragments","value":[{"kind":"identifier","text":"HMSUtility"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1codec(from:)\/title","value":"codecFrom:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1codec(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"codecFrom:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1codecString(from:)\/title","value":"codecStringFrom:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1codecString(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"codecStringFrom:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1messageRetryDelay()\/title","value":"messageRetryDelay"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtility~1messageRetryDelay()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"messageRetryDelay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}