{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtilities"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsutilities"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsutilities"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAllAudioTracks(in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAllVideoTracks(in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAudioTrack(for:in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getDevices()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getPeer(for:in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getTrack(for:in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getVideoTrack(for:in:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtilities"}],"title":"HMSUtilities","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@HMSSDK@objc(cs)HMSUtilities","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSUtilities"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getAudioTrack(for:in:)":{"role":"symbol","title":"getAudioTrack(for:in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSAudioTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAudioTrack(for:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAudioTrackFor:in:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getaudiotrack(for:in:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsutilities\/init"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getAllVideoTracks(in:)":{"role":"symbol","title":"getAllVideoTracks(in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllVideoTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrack"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAllVideoTracks(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAllVideoTracksIn:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getallvideotracks(in:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getAllAudioTracks(in:)":{"role":"symbol","title":"getAllAudioTracks(in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllAudioTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"HMSAudioTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioTrack"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAllAudioTracks(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAllAudioTracksIn:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getallaudiotracks(in:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getDevices()":{"role":"symbol","title":"getDevices()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDevices"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"HMSDevice","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSDevice"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getDevices()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDevices"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getdevices()"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getVideoTrack(for:in:)":{"role":"symbol","title":"getVideoTrack(for:in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSVideoTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getVideoTrack(for:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVideoTrackFor:in:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getvideotrack(for:in:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities":{"role":"symbol","title":"HMSUtilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtilities"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUtilities"}],"url":"\/documentation\/hmssdk\/hmsutilities"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getPeer(for:in:)":{"role":"symbol","title":"getPeer(for:in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPeer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getPeer(for:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPeerFor:in:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/getpeer(for:in:)"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUtilities/getTrack(for:in:)":{"role":"symbol","title":"getTrack(for:in:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSTrack","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getTrack(for:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getTrackFor:in:"}],"url":"\/documentation\/hmssdk\/hmsutilities\/gettrack(for:in:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSUtilities"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSUtilities"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSUtilities"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAllAudioTracks(in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAllVideoTracks(in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getAudioTrack(for:in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getDevices()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getPeer(for:in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getTrack(for:in:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUtilities\/getVideoTrack(for:in:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUtilities"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getAudioTrack(for:in:)\/title","value":"getAudioTrackFor:in:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getAudioTrack(for:in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAudioTrackFor:in:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getAllVideoTracks(in:)\/title","value":"getAllVideoTracksIn:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getAllVideoTracks(in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAllVideoTracksIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getAllAudioTracks(in:)\/title","value":"getAllAudioTracksIn:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getAllAudioTracks(in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getAllAudioTracksIn:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getDevices()\/title","value":"getDevices"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getDevices()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDevices"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getVideoTrack(for:in:)\/title","value":"getVideoTrackFor:in:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getVideoTrack(for:in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getVideoTrackFor:in:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities\/title","value":"HMSUtilities"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities\/fragments","value":[{"kind":"identifier","text":"HMSUtilities"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getPeer(for:in:)\/title","value":"getPeerFor:in:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getPeer(for:in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getPeerFor:in:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getTrack(for:in:)\/title","value":"getTrackFor:in:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUtilities~1getTrack(for:in:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getTrackFor:in:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}