{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideoview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideoview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCoding","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/objc(pl)CALayerDelegate","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/s8SendableP","doc:\/\/live.100ms.HMS\/objc(pl)UIAccessibilityIdentification","doc:\/\/live.100ms.HMS\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/live.100ms.HMS\/objc(pl)UIAppearance","doc:\/\/live.100ms.HMS\/objc(pl)UIAppearanceContainer","doc:\/\/live.100ms.HMS\/objc(pl)UICoordinateSpace","doc:\/\/live.100ms.HMS\/objc(pl)UIDynamicItem","doc:\/\/live.100ms.HMS\/objc(pl)UIFocusEnvironment","doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItem","doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItemContainer","doc:\/\/live.100ms.HMS\/objc(pl)UILargeContentViewerItem","doc:\/\/live.100ms.HMS\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/live.100ms.HMS\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/live.100ms.HMS\/objc(pl)UIResponderStandardEditActions","doc:\/\/live.100ms.HMS\/objc(pl)UITraitEnvironment","doc:\/\/live.100ms.HMS\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/disableAutoSimulcastLayerSelect","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/isZoomAndPanEnabled","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/mirror","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/videoContentMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/captureSnapshot()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/setVideoTrack(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/videoTrack()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoView"}],"title":"HMSVideoView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSVideoView","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVideoView"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItem"},"doc://live.100ms.HMS/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIDynamicItem"},"doc://live.100ms.HMS/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIPasteConfigurationSupporting"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/setVideoTrack(_:)":{"role":"symbol","title":"setVideoTrack(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/setVideoTrack(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoTrack:"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/setvideotrack(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/disableAutoSimulcastLayerSelect":{"role":"symbol","title":"disableAutoSimulcastLayerSelect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutoSimulcastLayerSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/disableAutoSimulcastLayerSelect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableAutoSimulcastLayerSelect"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/disableautosimulcastlayerselect"},"doc://live.100ms.HMS/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UITraitEnvironment"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIFocusEnvironment"},"doc://live.100ms.HMS/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSCoding"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/captureSnapshot()":{"role":"symbol","title":"captureSnapshot()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureSnapshot"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/captureSnapshot()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureSnapshot"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/capturesnapshot()"},"doc://live.100ms.HMS/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView":{"role":"symbol","title":"HMSVideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoView"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoView"}],"url":"\/documentation\/hmssdk\/hmsvideoview"},"doc://live.100ms.HMS/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)CALayerDelegate"},"doc://live.100ms.HMS/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIAppearance"},"doc://live.100ms.HMS/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UILargeContentViewerItem"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/mirror":{"role":"symbol","title":"mirror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/mirror","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mirror"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/mirror"},"doc://live.100ms.HMS/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIResponderStandardEditActions"},"doc://live.100ms.HMS/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UICoordinateSpace"},"doc://live.100ms.HMS/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)UIView"},"doc://live.100ms.HMS/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIFocusItemContainer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/videoTrack()":{"role":"symbol","title":"videoTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSVideoTrack","preciseIdentifier":"c:objc(cs)HMSVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/videoTrack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoTrack"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/videotrack()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/videoContentMode":{"role":"symbol","title":"videoContentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoContentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/videoContentMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoContentMode"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/videocontentmode"},"doc://live.100ms.HMS/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIAppearanceContainer"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIUserActivityRestoring"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)UIAccessibilityIdentification"},"doc://live.100ms.HMS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/live.100ms.HMS\/s8SendableP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoView/isZoomAndPanEnabled":{"role":"symbol","title":"isZoomAndPanEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isZoomAndPanEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/isZoomAndPanEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isZoomAndPanEnabled"}],"url":"\/documentation\/hmssdk\/hmsvideoview\/iszoomandpanenabled"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSVideoView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVideoView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSVideoView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/disableAutoSimulcastLayerSelect","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/isZoomAndPanEnabled","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/mirror","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/videoContentMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/captureSnapshot()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/setVideoTrack(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoView\/videoTrack()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1setVideoTrack(_:)\/title","value":"setVideoTrack:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1setVideoTrack(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoTrack:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1disableAutoSimulcastLayerSelect\/title","value":"disableAutoSimulcastLayerSelect"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1disableAutoSimulcastLayerSelect\/fragments","value":[{"kind":"identifier","text":"disableAutoSimulcastLayerSelect"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1captureSnapshot()\/title","value":"captureSnapshot"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1captureSnapshot()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureSnapshot"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView\/title","value":"HMSVideoView"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView\/fragments","value":[{"kind":"identifier","text":"HMSVideoView"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1mirror\/title","value":"mirror"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1mirror\/fragments","value":[{"kind":"identifier","text":"mirror"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1videoTrack()\/title","value":"videoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1videoTrack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"videoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1videoContentMode\/title","value":"videoContentMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1videoContentMode\/fragments","value":[{"kind":"identifier","text":"videoContentMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1isZoomAndPanEnabled\/title","value":"isZoomAndPanEnabled"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoView~1isZoomAndPanEnabled\/fragments","value":[{"kind":"identifier","text":"isZoomAndPanEnabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}