{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoConnectionState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideoconnectionstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideoconnectionstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH","doc:\/\/live.100ms.HMS\/SY","doc:\/\/live.100ms.HMS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connecting","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/disconnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/failed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/ready"]},{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/Equatable-Implementations","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoConnectionState"}],"title":"HMSVideoConnectionState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@HMSVideoConnectionState","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVideoConnectionState"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/rawrepresentable-implementations"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/failed":{"role":"symbol","title":"HMSVideoConnectionState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateFailed"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/failed"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/connecting":{"role":"symbol","title":"HMSVideoConnectionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/connecting"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/live.100ms.HMS\/SY"},"doc://live.100ms.HMS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/live.100ms.HMS\/s8SendableP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState":{"role":"symbol","title":"HMSVideoConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoConnectionState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoConnectionState"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/equatable-implementations"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/connected":{"role":"symbol","title":"HMSVideoConnectionState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnected"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/connected"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/ready":{"role":"symbol","title":"HMSVideoConnectionState.ready","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/ready","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateReady"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/ready"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/disconnected":{"role":"symbol","title":"HMSVideoConnectionState.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/disconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSVideoConnectionStateDisconnected"}],"url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/disconnected"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoConnectionState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmsvideoconnectionstate\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"HMSVideoConnectionState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVideoConnectionState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSVideoConnectionState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/connecting","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/disconnected","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/failed","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoConnectionState\/ready"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1failed\/title","value":"kHMSVideoConnectionStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1failed\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1connecting\/title","value":"kHMSVideoConnectionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1connecting\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState\/title","value":"HMSVideoConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState\/fragments","value":[{"kind":"identifier","text":"HMSVideoConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1connected\/title","value":"kHMSVideoConnectionStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1connected\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1ready\/title","value":"kHMSVideoConnectionStateReady"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1ready\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateReady"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1disconnected\/title","value":"kHMSVideoConnectionStateDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoConnectionState~1disconnected\/fragments","value":[{"kind":"identifier","text":"kHMSVideoConnectionStateDisconnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}