{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettingsbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettingsbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraFacing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraFocusMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraOrientationLock","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/trackDescription","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/videoPlugins"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"title":"HMSVideoTrackSettingsBuilder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSVideoTrackSettingsBuilder","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/videoPlugins":{"role":"symbol","title":"videoPlugins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/videoPlugins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoPlugins"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/videoplugins"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/init()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/cameraFocusMode":{"role":"symbol","title":"cameraFocusMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFocusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraFocusMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFocusMode"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/camerafocusmode"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/cameraOrientationLock":{"role":"symbol","title":"cameraOrientationLock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOrientationLock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraOrientationLock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraOrientationLock"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/cameraorientationlock"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/cameraFacing":{"role":"symbol","title":"cameraFacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/camerafacing"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder":{"role":"symbol","title":"HMSVideoTrackSettingsBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/initialMuteState":{"role":"symbol","title":"initialMuteState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/initialMuteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialMuteState"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/initialmutestate"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettingsBuilder/trackDescription":{"role":"symbol","title":"trackDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/trackDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackDescription"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettingsbuilder\/trackdescription"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSVideoTrackSettingsBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraFacing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraFocusMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/cameraOrientationLock","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/trackDescription","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/videoPlugins"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettingsBuilder\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1videoPlugins\/title","value":"videoPlugins"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1videoPlugins\/fragments","value":[{"kind":"identifier","text":"videoPlugins"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1cameraFocusMode\/title","value":"cameraFocusMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1cameraFocusMode\/fragments","value":[{"kind":"identifier","text":"cameraFocusMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1cameraOrientationLock\/title","value":"cameraOrientationLock"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1cameraOrientationLock\/fragments","value":[{"kind":"identifier","text":"cameraOrientationLock"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1cameraFacing\/title","value":"cameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1cameraFacing\/fragments","value":[{"kind":"identifier","text":"cameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder\/title","value":"HMSVideoTrackSettingsBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettingsBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1initialMuteState\/title","value":"initialMuteState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1initialMuteState\/fragments","value":[{"kind":"identifier","text":"initialMuteState"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1trackDescription\/title","value":"trackDescription"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettingsBuilder~1trackDescription\/fragments","value":[{"kind":"identifier","text":"trackDescription"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}