{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCopying","doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(builder:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFacing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFocusMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraOrientationLock","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/codec","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/maxBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/maxFrameRate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/resolution","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/simulcastSettings","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/trackDescription","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/videoPlugins"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/build(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"title":"HMSVideoTrackSettings","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSVideoTrackSettings","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/videoPlugins":{"role":"symbol","title":"videoPlugins","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/videoPlugins","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoPlugins"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/videoplugins"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/cameraFocusMode":{"role":"symbol","title":"cameraFocusMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFocusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFocusMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFocusMode"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/camerafocusmode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)":{"role":"symbol","title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFocusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraOrientationLock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:simulcastsettings:trackdescription:initialmutestate:camerafocusmode:cameraorientationlock:videoplugins:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/maxFrameRate":{"role":"symbol","title":"maxFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/maxFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxFrameRate"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/maxframerate"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/resolution":{"role":"symbol","title":"resolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/resolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resolution"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/resolution"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)":{"role":"symbol","title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFocusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:simulcastsettings:trackdescription:initialmutestate:camerafocusmode:videoplugins:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/simulcastSettings":{"role":"symbol","title":"simulcastSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/simulcastSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"simulcastSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/simulcastsettings"},"doc://live.100ms.HMS/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSCopying"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/maxBitrate":{"role":"symbol","title":"maxBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/maxBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxBitrate"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/maxbitrate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)":{"role":"symbol","title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:trackdescription:videoplugins:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/trackDescription":{"role":"symbol","title":"trackDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/trackDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackDescription"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/trackdescription"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)":{"role":"symbol","title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:simulcastsettings:trackdescription:initialmutestate:videoplugins:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(builder:)":{"role":"symbol","title":"init(builder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"builder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoTrackSettingsBuilder","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettingsBuilder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(builder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBuilder:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(builder:)"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/cameraFacing":{"role":"symbol","title":"cameraFacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/camerafacing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings":{"role":"symbol","title":"HMSVideoTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/codec":{"role":"symbol","title":"codec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/codec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codec"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/codec"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)":{"role":"symbol","title":"init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"codec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCodec","preciseIdentifier":"c:@E@HMSCodec"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"simulcastSettings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSSimulcastLayerSettings","preciseIdentifier":"c:objc(cs)HMSSimulcastLayerSettings"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"videoPlugins"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSVideoPlugin","preciseIdentifier":"c:objc(cs)HMSVideoPlugin"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init(codec:resolution:maxbitrate:maxframerate:camerafacing:simulcastsettings:trackdescription:videoplugins:)"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/build(_:)":{"role":"symbol","title":"build(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"HMSVideoTrackSettingsBuilder","preciseIdentifier":"c:objc(cs)HMSVideoTrackSettingsBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/build(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build:"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/build(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/init()"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/cameraOrientationLock":{"role":"symbol","title":"cameraOrientationLock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOrientationLock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientationMask","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraOrientationLock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraOrientationLock"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/cameraorientationlock"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/initialMuteState":{"role":"symbol","title":"initialMuteState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/initialMuteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialMuteState"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/initialmutestate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFacing","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFocusMode","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraOrientationLock","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/codec","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/initialMuteState","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/maxBitrate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/maxFrameRate","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/resolution","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/simulcastSettings","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/trackDescription","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/videoPlugins"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(builder:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)"]},{"title":"Type Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/build(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1videoPlugins\/title","value":"videoPlugins"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1videoPlugins\/fragments","value":[{"kind":"identifier","text":"videoPlugins"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraFocusMode\/title","value":"cameraFocusMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraFocusMode\/fragments","value":[{"kind":"identifier","text":"cameraFocusMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:cameraOrientationLock:videoPlugins:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1maxFrameRate\/title","value":"maxFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1maxFrameRate\/fragments","value":[{"kind":"identifier","text":"maxFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1resolution\/title","value":"resolution"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1resolution\/fragments","value":[{"kind":"identifier","text":"resolution"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:cameraFocusMode:videoPlugins:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1simulcastSettings\/title","value":"simulcastSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1simulcastSettings\/fragments","value":[{"kind":"identifier","text":"simulcastSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1maxBitrate\/title","value":"maxBitrate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1maxBitrate\/fragments","value":[{"kind":"identifier","text":"maxBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:trackDescription:videoPlugins:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1trackDescription\/title","value":"trackDescription"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1trackDescription\/fragments","value":[{"kind":"identifier","text":"trackDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:initialMuteState:videoPlugins:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(builder:)\/title","value":"initWithBuilder:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(builder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBuilder:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraFacing\/title","value":"cameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraFacing\/fragments","value":[{"kind":"identifier","text":"cameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1codec\/title","value":"codec"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1codec\/fragments","value":[{"kind":"identifier","text":"codec"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)\/title","value":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init(codec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCodec:resolution:maxBitrate:maxFrameRate:cameraFacing:simulcastSettings:trackDescription:videoPlugins:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1build(_:)\/title","value":"build:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1build(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"build:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraOrientationLock\/title","value":"cameraOrientationLock"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraOrientationLock\/fragments","value":[{"kind":"identifier","text":"cameraOrientationLock"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1initialMuteState\/title","value":"initialMuteState"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1initialMuteState\/fragments","value":[{"kind":"identifier","text":"initialMuteState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}