{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/addSink(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/isDegraded()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/removeSink(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"title":"HMSVideoTrack","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSVideoTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack/isDegraded()":{"role":"symbol","title":"isDegraded()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDegraded"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/isDegraded()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDegraded"}],"url":"\/documentation\/hmssdk\/hmsvideotrack\/isdegraded()"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrack":{"role":"symbol","title":"HMSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrack"}],"abstract":[{"type":"text","text":"A track represents either the audio or video that makes up a stream"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrack"}],"url":"\/documentation\/hmssdk\/hmstrack"},"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack":{"role":"symbol","title":"HMSLocalVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteVideoTrack":{"role":"symbol","title":"HMSRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsremotevideotrack"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack":{"role":"symbol","title":"HMSVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrack"}],"url":"\/documentation\/hmssdk\/hmsvideotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack/addSink(_:)":{"role":"symbol","title":"addSink(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addSink"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/addSink(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addSink:"}],"url":"\/documentation\/hmssdk\/hmsvideotrack\/addsink(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalScreenTrack":{"role":"symbol","title":"HMSLocalScreenTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalScreenTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalScreenTrack"}],"url":"\/documentation\/hmssdk\/hmslocalscreentrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrack/removeSink(_:)":{"role":"symbol","title":"removeSink(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeSink"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/removeSink(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeSink:"}],"url":"\/documentation\/hmssdk\/hmsvideotrack\/removesink(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSVideoTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrack"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSVideoTrack"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/addSink(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/isDegraded()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrack\/removeSink(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalScreenTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteVideoTrack"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrack","preciseIdentifier":"c:objc(cs)HMSTrack","text":"HMSTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack~1isDegraded()\/title","value":"isDegraded"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack~1isDegraded()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isDegraded"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/title","value":"HMSTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrack\/fragments","value":[{"kind":"identifier","text":"HMSTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack\/title","value":"HMSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/title","value":"HMSVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack~1addSink(_:)\/title","value":"addSink:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack~1addSink(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addSink:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalScreenTrack\/title","value":"HMSLocalScreenTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalScreenTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalScreenTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack~1removeSink(_:)\/title","value":"removeSink:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrack~1removeSink(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeSink:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}