{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideocapturer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideocapturer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/live.100ms.HMS\/objc(pl)NSObject","doc:\/\/live.100ms.HMS\/s7CVarArgP","doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP","doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP","doc:\/\/live.100ms.HMS\/SQ","doc:\/\/live.100ms.HMS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/init(capturer:resolution:frameRate:shim:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFocusMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFacing()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/captureImageAtMaxSupportedResolution(withFlash:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/captureResolution()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/frameRate()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/isCapturing()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/modifyCaptureDevice(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setCameraFacing(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setFocus(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setFrameRate(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setResolution(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/startCapture()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/stopCapture()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/switchCamera()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"}],"title":"HMSVideoCapturer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)HMSVideoCapturer","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSVideoCapturer"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/live.100ms.HMS\/objc(pl)NSObject"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/switchCamera()":{"role":"symbol","title":"switchCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchCamera"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/switchCamera()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchCamera"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/switchcamera()"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/setFrameRate(_:)":{"role":"symbol","title":"setFrameRate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameRate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setFrameRate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFrameRate:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/setframerate(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/stopCapture()":{"role":"symbol","title":"stopCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/stopCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/stopcapture()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/setResolution(_:)":{"role":"symbol","title":"setResolution(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setResolution"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setResolution(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setResolution:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/setresolution(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer":{"role":"symbol","title":"HMSVideoCapturer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoCapturer"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer"},"doc://live.100ms.HMS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s23CustomStringConvertibleP"},"doc://live.100ms.HMS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/live.100ms.HMS\/s28CustomDebugStringConvertibleP"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/modifyCaptureDevice(_:)":{"role":"symbol","title":"modifyCaptureDevice(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifyCaptureDevice"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/modifyCaptureDevice(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/modifycapturedevice(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/frameRate()":{"role":"symbol","title":"frameRate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/frameRate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameRate"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/framerate()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/captureImageAtMaxSupportedResolution(withFlash:completion:)":{"role":"symbol","title":"captureImageAtMaxSupportedResolution(withFlash:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFlash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/captureImageAtMaxSupportedResolution(withFlash:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/captureimageatmaxsupportedresolution(withflash:completion:)"},"doc://live.100ms.HMS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/live.100ms.HMS\/SQ"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/setFocus(_:)":{"role":"symbol","title":"setFocus(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFocus"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setFocus(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFocus:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/setfocus(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/init(capturer:resolution:frameRate:shim:)":{"role":"symbol","title":"init(capturer:resolution:frameRate:shim:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"capturer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCVideoCapturer","preciseIdentifier":"c:objc(cs)RTCVideoCapturer"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"resolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shim"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSVideoCapturerShim"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/init(capturer:resolution:frameRate:shim:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCapturer:resolution:frameRate:shim:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/init(capturer:resolution:framerate:shim:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/cameraFacing()":{"role":"symbol","title":"cameraFacing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFacing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/camerafacing()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/setCameraFacing(_:)":{"role":"symbol","title":"setCameraFacing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraFacing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setCameraFacing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCameraFacing:"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/setcamerafacing(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/cameraFocusMode":{"role":"symbol","title":"cameraFocusMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFocusMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFocusMode","preciseIdentifier":"c:@E@HMSCameraFocusMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFocusMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFocusMode"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/camerafocusmode"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/captureResolution()":{"role":"symbol","title":"captureResolution()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureResolution"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSVideoResolution","preciseIdentifier":"c:HMSCommonDefs.h@T@HMSVideoResolution"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/captureResolution()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureResolution"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/captureresolution()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/startCapture()":{"role":"symbol","title":"startCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/startCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/startcapture()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoCapturer/isCapturing()":{"role":"symbol","title":"isCapturing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/isCapturing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCapturing"}],"url":"\/documentation\/hmssdk\/hmsvideocapturer\/iscapturing()"},"doc://live.100ms.HMS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/live.100ms.HMS\/s7CVarArgP"},"doc://live.100ms.HMS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/live.100ms.HMS\/SH"},"doc://live.100ms.HMS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/live.100ms.HMS\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"HMSVideoCapturer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSVideoCapturer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"HMSVideoCapturer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFocusMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/cameraFacing()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/captureImageAtMaxSupportedResolution(withFlash:completion:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/captureResolution()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/frameRate()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/init(capturer:resolution:frameRate:shim:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/isCapturing()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/modifyCaptureDevice(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setCameraFacing(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setFocus(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setFrameRate(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/setResolution(_:)","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/startCapture()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/stopCapture()","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoCapturer\/switchCamera()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/live.100ms.HMS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoCapturer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1switchCamera()\/title","value":"switchCamera"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1switchCamera()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setFrameRate(_:)\/title","value":"setFrameRate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setFrameRate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrameRate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1stopCapture()\/title","value":"stopCapture"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1stopCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setResolution(_:)\/title","value":"setResolution:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setResolution(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setResolution:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/title","value":"HMSVideoCapturer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer\/fragments","value":[{"kind":"identifier","text":"HMSVideoCapturer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1modifyCaptureDevice(_:)\/title","value":"modifyCaptureDeviceUsingBlock:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1modifyCaptureDevice(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifyCaptureDeviceUsingBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1frameRate()\/title","value":"frameRate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1frameRate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"frameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1captureImageAtMaxSupportedResolution(withFlash:completion:)\/title","value":"captureImageAtMaxSupportedResolutionWithFlash:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1captureImageAtMaxSupportedResolution(withFlash:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setFocus(_:)\/title","value":"setFocus:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setFocus(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFocus:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1init(capturer:resolution:frameRate:shim:)\/title","value":"initWithCapturer:resolution:frameRate:shim:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1init(capturer:resolution:frameRate:shim:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCapturer:resolution:frameRate:shim:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1cameraFacing()\/title","value":"cameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1cameraFacing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setCameraFacing(_:)\/title","value":"setCameraFacing:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1setCameraFacing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraFacing:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1cameraFocusMode\/title","value":"cameraFocusMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1cameraFocusMode\/fragments","value":[{"kind":"identifier","text":"cameraFocusMode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1captureResolution()\/title","value":"captureResolution"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1captureResolution()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1startCapture()\/title","value":"startCapture"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1startCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1isCapturing()\/title","value":"isCapturing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoCapturer~1isCapturing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isCapturing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}