{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleChoice"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollquestiontype\/multiplechoice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollquestiontype\/multiplechoice"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/multipleChoice","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The question allows for multiple choice answers."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleChoice"}],"title":"HMSPollQuestionType.multipleChoice","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPollQuestionType@HMSPollQuestionTypeMultipleChoice","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType/multipleChoice":{"role":"symbol","title":"HMSPollQuestionType.multipleChoice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleChoice"}],"abstract":[{"type":"text","text":"The question allows for multiple choice answers."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType\/multipleChoice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype\/multiplechoice"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionType":{"role":"symbol","title":"HMSPollQuestionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionType"}],"abstract":[{"type":"text","text":"Represents the type of a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionType"}],"url":"\/documentation\/hmssdk\/hmspollquestiontype"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollQuestionTypeMultipleChoice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1multipleChoice\/title","value":"HMSPollQuestionTypeMultipleChoice"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType~1multipleChoice\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionTypeMultipleChoice"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType\/title","value":"HMSPollQuestionType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionType\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}