{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode","text":"HMSAudioMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/audiomode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/audiomode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioMode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode"}],"title":"audioMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSAudioTrackSettingsBuilder(py)audioMode","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"audioMode"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder":{"role":"symbol","title":"HMSAudioTrackSettingsBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettingsBuilder/audioMode":{"role":"symbol","title":"audioMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettingsBuilder\/audioMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioMode"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettingsbuilder\/audiomode"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioMode":{"role":"symbol","title":"HMSAudioMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioMode"}],"url":"\/documentation\/hmssdk\/hmsaudiomode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMode","preciseIdentifier":"c:@E@HMSAudioMode","text":"HMSAudioMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder\/title","value":"HMSAudioTrackSettingsBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettingsBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1audioMode\/title","value":"audioMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettingsBuilder~1audioMode\/fragments","value":[{"kind":"identifier","text":"audioMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}