{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactivityCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter","text":"HMSInteractivityCenter"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/interactivitycenter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/interactivitycenter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/interactivityCenter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the HMSInteractivityCenter for the current session."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactivityCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSInteractivityCenter","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter"}],"title":"interactivityCenter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(py)interactivityCenter","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"interactivityCenter"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter":{"role":"symbol","title":"HMSInteractivityCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Provides interactivity features."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSInteractivityCenter"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/interactivityCenter":{"role":"symbol","title":"interactivityCenter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactivityCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSInteractivityCenter","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Returns the HMSInteractivityCenter for the current session."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/interactivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"interactivityCenter"}],"url":"\/documentation\/hmssdk\/hmssdk\/interactivitycenter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"interactivityCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"interactivityCenter"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter","text":"HMSInteractivityCenter"},{"kind":"text","text":" * "},{"kind":"identifier","text":"interactivityCenter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/title","value":"HMSInteractivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/fragments","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1interactivityCenter\/title","value":"interactivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1interactivityCenter\/fragments","value":[{"kind":"identifier","text":"interactivityCenter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}