{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendHLSTimedMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSTimedMetadata","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSTimedMetadata","text":"HMSHLSTimedMetadata"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of HMSHLSTimedMetadata objects"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler to be invoked when the request succeeds or fails with an error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/sendhlstimedmetadata(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/sendhlstimedmetadata(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendHLSTimedMetadata(_:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Send HLS timed metadata"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendHLSTimedMetadata"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSHLSTimedMetadata","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSTimedMetadata"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"sendHLSTimedMetadata(_:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(im)sendHLSTimedMetadata:completion:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendHLSTimedMetadata:completion:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/sendHLSTimedMetadata(_:completion:)":{"role":"symbol","title":"sendHLSTimedMetadata(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendHLSTimedMetadata"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSHLSTimedMetadata","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSTimedMetadata"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send HLS timed metadata"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendHLSTimedMetadata(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendHLSTimedMetadata:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/sendhlstimedmetadata(_:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSTimedMetadata":{"role":"symbol","title":"HMSHLSTimedMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSTimedMetadata"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSTimedMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSTimedMetadata"}],"url":"\/documentation\/hmssdk\/hmshlstimedmetadata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendHLSTimedMetadata:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendHLSTimedMetadata:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendHLSTimedMetadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<HMSHLSTimedMetadata *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool, NSError *)","preciseIdentifier":"c:BFv(#b#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendHLSTimedMetadata(_:completion:)\/title","value":"sendHLSTimedMetadata:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendHLSTimedMetadata(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendHLSTimedMetadata:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSTimedMetadata\/title","value":"HMSHLSTimedMetadata"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSTimedMetadata\/fragments","value":[{"kind":"identifier","text":"HMSHLSTimedMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}