{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameProcessingQueue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideoplugin\/setframeprocessingqueue(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideoplugin\/setframeprocessingqueue(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin\/setFrameProcessingQueue(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameProcessingQueue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"!)"}],"title":"setFrameProcessingQueue(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSVideoPlugin(im)setFrameProcessingQueue:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setFrameProcessingQueue:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoPlugin":{"role":"symbol","title":"HMSVideoPlugin","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoPlugin"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoPlugin"}],"url":"\/documentation\/hmssdk\/hmsvideoplugin"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoPlugin/setFrameProcessingQueue(_:)":{"role":"symbol","title":"setFrameProcessingQueue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameProcessingQueue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoPlugin\/setFrameProcessingQueue(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFrameProcessingQueue:"}],"url":"\/documentation\/hmssdk\/hmsvideoplugin\/setframeprocessingqueue(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setFrameProcessingQueue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrameProcessingQueue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setFrameProcessingQueue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"queue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/title","value":"HMSVideoPlugin"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin\/fragments","value":[{"kind":"identifier","text":"HMSVideoPlugin"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin~1setFrameProcessingQueue(_:)\/title","value":"setFrameProcessingQueue:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoPlugin~1setFrameProcessingQueue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrameProcessingQueue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}