{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localAudioTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack","preciseIdentifier":"c:objc(cs)HMSLocalAudioTrack","text":"HMSLocalAudioTrack"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalpeer\/localaudiotrack()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalpeer\/localaudiotrack()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer\/localAudioTrack()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localAudioTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSLocalAudioTrack","preciseIdentifier":"c:objc(cs)HMSLocalAudioTrack"},{"kind":"text","text":"?"}],"title":"localAudioTrack()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSLocalPeer(im)localAudioTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"localAudioTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalPeer/localAudioTrack()":{"role":"symbol","title":"localAudioTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localAudioTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSLocalAudioTrack","preciseIdentifier":"c:objc(cs)HMSLocalAudioTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer\/localAudioTrack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localAudioTrack"}],"url":"\/documentation\/hmssdk\/hmslocalpeer\/localaudiotrack()"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalPeer":{"role":"symbol","title":"HMSLocalPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalPeer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalPeer"}],"url":"\/documentation\/hmssdk\/hmslocalpeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalAudioTrack":{"role":"symbol","title":"HMSLocalAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalAudioTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalAudioTrack"}],"url":"\/documentation\/hmssdk\/hmslocalaudiotrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"localAudioTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"localAudioTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalAudioTrack","preciseIdentifier":"c:objc(cs)HMSLocalAudioTrack","text":"HMSLocalAudioTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"localAudioTrack"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer~1localAudioTrack()\/title","value":"localAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer~1localAudioTrack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"localAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer\/title","value":"HMSLocalPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalPeer\/fragments","value":[{"kind":"identifier","text":"HMSLocalPeer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioTrack\/title","value":"HMSLocalAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalAudioTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalAudioTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}