- Please refer to the platform specific documentation for details on how to obtain the stream URL and stream key. Here are some examples: 
    -   [YouTube](https://support.google.com/youtube/answer/2907883?hl=en&ref_topic=9257892)
    -   [Facebook](https://www.facebook.com/help/587160588142067)
    -   [Instagram](https://about.instagram.com/blog/tips-and-tricks/instagram-live-producer)
    -   [Twitch](https://help.twitch.tv/s/article/twitch-stream-key-faq?language=en_US)
    -   [LinkedIn](https://www.linkedin.com/help/linkedin/answer/a564446/go-live-using-a-custom-stream-rtmp)