{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"audioEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioEngine","preciseIdentifier":"c:objc(cs)AVAudioEngine"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mixerDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioMixerSource","text":"HMSAudioMixerSource"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsmanualaudiorenderer\/init(audioengine:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsmanualaudiorenderer\/init(audioengine:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSManualAudioRenderer\/init(audioEngine:delegate:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithAudioEngine:delegate:"}],"role":"symbol","title":"init(audioEngine:delegate:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"audioEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioEngine","preciseIdentifier":"c:objc(cs)AVAudioEngine"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMixerSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioMixerSource"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:objc(cs)HMSManualAudioRenderer(im)initWithAudioEngine:delegate:","modules":[{"name":"HMSSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSManualAudioRenderer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSManualAudioRenderer/init(audioEngine:delegate:)":{"role":"symbol","title":"init(audioEngine:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"audioEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioEngine","preciseIdentifier":"c:objc(cs)AVAudioEngine"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioMixerSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioMixerSource"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSManualAudioRenderer\/init(audioEngine:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAudioEngine:delegate:"}],"url":"\/documentation\/hmssdk\/hmsmanualaudiorenderer\/init(audioengine:delegate:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioMixerSource":{"role":"symbol","title":"HMSAudioMixerSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioMixerSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioMixerSource"}],"url":"\/documentation\/hmssdk\/hmsaudiomixersource"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSManualAudioRenderer":{"role":"symbol","title":"HMSManualAudioRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSManualAudioRenderer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSManualAudioRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSManualAudioRenderer"}],"url":"\/documentation\/hmssdk\/hmsmanualaudiorenderer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAudioEngine:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAudioEngine:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAudioEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioEngine","preciseIdentifier":"c:objc(cs)AVAudioEngine"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"audioEngine"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioMixerSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioMixerSource","text":"HMSAudioMixerSource"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mixerDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSManualAudioRenderer~1init(audioEngine:delegate:)\/title","value":"initWithAudioEngine:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSManualAudioRenderer~1init(audioEngine:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAudioEngine:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioMixerSource\/title","value":"HMSAudioMixerSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioMixerSource\/fragments","value":[{"kind":"identifier","text":"HMSAudioMixerSource"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSManualAudioRenderer\/title","value":"HMSManualAudioRenderer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSManualAudioRenderer\/fragments","value":[{"kind":"identifier","text":"HMSManualAudioRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}