{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcast"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsmessagerecipienttype\/broadcast"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsmessagerecipienttype\/broadcast"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType\/broadcast","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcast"}],"title":"HMSMessageRecipientType.broadcast","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSMessageRecipientType@HMSMessageRecipientTypeBroadcast","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipientTypeBroadcast"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessageRecipientType/broadcast":{"role":"symbol","title":"HMSMessageRecipientType.broadcast","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcast"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType\/broadcast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipientTypeBroadcast"}],"url":"\/documentation\/hmssdk\/hmsmessagerecipienttype\/broadcast"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessageRecipientType":{"role":"symbol","title":"HMSMessageRecipientType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessageRecipientType"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessageRecipientType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessageRecipientType"}],"url":"\/documentation\/hmssdk\/hmsmessagerecipienttype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSMessageRecipientTypeBroadcast"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipientTypeBroadcast"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSMessageRecipientTypeBroadcast"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType~1broadcast\/title","value":"HMSMessageRecipientTypeBroadcast"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType~1broadcast\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipientTypeBroadcast"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType\/title","value":"HMSMessageRecipientType"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessageRecipientType\/fragments","value":[{"kind":"identifier","text":"HMSMessageRecipientType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}