{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescriptionChanged"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmstrackupdate\/trackdescriptionchanged"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmstrackupdate\/trackdescriptionchanged"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDescriptionChanged","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescriptionChanged"}],"title":"HMSTrackUpdate.trackDescriptionChanged","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSTrackUpdate@HMSTrackUpdateTrackDescriptionChanged","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate/trackDescriptionChanged":{"role":"symbol","title":"HMSTrackUpdate.trackDescriptionChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescriptionChanged"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate\/trackDescriptionChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}],"url":"\/documentation\/hmssdk\/hmstrackupdate\/trackdescriptionchanged"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackUpdate":{"role":"symbol","title":"HMSTrackUpdate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackUpdate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackUpdate"}],"url":"\/documentation\/hmssdk\/hmstrackupdate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSTrackUpdateTrackDescriptionChanged"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackDescriptionChanged\/title","value":"HMSTrackUpdateTrackDescriptionChanged"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate~1trackDescriptionChanged\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdateTrackDescriptionChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate\/title","value":"HMSTrackUpdate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackUpdate\/fragments","value":[{"kind":"identifier","text":"HMSTrackUpdate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}