{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSUpdateListener","text":"HMSUpdateListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the update listener object which will receive all callbacks"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/add(delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/add(delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/add(delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds another listener of SDK updates"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSUpdateListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSUpdateListener"},{"kind":"text","text":")"}],"title":"add(delegate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(im)addWithDelegate:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addWithDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/add(delegate:)":{"role":"symbol","title":"add(delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSUpdateListener","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSUpdateListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds another listener of SDK updates"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/add(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addWithDelegate:"}],"url":"\/documentation\/hmssdk\/hmssdk\/add(delegate:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSUpdateListener":{"role":"symbol","title":"HMSUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSUpdateListener"}],"abstract":[{"type":"text","text":"100ms SDK provides callbacks to the client app about any change or update happening in the room after a user has joined by implementing HMSUpdateListener."},{"type":"text","text":" "},{"type":"text","text":"These updates can be used to render the video on screen or to display other info regarding the room."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSUpdateListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSUpdateListener"}],"url":"\/documentation\/hmssdk\/hmsupdatelistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addWithDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<HMSUpdateListener>","preciseIdentifier":"c:Qo@M@HMSSDK@objc(pl)HMSUpdateListener"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1add(delegate:)\/title","value":"addWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1add(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/title","value":"HMSUpdateListener"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSUpdateListener\/fragments","value":[{"kind":"identifier","text":"HMSUpdateListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}