{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeTrackState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"trackKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind","text":"HMSTrackKind"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"roles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole","text":"HMSRole"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mute","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the track needs to be muted, false otherwise."}]}]},{"name":"trackKind","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass an array of HMSTrackKind for change to apply to specific kind of tracks. Passing nil means all track kinds will be changed."}]}]},{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass a HMSTrackSource for change to apply to specific track source. Passing nil means all track sources will be changed."}]}]},{"name":"roles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Pass an array of HMSRole for change to apply to specific roles. Passing nil means all roles will be changed."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler to be invoked when the request succeeds or fails with an error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/changetrackstate(mute:for:source:roles:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(mute:for:source:roles:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"To change the mute status of multiple tracks of specific kinds for every peer or for peers with certain roles."},{"type":"text","text":" "},{"type":"text","text":"Call changeTrackState(mute: true) to mute everybody’s audio and video."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeTrackState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"roles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"changeTrackState(mute:for:source:roles:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:6HMSSDKAAC16changeTrackState4mute3for6source5roles10completionySb_So12HMSTrackKindVSgSSSgSayAA7HMSRoleCGSgySb_s5Error_pSgtcSgtF","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackKind":{"role":"symbol","title":"HMSTrackKind","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackKind"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackKind","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackKind"}],"url":"\/documentation\/hmssdk\/hmstrackkind"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/changeTrackState(mute:for:source:roles:completion:)":{"role":"symbol","title":"changeTrackState(mute:for:source:roles:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeTrackState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackKind","preciseIdentifier":"c:@E@HMSTrackKind"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"roles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"To change the mute status of multiple tracks of specific kinds for every peer or for peers with certain roles."},{"type":"text","text":" "},{"type":"text","text":"Call changeTrackState(mute: true) to mute everybody’s audio and video."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/changeTrackState(mute:for:source:roles:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmssdk\/changetrackstate(mute:for:source:roles:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRole":{"role":"symbol","title":"HMSRole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRole"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRole"}],"url":"\/documentation\/hmssdk\/hmsrole"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRole\/title","value":"HMSRole"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRole\/fragments","value":[{"kind":"identifier","text":"HMSRole"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}