{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsStatsMonitor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVPlayer","preciseIdentifier":"c:objc(cs)AVPlayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSStatsMonitor","text":"HMSHLSStatsMonitor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/hlsstatsmonitor(player:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/hlsstatsmonitor(player:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/hlsStatsMonitor(player:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get an instance of HMSHLSStatsMonitor to check hls playback stats and errors during playback"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsStatsMonitor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVPlayer","preciseIdentifier":"c:objc(cs)AVPlayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSHLSStatsMonitor","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSStatsMonitor"}],"title":"hlsStatsMonitor(player:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(im)hlsStatsMonitorWithPlayer:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"hlsStatsMonitorWithPlayer:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/hlsStatsMonitor(player:)":{"role":"symbol","title":"hlsStatsMonitor(player:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hlsStatsMonitor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVPlayer","preciseIdentifier":"c:objc(cs)AVPlayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSHLSStatsMonitor","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSStatsMonitor"}],"abstract":[{"type":"text","text":"Get an instance of HMSHLSStatsMonitor to check hls playback stats and errors during playback"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/hlsStatsMonitor(player:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hlsStatsMonitorWithPlayer:"}],"url":"\/documentation\/hmssdk\/hmssdk\/hlsstatsmonitor(player:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor":{"role":"symbol","title":"HMSHLSStatsMonitor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"url":"\/documentation\/hmssdk\/hmshlsstatsmonitor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"hlsStatsMonitorWithPlayer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hlsStatsMonitorWithPlayer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSHLSStatsMonitor","text":"HMSHLSStatsMonitor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"hlsStatsMonitorWithPlayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVPlayer","preciseIdentifier":"c:objc(cs)AVPlayer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"player"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1hlsStatsMonitor(player:)\/title","value":"hlsStatsMonitorWithPlayer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1hlsStatsMonitor(player:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hlsStatsMonitorWithPlayer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor\/title","value":"HMSHLSStatsMonitor"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor\/fragments","value":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}