{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/room"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/room"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/room","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the room which was joined."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":"?"}],"title":"room","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(py)room","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"room"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRoom":{"role":"symbol","title":"HMSRoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRoom"}],"abstract":[{"type":"text","text":"A room represents a real-time audio, video session, the basic building block of the 100ms SDK"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRoom"}],"url":"\/documentation\/hmssdk\/hmsroom"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/room":{"role":"symbol","title":"room","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the room which was joined."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/room","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"room"}],"url":"\/documentation\/hmssdk\/hmssdk\/room"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"room"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"room"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRoom","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRoom","text":"HMSRoom"},{"kind":"text","text":" * "},{"kind":"identifier","text":"room"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/title","value":"HMSRoom"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRoom\/fragments","value":[{"kind":"identifier","text":"HMSRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1room\/title","value":"room"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1room\/fragments","value":[{"kind":"identifier","text":"room"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}