{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNode"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenBroadcastAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSScreenBroadcastAudioNode","text":"HMSScreenBroadcastAudioNode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/screenbroadcastaudioreceivernode()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/screenbroadcastaudioreceivernode()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/screenBroadcastAudioReceiverNode()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get audio node which receives audio from screen broadcast extension"},{"type":"text","text":" "},{"type":"text","text":"App group needs to be set on hmssdk instance for it to work"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNode"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"HMSScreenBroadcastAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSScreenBroadcastAudioNode"}],"title":"screenBroadcastAudioReceiverNode()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(im)screenBroadcastAudioReceiverNodeAndReturnError:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenBroadcastAudioNode":{"role":"symbol","title":"HMSScreenBroadcastAudioNode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenBroadcastAudioNode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenBroadcastAudioNode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSScreenBroadcastAudioNode"}],"url":"\/documentation\/hmssdk\/hmsscreenbroadcastaudionode"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/screenBroadcastAudioReceiverNode()":{"role":"symbol","title":"screenBroadcastAudioReceiverNode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNode"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"HMSScreenBroadcastAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSScreenBroadcastAudioNode"}],"abstract":[{"type":"text","text":"Get audio node which receives audio from screen broadcast extension"},{"type":"text","text":" "},{"type":"text","text":"App group needs to be set on hmssdk instance for it to work"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/screenBroadcastAudioReceiverNode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"}],"url":"\/documentation\/hmssdk\/hmssdk\/screenbroadcastaudioreceivernode()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"screenBroadcastAudioReceiverNodeAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenBroadcastAudioNode","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSScreenBroadcastAudioNode","text":"HMSScreenBroadcastAudioNode"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenBroadcastAudioNode\/title","value":"HMSScreenBroadcastAudioNode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenBroadcastAudioNode\/fragments","value":[{"kind":"identifier","text":"HMSScreenBroadcastAudioNode"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1screenBroadcastAudioReceiverNode()\/title","value":"screenBroadcastAudioReceiverNodeAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1screenBroadcastAudioReceiverNode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"screenBroadcastAudioReceiverNodeAndReturnError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}