{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendDirectMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"chat\", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority","text":"HMSCommandPriority"},{"kind":"text","text":" = .medium, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage","text":"HMSMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of message."}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Content of the message."}]}]},{"name":"peer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The peer to whom this message is directed."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler to be invoked when message was sent, or when error happened during sending"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/senddirectmessage(type:message:peer:priority:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/senddirectmessage(type:message:peer:priority:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendDirectMessage(type:message:peer:priority:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sends a direct message to the specified peer only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendDirectMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"sendDirectMessage(type:message:peer:priority:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(im)sendDirectMessageWithType:message:peer:priority:completion:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sendDirectMessageWithType:message:peer:priority:completion:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPeer":{"role":"symbol","title":"HMSPeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPeer"}],"abstract":[{"type":"text","text":"A peer represents all participants connected to a room. Peers can be “local” or “remote”"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPeer"}],"url":"\/documentation\/hmssdk\/hmspeer"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSMessage":{"role":"symbol","title":"HMSMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSMessage"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSMessage"}],"url":"\/documentation\/hmssdk\/hmsmessage"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCommandPriority":{"role":"symbol","title":"HMSCommandPriority","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCommandPriority"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCommandPriority"}],"url":"\/documentation\/hmssdk\/hmscommandpriority"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/sendDirectMessage(type:message:peer:priority:completion:)":{"role":"symbol","title":"sendDirectMessage(type:message:peer:priority:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendDirectMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"peer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"HMSMessage","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sends a direct message to the specified peer only."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/sendDirectMessage(type:message:peer:priority:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendDirectMessageWithType:message:peer:priority:completion:"}],"url":"\/documentation\/hmssdk\/hmssdk\/senddirectmessage(type:message:peer:priority:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendDirectMessageWithType:message:peer:priority:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendDirectMessageWithType:message:peer:priority:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendDirectMessageWithType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"peer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPeer","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPeer","text":"HMSPeer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peer"},{"kind":"text","text":" "},{"kind":"identifier","text":"priority:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCommandPriority","preciseIdentifier":"c:@M@HMSSDK@E@HMSCommandPriority","text":"HMSCommandPriority"},{"kind":"text","text":") "},{"kind":"internalParam","text":"priority"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(HMSMessage *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@HMSSDK@objc(cs)HMSMessage#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/title","value":"HMSPeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPeer\/fragments","value":[{"kind":"identifier","text":"HMSPeer"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage\/title","value":"HMSMessage"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSMessage\/fragments","value":[{"kind":"identifier","text":"HMSMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCommandPriority\/title","value":"HMSCommandPriority"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCommandPriority\/fragments","value":[{"kind":"identifier","text":"HMSCommandPriority"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendDirectMessage(type:message:peer:priority:completion:)\/title","value":"sendDirectMessageWithType:message:peer:priority:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1sendDirectMessage(type:message:peer:priority:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendDirectMessageWithType:message:peer:priority:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}