{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings","preciseIdentifier":"c:objc(cs)HMSTrackSettings","text":"HMSTrackSettings"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssdk\/tracksettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssdk\/tracksettings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/trackSettings","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use to override track settings coming from role policy"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackSettings","preciseIdentifier":"c:objc(cs)HMSTrackSettings"}],"title":"trackSettings","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSSDK(py)trackSettings","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"trackSettings"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackSettings":{"role":"symbol","title":"HMSTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackSettings"}],"url":"\/documentation\/hmssdk\/hmstracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK/trackSettings":{"role":"symbol","title":"trackSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackSettings","preciseIdentifier":"c:objc(cs)HMSTrackSettings"}],"abstract":[{"type":"text","text":"Use to override track settings coming from role policy"}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK\/trackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackSettings"}],"url":"\/documentation\/hmssdk\/hmssdk\/tracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSDK":{"role":"symbol","title":"HMSSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSDK"}],"abstract":[{"type":"text","text":"The public interface of 100ms SDK. Create an instance of HMSSDK to start using the SDK."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSDK"}],"url":"\/documentation\/hmssdk\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"trackSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"trackSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackSettings","preciseIdentifier":"c:objc(cs)HMSTrackSettings","text":"HMSTrackSettings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"trackSettings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings\/title","value":"HMSTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1trackSettings\/title","value":"trackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK~1trackSettings\/fragments","value":[{"kind":"identifier","text":"trackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/title","value":"HMSSDK"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSDK\/fragments","value":[{"kind":"identifier","text":"HMSSDK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}