{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRolesThatCanViewResponses"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rolesThatCanViewResponses"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole","text":"HMSRole"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"rolesThatCanViewResponses","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The roles that can view responses in the poll."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated poll builder instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/withrolesthatcanviewresponses(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/withrolesthatcanviewresponses(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanViewResponses(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the roles that can view responses in the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRolesThatCanViewResponses"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"title":"withRolesThatCanViewResponses(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSPollBuilder(im)withRolesThatCanViewResponses:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"withRolesThatCanViewResponses:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSRole":{"role":"symbol","title":"HMSRole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRole"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRole"}],"url":"\/documentation\/hmssdk\/hmsrole"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withRolesThatCanViewResponses(_:)":{"role":"symbol","title":"withRolesThatCanViewResponses(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRolesThatCanViewResponses"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"HMSRole","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSRole"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the roles that can view responses in the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withRolesThatCanViewResponses(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withRolesThatCanViewResponses:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withrolesthatcanviewresponses(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder":{"role":"symbol","title":"HMSPollBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollBuilder"}],"url":"\/documentation\/hmssdk\/hmspollbuilder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"withRolesThatCanViewResponses:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withRolesThatCanViewResponses:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"withRolesThatCanViewResponses:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<HMSRole *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rolesThatCanViewResponses"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRole\/title","value":"HMSRole"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRole\/fragments","value":[{"kind":"identifier","text":"HMSRole"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withRolesThatCanViewResponses(_:)\/title","value":"withRolesThatCanViewResponses:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withRolesThatCanViewResponses(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withRolesThatCanViewResponses:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/title","value":"HMSPollBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}