{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeDegradation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeDegradationPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSubscribeDegradationPolicy","text":"HMSSubscribeDegradationPolicy"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmssubscribesettings\/subscribedegradation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmssubscribesettings\/subscribedegradation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeSettings\/subscribeDegradation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeDegradation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSubscribeDegradationPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSubscribeDegradationPolicy"},{"kind":"text","text":"?"}],"title":"subscribeDegradation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSSubscribeSettings(py)subscribeDegradation","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"subscribeDegradation"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSubscribeSettings":{"role":"symbol","title":"HMSSubscribeSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSubscribeSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSubscribeSettings"}],"url":"\/documentation\/hmssdk\/hmssubscribesettings"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSubscribeDegradationPolicy":{"role":"symbol","title":"HMSSubscribeDegradationPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSSubscribeDegradationPolicy"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeDegradationPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSSubscribeDegradationPolicy"}],"url":"\/documentation\/hmssdk\/hmssubscribedegradationpolicy"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSSubscribeSettings/subscribeDegradation":{"role":"symbol","title":"subscribeDegradation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribeDegradation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSSubscribeDegradationPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSubscribeDegradationPolicy"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeSettings\/subscribeDegradation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscribeDegradation"}],"url":"\/documentation\/hmssdk\/hmssubscribesettings\/subscribedegradation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subscribeDegradation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subscribeDegradation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSSubscribeDegradationPolicy","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSSubscribeDegradationPolicy","text":"HMSSubscribeDegradationPolicy"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subscribeDegradation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSubscribeSettings\/title","value":"HMSSubscribeSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSubscribeSettings\/fragments","value":[{"kind":"identifier","text":"HMSSubscribeSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSubscribeDegradationPolicy\/title","value":"HMSSubscribeDegradationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSubscribeDegradationPolicy\/fragments","value":[{"kind":"identifier","text":"HMSSubscribeDegradationPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSubscribeSettings~1subscribeDegradation\/title","value":"subscribeDegradation"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSSubscribeSettings~1subscribeDegradation\/fragments","value":[{"kind":"identifier","text":"subscribeDegradation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}