{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponseBuilder","text":"HMSPollResponseBuilder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ((["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponseResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponseResult","text":"HMSPollQuestionResponseResult"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The poll response builder."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The closure to be called upon completion, providing the response result or an error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter\/add(response:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsinteractivitycenter\/add(response:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/add(response:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a poll response."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResponseBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponseBuilder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSPollQuestionResponseResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponseResult"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"add(response:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSInteractivityCenter(im)addWithResponse:completion:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addWithResponse:completion:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResponseResult":{"role":"symbol","title":"HMSPollQuestionResponseResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResponseResult"}],"abstract":[{"type":"text","text":"Represents the result of a poll question response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResponseResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionResponseResult"}],"url":"\/documentation\/hmssdk\/hmspollquestionresponseresult"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter":{"role":"symbol","title":"HMSInteractivityCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSInteractivityCenter"}],"abstract":[{"type":"text","text":"Provides interactivity features."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSInteractivityCenter"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSInteractivityCenter/add(response:completion:)":{"role":"symbol","title":"add(response:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollResponseBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponseBuilder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"HMSPollQuestionResponseResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResponseResult"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Adds a poll response."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSInteractivityCenter\/add(response:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addWithResponse:completion:"}],"url":"\/documentation\/hmssdk\/hmsinteractivitycenter\/add(response:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollResponseBuilder":{"role":"symbol","title":"HMSPollResponseBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollResponseBuilder"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollResponseBuilder"}],"url":"\/documentation\/hmssdk\/hmspollresponsebuilder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addWithResponse:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithResponse:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addWithResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResponseBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollResponseBuilder","text":"HMSPollResponseBuilder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<HMSPollQuestionResponseResult *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponseResult\/title","value":"HMSPollQuestionResponseResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResponseResult\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionResponseResult"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/title","value":"HMSInteractivityCenter"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter\/fragments","value":[{"kind":"identifier","text":"HMSInteractivityCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1add(response:completion:)\/title","value":"addWithResponse:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSInteractivityCenter~1add(response:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithResponse:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResponseBuilder\/title","value":"HMSPollResponseBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResponseBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollResponseBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}