{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","preciseIdentifier":"c:@E@HMSQualityLimitationReason","text":"HMSQualityLimitationReason"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreasons\/reason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreasons\/reason"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/reason","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSQualityLimitationReason","preciseIdentifier":"c:@E@HMSQualityLimitationReason"}],"title":"reason","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSQualityLimitationReasons(py)reason","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"reason"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason":{"role":"symbol","title":"HMSQualityLimitationReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReason"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons":{"role":"symbol","title":"HMSQualityLimitationReasons","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReasons"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReasons/reason":{"role":"symbol","title":"reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSQualityLimitationReason","preciseIdentifier":"c:@E@HMSQualityLimitationReason"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReasons\/reason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reason"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreasons\/reason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reason"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","preciseIdentifier":"c:@E@HMSQualityLimitationReason","text":"HMSQualityLimitationReason"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/title","value":"HMSQualityLimitationReason"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons\/title","value":"HMSQualityLimitationReasons"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReasons"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1reason\/title","value":"reason"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReasons~1reason\/fragments","value":[{"kind":"identifier","text":"reason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}