{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState","text":"HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource","text":"HMSAudioSource"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:initialmutestate:audiosource:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:initialmutestate:audiosource:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioSource:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?)"}],"title":"init(maxBitrate:trackDescription:initialMuteState:audioSource:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)HMSAudioTrackSettings(im)initWithMaxBitrate:trackDescription:initialMuteState:audioSource:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSTrackMuteState":{"role":"symbol","title":"HMSTrackMuteState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSTrackMuteState"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackMuteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSTrackMuteState"}],"url":"\/documentation\/hmssdk\/hmstrackmutestate"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings/init(maxBitrate:trackDescription:initialMuteState:audioSource:)":{"role":"symbol","title":"init(maxBitrate:trackDescription:initialMuteState:audioSource:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initialMuteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings\/init(maxBitrate:trackDescription:initialMuteState:audioSource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings\/init(maxbitrate:trackdescription:initialmutestate:audiosource:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioSource":{"role":"symbol","title":"HMSAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioSource"}],"url":"\/documentation\/hmssdk\/hmsaudiosource"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioTrackSettings":{"role":"symbol","title":"HMSAudioTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsaudiotracksettings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMaxBitrate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxBitrate"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDescription:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackDescription"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialMuteState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSTrackMuteState","preciseIdentifier":"c:@E@HMSTrackMuteState","text":"HMSTrackMuteState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"initialMuteState"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioSource","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSAudioSource","text":"HMSAudioSource"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"audioSource"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:initialMuteState:audioSource:)\/title","value":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings~1init(maxBitrate:trackDescription:initialMuteState:audioSource:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxBitrate:trackDescription:initialMuteState:audioSource:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioSource\/title","value":"HMSAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioSource\/fragments","value":[{"kind":"identifier","text":"HMSAudioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/title","value":"HMSAudioTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSAudioTrackSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}