{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"poll"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollcategory\/poll"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollcategory\/poll"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory\/poll","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The poll is a standard poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"poll"}],"title":"HMSPollCategory.poll","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPollCategory@HMSPollCategoryPoll","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollCategoryPoll"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollCategory":{"role":"symbol","title":"HMSPollCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollCategory"}],"abstract":[{"type":"text","text":"Represents the category of a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollCategory"}],"url":"\/documentation\/hmssdk\/hmspollcategory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollCategory/poll":{"role":"symbol","title":"HMSPollCategory.poll","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"poll"}],"abstract":[{"type":"text","text":"The poll is a standard poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory\/poll","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollCategoryPoll"}],"url":"\/documentation\/hmssdk\/hmspollcategory\/poll"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollCategoryPoll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollCategoryPoll"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPollCategoryPoll"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/title","value":"HMSPollCategory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/fragments","value":[{"kind":"identifier","text":"HMSPollCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory~1poll\/title","value":"HMSPollCategoryPoll"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory~1poll\/fragments","value":[{"kind":"identifier","text":"HMSPollCategoryPoll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}