{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusModeTapToLockFocus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmscamerafocusmode\/focusmodetaptolockfocus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmscamerafocusmode\/focusmodetaptolockfocus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode\/focusModeTapToLockFocus","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusModeTapToLockFocus"}],"title":"HMSCameraFocusMode.focusModeTapToLockFocus","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSCameraFocusMode@kHMSFocusModeTapToLockFocus","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSFocusModeTapToLockFocus"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFocusMode/focusModeTapToLockFocus":{"role":"symbol","title":"HMSCameraFocusMode.focusModeTapToLockFocus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusModeTapToLockFocus"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode\/focusModeTapToLockFocus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSFocusModeTapToLockFocus"}],"url":"\/documentation\/hmssdk\/hmscamerafocusmode\/focusmodetaptolockfocus"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFocusMode":{"role":"symbol","title":"HMSCameraFocusMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCameraFocusMode"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFocusMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCameraFocusMode"}],"url":"\/documentation\/hmssdk\/hmscamerafocusmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSFocusModeTapToLockFocus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSFocusModeTapToLockFocus"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSFocusModeTapToLockFocus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFocusMode~1focusModeTapToLockFocus\/title","value":"kHMSFocusModeTapToLockFocus"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFocusMode~1focusModeTapToLockFocus\/fragments","value":[{"kind":"identifier","text":"kHMSFocusModeTapToLockFocus"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFocusMode\/title","value":"HMSCameraFocusMode"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSCameraFocusMode\/fragments","value":[{"kind":"identifier","text":"HMSCameraFocusMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}