{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFlash"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flashEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack\/captureimageatmaxsupportedresolution(withflash:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmslocalvideotrack\/captureimageatmaxsupportedresolution(withflash:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/captureImageAtMaxSupportedResolution(withFlash:completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFlash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"captureImageAtMaxSupportedResolution(withFlash:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)HMSLocalVideoTrack(im)captureImageAtMaxSupportedResolutionWithFlash:completion:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack/captureImageAtMaxSupportedResolution(withFlash:completion:)":{"role":"symbol","title":"captureImageAtMaxSupportedResolution(withFlash:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFlash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack\/captureImageAtMaxSupportedResolution(withFlash:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack\/captureimageatmaxsupportedresolution(withflash:completion:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSLocalVideoTrack":{"role":"symbol","title":"HMSLocalVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSLocalVideoTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSLocalVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSLocalVideoTrack"}],"url":"\/documentation\/hmssdk\/hmslocalvideotrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"captureImageAtMaxSupportedResolutionWithFlash:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flashEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UIImage *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1captureImageAtMaxSupportedResolution(withFlash:completion:)\/title","value":"captureImageAtMaxSupportedResolutionWithFlash:completion:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack~1captureImageAtMaxSupportedResolution(withFlash:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureImageAtMaxSupportedResolutionWithFlash:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/title","value":"HMSLocalVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSLocalVideoTrack\/fragments","value":[{"kind":"identifier","text":"HMSLocalVideoTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}