{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteAudioTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)HMSRemoteAudioTrack","text":"HMSRemoteAudioTrack"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsremotepeer\/remoteaudiotrack()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsremotepeer\/remoteaudiotrack()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer\/remoteAudioTrack()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteAudioTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)HMSRemoteAudioTrack"},{"kind":"text","text":"?"}],"title":"remoteAudioTrack()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSRemotePeer(im)remoteAudioTrack","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"remoteAudioTrack"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemotePeer/remoteAudioTrack()":{"role":"symbol","title":"remoteAudioTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteAudioTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"HMSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)HMSRemoteAudioTrack"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer\/remoteAudioTrack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteAudioTrack"}],"url":"\/documentation\/hmssdk\/hmsremotepeer\/remoteaudiotrack()"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemoteAudioTrack":{"role":"symbol","title":"HMSRemoteAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemoteAudioTrack"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}],"url":"\/documentation\/hmssdk\/hmsremoteaudiotrack"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSRemotePeer":{"role":"symbol","title":"HMSRemotePeer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSRemotePeer"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemotePeer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSRemotePeer"}],"url":"\/documentation\/hmssdk\/hmsremotepeer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"remoteAudioTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"remoteAudioTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)HMSRemoteAudioTrack","text":"HMSRemoteAudioTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"remoteAudioTrack"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemotePeer~1remoteAudioTrack()\/title","value":"remoteAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemotePeer~1remoteAudioTrack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"remoteAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack\/title","value":"HMSRemoteAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemoteAudioTrack\/fragments","value":[{"kind":"identifier","text":"HMSRemoteAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemotePeer\/title","value":"HMSRemotePeer"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSRemotePeer\/fragments","value":[{"kind":"identifier","text":"HMSRemotePeer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}