{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSHLSPlaybackDelegate","text":"HMSHLSPlaybackDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsstatsmonitor\/delegate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSPlaybackDelegate","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSHLSPlaybackDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6HMSSDK18HMSHLSStatsMonitorC8delegateAA22HMSHLSPlaybackDelegate_pSgvp","modules":[{"name":"HMSSDK"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSPlaybackDelegate":{"role":"symbol","title":"HMSHLSPlaybackDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSPlaybackDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}],"url":"\/documentation\/hmssdk\/hmshlsplaybackdelegate"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor":{"role":"symbol","title":"HMSHLSStatsMonitor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}],"url":"\/documentation\/hmssdk\/hmshlsstatsmonitor"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSStatsMonitor/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSHLSPlaybackDelegate","preciseIdentifier":"c:@M@HMSSDK@objc(pl)HMSHLSPlaybackDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSStatsMonitor\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk\/hmshlsstatsmonitor\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate\/title","value":"HMSHLSPlaybackDelegate"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSPlaybackDelegate\/fragments","value":[{"kind":"identifier","text":"HMSHLSPlaybackDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor\/title","value":"HMSHLSStatsMonitor"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSStatsMonitor\/fragments","value":[{"kind":"identifier","text":"HMSHLSStatsMonitor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}