{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScoreMap","preciseIdentifier":"c:objc(cs)HMSScoreMap","text":"HMSScoreMap"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsnetworkhealthconfig\/scoremap"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsnetworkhealthconfig\/scoremap"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/scoreMap","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"HMSScoreMap","preciseIdentifier":"c:objc(cs)HMSScoreMap"},{"kind":"text","text":"]"}],"title":"scoreMap","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSNetworkHealthConfig(py)scoreMap","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"scoreMap"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSScoreMap":{"role":"symbol","title":"HMSScoreMap","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScoreMap"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScoreMap","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSScoreMap"}],"url":"\/documentation\/hmssdk\/hmsscoremap"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig/scoreMap":{"role":"symbol","title":"scoreMap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scoreMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"HMSScoreMap","preciseIdentifier":"c:objc(cs)HMSScoreMap"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig\/scoreMap","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scoreMap"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig\/scoremap"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSNetworkHealthConfig":{"role":"symbol","title":"HMSNetworkHealthConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSNetworkHealthConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}],"url":"\/documentation\/hmssdk\/hmsnetworkhealthconfig"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scoreMap"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scoreMap"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,HMSScoreMap *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"scoreMap"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScoreMap\/title","value":"HMSScoreMap"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScoreMap\/fragments","value":[{"kind":"identifier","text":"HMSScoreMap"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1scoreMap\/title","value":"scoreMap"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig~1scoreMap\/fragments","value":[{"kind":"identifier","text":"scoreMap"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig\/title","value":"HMSNetworkHealthConfig"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSNetworkHealthConfig\/fragments","value":[{"kind":"identifier","text":"HMSNetworkHealthConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}