{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioBuffer","preciseIdentifier":"c:objc(cs)AVAudioBuffer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsaudiobuffersource\/enqueue(buffer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsaudiobuffersource\/enqueue(buffer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferSource\/enqueue(buffer:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioBuffer","preciseIdentifier":"c:objc(cs)AVAudioBuffer"},{"kind":"text","text":")"}],"title":"enqueue(buffer:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSAudioBufferSource(im)enqueueWithBuffer:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enqueueWithBuffer:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferSource"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioBufferSource/enqueue(buffer:)":{"role":"symbol","title":"enqueue(buffer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enqueue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioBuffer","preciseIdentifier":"c:objc(cs)AVAudioBuffer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferSource\/enqueue(buffer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enqueueWithBuffer:"}],"url":"\/documentation\/hmssdk\/hmsaudiobuffersource\/enqueue(buffer:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSAudioBufferSource":{"role":"symbol","title":"HMSAudioBufferSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSAudioBufferSource"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSAudioBufferSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSAudioBufferSource"}],"url":"\/documentation\/hmssdk\/hmsaudiobuffersource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enqueueWithBuffer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueWithBuffer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"enqueueWithBuffer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioBuffer","preciseIdentifier":"c:objc(cs)AVAudioBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferSource~1enqueue(buffer:)\/title","value":"enqueueWithBuffer:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferSource~1enqueue(buffer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enqueueWithBuffer:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferSource\/title","value":"HMSAudioBufferSource"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSAudioBufferSource\/fragments","value":[{"kind":"identifier","text":"HMSAudioBufferSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}