{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"meetingURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"\")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmshlsmeetingurlvariant\/init(meetingurl:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmshlsmeetingurlvariant\/init(meetingurl:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant\/init(meetingURL:metadata:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"meetingURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(meetingURL:metadata:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@HMSSDK@objc(cs)HMSHLSMeetingURLVariant(im)initWithMeetingURL:metadata:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMeetingURL:metadata:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSMeetingURLVariant/init(meetingURL:metadata:)":{"role":"symbol","title":"init(meetingURL:metadata:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"meetingURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant\/init(meetingURL:metadata:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMeetingURL:metadata:"}],"url":"\/documentation\/hmssdk\/hmshlsmeetingurlvariant\/init(meetingurl:metadata:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSHLSMeetingURLVariant":{"role":"symbol","title":"HMSHLSMeetingURLVariant","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSHLSMeetingURLVariant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}],"url":"\/documentation\/hmssdk\/hmshlsmeetingurlvariant"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMeetingURL:metadata:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMeetingURL:metadata:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMeetingURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"meetingURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant~1init(meetingURL:metadata:)\/title","value":"initWithMeetingURL:metadata:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant~1init(meetingURL:metadata:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMeetingURL:metadata:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant\/title","value":"HMSHLSMeetingURLVariant"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSHLSMeetingURLVariant\/fragments","value":[{"kind":"identifier","text":"HMSHLSMeetingURLVariant"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}