{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsvideotracksettings\/camerafacing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFacing","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"title":"cameraFacing","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)HMSVideoTrackSettings(py)cameraFacing","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings":{"role":"symbol","title":"HMSVideoTrackSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSVideoTrackSettings"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSVideoTrackSettings"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSVideoTrackSettings/cameraFacing":{"role":"symbol","title":"cameraFacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSVideoTrackSettings\/cameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"url":"\/documentation\/hmssdk\/hmsvideotracksettings\/camerafacing"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSCameraFacing":{"role":"symbol","title":"HMSCameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSCameraFacing"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSCameraFacing"}],"url":"\/documentation\/hmssdk\/hmscamerafacing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cameraFacing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cameraFacing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSCameraFacing","preciseIdentifier":"c:@E@HMSCameraFacing","text":"HMSCameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/title","value":"HMSVideoTrackSettings"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings\/fragments","value":[{"kind":"identifier","text":"HMSVideoTrackSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraFacing\/title","value":"cameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSVideoTrackSettings~1cameraFacing\/fragments","value":[{"kind":"identifier","text":"cameraFacing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}