{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"builder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","text":"HMSPollQuestionBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"builder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The builder instance for creating the question."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated poll builder instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/addquestion(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/addquestion(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addQuestion(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a question to the poll using a question builder."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"title":"addQuestion(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSPollBuilder(im)addQuestionWith:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addQuestionWith:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionBuilder":{"role":"symbol","title":"HMSPollQuestionBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll question."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}],"url":"\/documentation\/hmssdk\/hmspollquestionbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder":{"role":"symbol","title":"HMSPollBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollBuilder"}],"url":"\/documentation\/hmssdk\/hmspollbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/addQuestion(with:)":{"role":"symbol","title":"addQuestion(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addQuestion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Adds a question to the poll using a question builder."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/addQuestion(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addQuestionWith:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/addquestion(with:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addQuestionWith:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addQuestionWith:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"addQuestionWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionBuilder","text":"HMSPollQuestionBuilder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"builder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/title","value":"HMSPollQuestionBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/title","value":"HMSPollBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addQuestion(with:)\/title","value":"addQuestionWith:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1addQuestion(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addQuestionWith:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}