{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCategory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory","text":"HMSPollCategory"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"category","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The category of the poll."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated poll builder instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/withcategory(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/withcategory(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withCategory(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the category of the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"title":"withCategory(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSPollBuilder(im)withCategory:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"withCategory:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder":{"role":"symbol","title":"HMSPollBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollBuilder"}],"url":"\/documentation\/hmssdk\/hmspollbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withCategory(_:)":{"role":"symbol","title":"withCategory(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the category of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withCategory(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withCategory:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withcategory(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollCategory":{"role":"symbol","title":"HMSPollCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollCategory"}],"abstract":[{"type":"text","text":"Represents the category of a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollCategory"}],"url":"\/documentation\/hmssdk\/hmspollcategory"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"withCategory:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCategory:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"withCategory:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","preciseIdentifier":"c:@M@HMSSDK@E@HMSPollCategory","text":"HMSPollCategory"},{"kind":"text","text":") "},{"kind":"internalParam","text":"category"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/title","value":"HMSPollBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withCategory(_:)\/title","value":"withCategory:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withCategory(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withCategory:"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/title","value":"HMSPollCategory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/fragments","value":[{"kind":"identifier","text":"HMSPollCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}