{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The duration of the poll."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated poll builder instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/withduration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollbuilder\/withduration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withDuration(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the duration of the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDuration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"title":"withDuration(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@HMSSDK@objc(cs)HMSPollBuilder(im)withDuration:","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"withDuration:"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder":{"role":"symbol","title":"HMSPollBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollBuilder"}],"abstract":[{"type":"text","text":"Builder class for creating a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollBuilder"}],"url":"\/documentation\/hmssdk\/hmspollbuilder"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollBuilder/withDuration(_:)":{"role":"symbol","title":"withDuration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDuration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder"}],"abstract":[{"type":"text","text":"Sets the duration of the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder\/withDuration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"withDuration:"}],"url":"\/documentation\/hmssdk\/hmspollbuilder\/withduration(_:)"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"withDuration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withDuration:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollBuilder","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollBuilder","text":"HMSPollBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"withDuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/title","value":"HMSPollBuilder"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder\/fragments","value":[{"kind":"identifier","text":"HMSPollBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withDuration(_:)\/title","value":"withDuration:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollBuilder~1withDuration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withDuration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}