{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quiz"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollcategory\/quiz"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollcategory\/quiz"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory\/quiz","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The poll is a quiz."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quiz"}],"title":"HMSPollCategory.quiz","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@HMSSDK@E@HMSPollCategory@HMSPollCategoryQuiz","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"HMSPollCategoryQuiz"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollCategory":{"role":"symbol","title":"HMSPollCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollCategory"}],"abstract":[{"type":"text","text":"Represents the category of a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollCategory"}],"url":"\/documentation\/hmssdk\/hmspollcategory"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollCategory/quiz":{"role":"symbol","title":"HMSPollCategory.quiz","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quiz"}],"abstract":[{"type":"text","text":"The poll is a quiz."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollCategory\/quiz","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollCategoryQuiz"}],"url":"\/documentation\/hmssdk\/hmspollcategory\/quiz"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"HMSPollCategoryQuiz"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"HMSPollCategoryQuiz"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"HMSPollCategoryQuiz"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/title","value":"HMSPollCategory"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory\/fragments","value":[{"kind":"identifier","text":"HMSPollCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory~1quiz\/title","value":"HMSPollCategoryQuiz"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollCategory~1quiz\/fragments","value":[{"kind":"identifier","text":"HMSPollCategoryQuiz"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}