name: Link Check

on:
  pull_request:
    branches:
      - qa
      - main
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Preview URL
      uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      id: getPreviewUrl
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 300
        check_interval: 10

    - name: Print Preview URL
      run: echo ${{steps.getPreviewUrl.outputs.url}}

    - name: Update mlc_config
      run: |
        sed -i "s/<PREVIEW_URL>/${{steps.getPreviewUrl.outputs.url}}/" ./mlc_config.json

    - name: Run link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'mlc_config.json'
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'no'
        base-branch: 'main'
        file-extension: '.mdx'
