{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bandwidth"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreason\/bandwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreason\/bandwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/bandwidth","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bandwidth"}],"title":"HMSQualityLimitationReason.bandwidth","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSQualityLimitationReason@kHMSQualityLimitationReasonBandwidth","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/bandwidth":{"role":"symbol","title":"HMSQualityLimitationReason.bandwidth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bandwidth"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/bandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/bandwidth"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason":{"role":"symbol","title":"HMSQualityLimitationReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReason"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSQualityLimitationReasonBandwidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1bandwidth\/title","value":"kHMSQualityLimitationReasonBandwidth"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1bandwidth\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonBandwidth"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/title","value":"HMSQualityLimitationReason"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}