{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unkown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreason\/unkown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsqualitylimitationreason\/unkown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/unkown","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unkown"}],"title":"HMSQualityLimitationReason.unkown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@HMSQualityLimitationReason@kHMSQualityLimitationReasonUnkown","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason":{"role":"symbol","title":"HMSQualityLimitationReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSQualityLimitationReason"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSQualityLimitationReason"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSQualityLimitationReason/unkown":{"role":"symbol","title":"HMSQualityLimitationReason.unkown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unkown"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSQualityLimitationReason\/unkown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}],"url":"\/documentation\/hmssdk\/hmsqualitylimitationreason\/unkown"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kHMSQualityLimitationReasonUnkown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/title","value":"HMSQualityLimitationReason"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason\/fragments","value":[{"kind":"identifier","text":"HMSQualityLimitationReason"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1unkown\/title","value":"kHMSQualityLimitationReasonUnkown"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSQualityLimitationReason~1unkown\/fragments","value":[{"kind":"identifier","text":"kHMSQualityLimitationReasonUnkown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}