{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResult","text":"HMSPollQuestionResult"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmspollresult\/questions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmspollresult\/questions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResult\/questions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The list of question results for the poll."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestionResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResult"},{"kind":"text","text":"]"}],"title":"questions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@HMSSDK@objc(cs)HMSPollResult(py)questions","modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"questions"}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResult"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollResult":{"role":"symbol","title":"HMSPollResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollResult"}],"abstract":[{"type":"text","text":"Represents the result of a poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollResult"}],"url":"\/documentation\/hmssdk\/hmspollresult"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollQuestionResult":{"role":"symbol","title":"HMSPollQuestionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSPollQuestionResult"}],"abstract":[{"type":"text","text":"Represents the result of a poll question within a poll result."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollQuestionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSPollQuestionResult"}],"url":"\/documentation\/hmssdk\/hmspollquestionresult"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSPollResult/questions":{"role":"symbol","title":"questions","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"questions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"HMSPollQuestionResult","preciseIdentifier":"c:@M@HMSSDK@objc(cs)HMSPollQuestionResult"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The list of question results for the poll."}],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSPollResult\/questions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"questions"}],"url":"\/documentation\/hmssdk\/hmspollresult\/questions"},"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"questions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"questions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<HMSPollQuestionResult *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"questions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResult\/title","value":"HMSPollResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResult\/fragments","value":[{"kind":"identifier","text":"HMSPollResult"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResult\/title","value":"HMSPollQuestionResult"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollQuestionResult\/fragments","value":[{"kind":"identifier","text":"HMSPollQuestionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResult~1questions\/title","value":"questions"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSPollResult~1questions\/fragments","value":[{"kind":"identifier","text":"questions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}