{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveVideoData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/hmssdk\/hmsscreenvideobufferreceiver\/didreceivevideodata(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/hmssdk\/hmsscreenvideobufferreceiver\/didreceivevideodata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenVideoBufferReceiver\/didReceiveVideoData(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"HMSSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didReceiveVideoData:"}],"role":"symbol","title":"didReceiveVideoData(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveVideoData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)HMSScreenVideoBufferReceiver(im)didReceiveVideoData:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"16.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenVideoBufferReceiver"]]},"references":{"doc://live.100ms.HMS/documentation/HMSSDK":{"role":"collection","title":"HMSSDK","abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK","kind":"symbol","type":"topic","url":"\/documentation\/hmssdk"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenVideoBufferReceiver":{"role":"symbol","title":"HMSScreenVideoBufferReceiver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HMSScreenVideoBufferReceiver"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenVideoBufferReceiver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HMSScreenVideoBufferReceiver"}],"url":"\/documentation\/hmssdk\/hmsscreenvideobufferreceiver"},"doc://live.100ms.HMS/documentation/HMSSDK/HMSScreenVideoBufferReceiver/didReceiveVideoData(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveVideoData:"}],"role":"symbol","title":"didReceiveVideoData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveVideoData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/live.100ms.HMS\/documentation\/HMSSDK\/HMSScreenVideoBufferReceiver\/didReceiveVideoData(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/hmssdk\/hmsscreenvideobufferreceiver\/didreceivevideodata(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"16.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didReceiveVideoData:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveVideoData:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveVideoData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenVideoBufferReceiver\/title","value":"HMSScreenVideoBufferReceiver"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenVideoBufferReceiver\/fragments","value":[{"kind":"identifier","text":"HMSScreenVideoBufferReceiver"}]},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenVideoBufferReceiver~1didReceiveVideoData(_:)\/title","value":"didReceiveVideoData:"},{"op":"replace","path":"\/references\/doc:~1~1live.100ms.HMS~1documentation~1HMSSDK~1HMSScreenVideoBufferReceiver~1didReceiveVideoData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveVideoData:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}